### ISSUE TITLE
alternative run command 

### ISSUE THREAD

**Issue by kapilt** [capitalone/cloud-custodian#1000]
Lots of folks are doing various wrapper scripts, worth looking at what a built-in one might look like. 

Goals
 - parallel execution
 - support multiple accounts
 - support multiple regions

That implies a separate config file.

**Comment by JohnTheodore** [comment]
How would the multi-threading work? Each unique account+region combo would get their own thread, up to some threshold of max threads? thoughts on the threshold? There is a 4th bullet point of running arbitrary quantity of policies too, no?

**Comment by JohnTheodore** [comment]
What do you imagine the config file would look like? a yaml file where you can specify which accounts to execute on, where those credentials are, what regions for each account (a setting for all regions), and what policies for which regions? 

perhaps the default would be to apply run everything in /policies? but you could manually specify different account+region runs to use certain policies?

**Comment by kapilt** [comment]
re config file,  account ids, names, role, regions, tags.   i'd rather leave policy spec out of the config. its effectively a separate config file for account spec. and which policies to run is an at invocation time choice.

**Comment by scotwk** [comment]
Multiple regions is available in PR #967 .  Perhaps you are waiting on that one to decide if you want a more integrated approach.

**Comment by kapilt** [comment]
i think we'll end up at integrated approach but perhaps distinct from the extant run as run many will need a new config file.

**Comment by kapilt** [comment]
merged as tools/c7n_org
