### ISSUE TITLE
What is the best way to set up a policy that emails HTML and sends to SNS topic?

### ISSUE THREAD

**Issue by caversa** [capitalone/cloud-custodian#1017]
As I have a use case to email our resource owner as well as publish to a slack channel, I took advantage of putting both in the 'to' of my notification section of my policy.   SNS is not really intended for HTML however (email subscribers to an SNS topic get literally the html tags in their message), so I had written a mini-mod to strip out the HTML from the message if the 'to' was an SNS topic.  With a fairly basic template, this works quite well.  

However, I really like the output of the latest default.html.js , so am going to use that for my email - but it doesn't 'look' good for my stripped down SNS message.

As a workaround, I currently have two notification sections in my test policy - one that defines the HTML email template, with a to going to my resource owner.  The second notification section goes to the SNS topic, with a separate non-HTML template.  

This does work - but adds a lot of bulk to every policy, and there's duplicate settings such as the transport section, action_desc, and violation_desc (which is error prone in consistency if I need to tweak). So before I mass change my policies, I wanted to ask whether this is the right approach, or if there is a more efficient way of doing this.  For example, if the target 'To' is an SNS topic, could it look for the non-HTML version (named the same but without the .html) of that template to avoid a repeated notification section?  

Any advice is appreciated!

  actions:
    - type: notify
      template: default.html
      subject: Tagging Compliance Violation in {{ account }}
      violation_desc: "The following EC2(s) are not tagged properly:"
      action_desc: "The EC2(s) have been terminated."
      to:
        - resource-owner
      transport:
        type: sqs
        queue: https://sqs.MYREGION.amazonaws.com/MYACCOUNT/cloud-custodian-queue
    - type: notify
      template: default
      subject: Tagging Compliance Violation in {{ account }}
      violation_desc: "The following EC2(s) are not tagged properly:"
      action_desc: "The EC2(s) have been terminated."
      to:
        - arn:aws:sns:MYREGION:MYACCOUNT:Cloud-Custodian
      transport:
        type: sqs
        queue: https://sqs.MYREGION.amazonaws.com/MYACCOUNT/cloud-custodian-queue
    - terminate

**Comment by kennyg** [comment]
i'd like to see something like this bumped up in priority. We're currently using SimianArmy janitor monkey to send notifications, and we'd like to use cloud-custodian to replace it. i'm struggling getting c7n_mailer to work. i'm getting this error TypeError: __init__() takes at most 6 arguments (8 given).

**Comment by kapilt** [comment]
@caversa  re sns topic and mailer, you can subscribe a mailer sqs queue to the sns topics.

@kennyg there was a drift issue with the 0.8.21.3 release and mailer trunk, since resolved with 0.8.24 release.
