### ISSUE TITLE
Age and Expiration value_type doesn't have default time zone

### ISSUE THREAD

**Issue by cplee** [capitalone/cloud-custodian#1019]
I’m trying to define a policy that matches on ec2 instances that are “expired”, where the expiration date is defined as a tag on the instance: `c7n_expiration: 2017-03-01`. I have a policy filter that uses the expiration value_type to match on the instances that are “expired”:

```
   - type: value
      key: tag:c7n_expiration
      op: lt
      value_type: expiration
      value: 0
```
The problem is the op() throws TypeError because the value_types of `expiration` and `age` both parse the value without a default timezone.

**Comment by kapilt** [comment]
merged
