### ISSUE TITLE
ssl listener filter should annotate which listener triggered

### ISSUE THREAD

**Issue by kapilt** [capitalone/cloud-custodian#103]

**Comment by kapilt** [comment]
annotate elb with listener name/port  and the actual protocol that matches (tls1.0, cipher, etc).

**Comment by naveenb29** [comment]
+1

**Comment by bclodius** [comment]
@kapilt I'm going through cloud custodian during my free time; I want to try to implement this but cannot give any guarantees 😄

**Comment by kapilt** [comment]
That would be great! basically modifying the filter to annotate the elb struct inline if matches

**Comment by kapilt** [comment]
merged
