### ISSUE TITLE
have mark action for volumes to allow for unattached volume cleanup

### ISSUE THREAD

**Issue by jmahowald** [capitalone/cloud-custodian#1037]
It would be nice if there were rules that allowed us to clean up dangling volumes that frequently occur during automation development.  I think that if there were a mark action on volumes, it could be done by having a filter to detect volumes with no instances attached, then mark and sweep later.
Thoughts?  Or are there other ways of achieving this?

**Comment by kumarsiyer** [comment]
@jmahowald you can achieve this... 

custodian schema ebs
ebs:
  actions: [copy-instance-tags, delete, encrypt-instance-volumes, invoke-lambda, mark,
    mark-for-op, normalize-tag, notify, remove-tag, rename-tag, tag, tag-trim, unmark,
    untag]
  filters: [and, event, fault-tolerant, health-event, instance, kms-alias, marked-for-op,
    metrics, not, or, tag-count, value]

**Comment by jmahowald** [comment]
thanks, closing
