### ISSUE TITLE
Bug in c7n/resources/rds.py

### ISSUE THREAD

**Issue by JamieRodgers** [capitalone/cloud-custodian#1043]
Lines 370-372 in rds py 

`params = {'AutoMinorVersionUpgrade': self.data.get('minor', True)}`
 `       if self.data.get('window'):`
 `           params['PreferredMaintenanceWindow'] = self.data['minor']`

I was trying to implement an RDS policy to enable auto-patching and when running the example policy in rds.py I got parameter validation errors against PreferredMaintenanceWindow. The above code is assigning a boolean value (minor) to a string parameter (PreferredMaintenanceWindow). Below are the lines in the example policy (lines 355-358 in rds.py) where I discovered the issue. After I removed the window property the policy worked perfectly. Probably needs line 372 to be set to self.data['window'] rather than self.data['minor'] but I don't have full context of the code!

`    actions:`
  `      - type: auto-patch`
         ` minor: true`
		`  window: Mon:23:00-Tue:01:00`

**Comment by scotwk** [comment]
@JamieRodgers - I agree with your assessment, thanks for debugging.  There was no test for that code path so I added one.

**Comment by scotwk** [comment]
@JamieRodgers - fixed in #1046
