### ISSUE TITLE
How to encrypt individual buckets? 

### ISSUE THREAD

**Issue by srinivas-anant** [capitalone/cloud-custodian#1047]
Is there a way to check for encryption and also for bucket policies if they are present on a single bucket? Below is the yaml file I created for checking single bucket and the log the CC returns. 

policies:
  - name: s3-key-encryption
    description: |
        Encrypt s3 buckets
    resource: s3
    filters:
      - type: value
        key: bucket
        op: equal
        value:
            - _bucket-name_
    actions:
      - type: encrypt-keys
        crypto: AES256

`$ custodian run --dryrun -c bucket-encryption.yml -s out 
2017-03-27 16:19:22,407: custodian.policy:INFO Running policy s3-key-encryption resource: s3 region:us-west-2 c7n:0.8.23.2
2017-03-27 16:19:22,408: custodian.policy:INFO policy: s3-key-encryption resource:s3 has count:0 time:0.00
`

**Comment by kapilt** [comment]
key: Name

**Comment by kapilt** [comment]
easiest way for this is

is just a filter with
```
  - Name: bucket_name
```

**Comment by srinivas-anant** [comment]
Thank you.
