### ISSUE TITLE
Custodian output logs for scheduled policy (Lambda)

### ISSUE THREAD

**Issue by victorh3** [capitalone/cloud-custodian#1063]
If I've set up my policy to run on a schedule through Lambda, where can I define where the output logs will go? Can I send them to an S3 bucket? Or are there no logs when Custodian runs as a Lambda function?

**Comment by victorh3** [comment]
Specifically looking for the resource.json. I see Lambda/Custodian taking actions on my resources, such as marking them, but cant find a way to access or save resource.json

**Comment by victorh3** [comment]
Figured solution to push resource.json from tmp folder to S3 bucket

**Comment by sreeramsanjay** [comment]
Hi, could you share the solution here,i am also looking for similar kind of solutions.

**Comment by sri321** [comment]
same here 
@victorh3 : can you share the solution?
