### ISSUE TITLE
ec2 offhour support

### ISSUE THREAD

**Issue by ManojPN** [capitalone/cloud-custodian#1074]
My CloudCustodian policy for offhour. it is as follows
policies:
  - name: offhour_stop
    resource: ec2
    comments: |
      Daily stoppage at 6pm
    filters:
      - type: offhour
        tag: cc_downtime
        offhour: 18
        default_tz: est
    actions:
      - stop
i created two ec2 instance with tag "cc_downtime" they are running on the default region(us-east-1). And i configured aws cli for the same region. When i used ec2 offhour filter as mentioned in the document for ec2 instance to stop at 6pm, it results me this,
$ custodian run -d ec2-offhour-policy.yml -s out                      
custodian.policy:INFO policy: offhour_stop resource:ec2 has count:0 time:0.00
i don't know what is the problem with the policy i wrote, is that because its not finding ec2 instance with right tag ?, or  Is there any problem with the time zone i mentioned?.I am a newbee to this, can anybody help?. @kapilt

**Comment by kapilt** [comment]
the offhour filter only triggers when the current time has the specified hour in either the tag value or the default offhour value (6pm est in this case).  if you run it at a different time it won't match.

**Comment by ManojPN** [comment]
Thank you @kapilt
