### ISSUE TITLE
creating reports for multiple policies 

### ISSUE THREAD

**Issue by srinivas-anant** [capitalone/cloud-custodian#1076]
Is there a way to create reports for multiple policies?

**Comment by kapilt** [comment]
what would that look like? the csv format is resource specific. do you have an example of what your thinking about?

**Comment by srinivas-anant** [comment]
If I create say a policy for tag compliance and s3 global grants and put both of them in the same yaml file and I try to generate report for it? Will that be possible?

**Comment by scotwk** [comment]
@srinivas-anant - currently, no.  The report can only accept a single policy.

(Note that you could put multiple policies into a single file and then generate a report on one of them by using filtering via `-p` or `-t` to narrow down to a single policy.  But I don't think that is the spirit of your question)

**Comment by srinivas-anant** [comment]
Alright thank you.

**Comment by nitinitare** [comment]
How can we generate csv file using report subcommand???

**Comment by rajat-pe** [comment]
Is this feature still not implemented ??
