### ISSUE TITLE
fix log output with py.test

### ISSUE THREAD

**Issue by kapilt** [capitalone/cloud-custodian#1082]
the log levels aren't taking across the xdist, boundary resulting in copious output from placebo

**Comment by kapilt** [comment]
removing the -v should suffice

**Comment by whit537** [comment]
> the switch to py.test has made the travis output pretty much unusable
unclear if its as simple as removing the -v
locally that still generated alot of verbosity, but also tied to local env wrt to separate virtualenvs on tools, and py.test picking up extraneous

https://gitter.im/capitalone/cloud-custodian?at=58f4e48708c00c092a8bdf64

**Comment by whit537** [comment]
> the switch to py.test has made the travis output pretty much unusable

Indeed. I am experiencing this first-hand under https://github.com/capitalone/cloud-custodian/pull/1084. :)

**Comment by whit537** [comment]
Here's the [culprit](https://github.com/capitalone/cloud-custodian/blob/18f5fd34eb48f58444ee6bf452f1cf9520854089/tests/common.py#L31):

```python
logging.getLogger('placebo.pill').setLevel(logging.DEBUG)
```

Looking at options ...

**Comment by whit537** [comment]
PR in https://github.com/capitalone/cloud-custodian/pull/1086.

**Comment by whit537** [comment]
Done in #1086.
