### ISSUE TITLE
Support for tagging in Lambda functions

### ISSUE THREAD

**Issue by tim-elliott** [capitalone/cloud-custodian#1088]
Now that Lambda functions support tagging, please add the following for the lambda resource type:
- Include tag information in output
- Filters: marked-for-op
- Actions: auto-tag-user, mark-for-op, remove-tag, tag

**Comment by alfredgamulo** [comment]
@kapilt I'll take care of this

**Comment by alfredgamulo** [comment]
Resolved with https://github.com/capitalone/cloud-custodian/pull/1092
