### ISSUE TITLE
c7n_mailer based on latest source code is broken

### ISSUE THREAD

**Issue by ringxw** [capitalone/cloud-custodian#1096]
Following the installation guide, it looks like c7n_mailer is broken due to changes to mu.py. 

```
(custodian)$ c7n-mailer -c mailer.yml
Traceback (most recent call last):
  File "/home/testusercloud-custodian/tools/c7n_mailer/c7n_mailer/cli.py", line 72, in main
    deploy.provision(config, functools.partial(session_factory, config))
  File "/home/testuser/cloud-custodian/tools/c7n_mailer/c7n_mailer/deploy.py", line 74, in provision
    archive = get_archive(config)
  File "/home/testuser/cloud-custodian/tools/c7n_mailer/c7n_mailer/deploy.py", line 38, in get_archive
    'memcache')
TypeError: __init__() takes at most 6 arguments (8 given)
> /home/testuser/cloud-custodian/tools/c7n_mailer/c7n_mailer/deploy.py(38)get_archive()
-> 'memcache')
```

By looking at the code, it looks like the older version of c7n installed from pip install compatible with the source code from top of the tree.   https://github.com/capitalone/cloud-custodian/commit/1be171dbdf48d80c1b640c499d9fe6b2194255dc   

What should I do to get around this? just checkout a specific commit before the one that breaks c7n-mailer? Is there a planned new version of pip?

**Comment by kennyg** [comment]
i'm also interested in a workaround to this. it appears it's fixed in 0.8.23.2, but, i've yet to successfully install it.

**Comment by ringxw** [comment]
@kennyg so I had to do a git checkout 34d74e0dce6a2eb8599311947a4b2fea3036d466 to rollback c7n_mailer that works with c7n 0.8.23.1

**Comment by kennyg** [comment]
that did the trick! thanks

**Comment by ringxw** [comment]
any update on when the next version of c7n will be released through pip?

**Comment by kapilt** [comment]
I'll try and get this sorted monday, currently traveling.

**Comment by ringxw** [comment]
good to know, thanks @kapilt

**Comment by kapilt** [comment]
so current trunk has a regression which is preventing release per #1111

**Comment by kapilt** [comment]
0.8.24 released
