### ISSUE TITLE
ELB set-ssl-listener-policy shouldn't delete other non-ssl related policies.

### ISSUE THREAD

**Issue by alfredgamulo** [capitalone/cloud-custodian#1097]
Currently the set-ssl-listener-policy action replaces all policies for the listener including LBCookieStickinessPolicy.

The action should first get the list of all policies and find/replace only the policies that have the `"PolicyTypeName": "SSLNegotiationPolicyType"`.

**Comment by salwandhruvdev** [comment]
@kapilt I am working on this.
Thanks.
