### ISSUE TITLE
Not able to run cloud-custodian from a centralised EC2-instance for multiple accounts.

### ISSUE THREAD

**Issue by srinivas-anant** [capitalone/cloud-custodian#1102]
I am trying to run cloud custodian policies from a centralised instance, for multiple accounts using assume role, but when I run the CLI for a particular account the same output I am getting for another account, how to fix this? And also do I need access_key and secret_access_key present on the instance for cloud custodian to run?

**Comment by Iron-Bound** [comment]
Hey S-A

Would recommend to post the command if this fails to work, but try using the "--cache" file option when your running against multiple accounts.

Example: 
--cache /home/custodian/.accountname.cache

Have resolve this issue in the past so confidence it will help.

Cheers,
AB

More info here:
https://groups.google.com/d/msg/cloud-custodian/w5sHHRA7pIQ/V_fZrTFtEgAJ

**Comment by srinivas-anant** [comment]
Thank you @Iron-Bound. Didn't explore the "--cache" option when running it on an instance because when I ran it from my local machine it would work without any issues.

**Comment by srinivas-anant** [comment]
@Iron-Bound If you have run custodian from an instance for cross accounts how did you make the instance assume a role? I keep getting an error saying the instance is not allowed to assume a the role.

**Comment by kapilt** [comment]
Cache file is currently account specific, a different file can be passed on the CPI per account.
