### ISSUE TITLE
assume role doesn't work new account id detection on trunk

### ISSUE THREAD

**Issue by kapilt** [capitalone/cloud-custodian#1111]
account id is picked up prior to the role assume

**Comment by cmedley** [comment]
@scotwk if it helps, patched local using https://github.com/cmedley/cloud-custodian/commit/e14d8190b08684ca266736d8ac7c9789c82eff92

**Comment by scotwk** [comment]
@cmedley - thanks for the guidance that the account ID is included in the assumed role.
