### ISSUE TITLE
sending email through SMTP server sends attachments

### ISSUE THREAD

**Issue by ringxw** [capitalone/cloud-custodian#1112]
Not sure if it's something that only I'm seeing or it's designed that way. 
I initially had a setup for sending emails through SES, after discovering the smtp feature I switched to use an existing smtp server to send out notifications. 
The emails gets delivered, but the content is in an attachment filewith a standard name, e.g. "ATT0001" .  Is this the expected behaviour?   I can't really tell from the code, since it's just using smtplib.sendmail. 

Thanks!

**Comment by kapilt** [comment]
the smtp functionality on the mailer is new and i haven't used it yet, it could be it needs a email mime type wrapper. @JohnTheodore could you comment on the attachment behavior?

**Comment by JohnTheodore** [comment]
@ringxw on a fresh setup I just checked out HEAD from capitalone/cloud-custodian.

My mailer.yml is this:
`queue_url: https://sqs.us-east-1.amazonaws.com/xxxxxxxxx/cloudcustodian-mailer
role: arn:aws:iam::172119256206:role/cloudcustodian-mailer
region: us-east-1
from_address: DL-CPE-AWS-CloudCustodian@example.com
smtp_server: smtp.example.com
smtp_port: 25
smtp_ssl: True

contact_tags:
  - OwnerEmail
  - SupportEmail`

and my default.html.j2 is this: https://gist.github.com/JohnTheodore/abb669a7eb7a41a8a89244b851fa1e7b

and everything works. The html email displays fine in outlook, office365 and gmail.

Would you dump your mailer.yml and default.html.j2 into a gist and link in a comment?

**Comment by JohnTheodore** [comment]
https://kb.mit.edu/confluence/pages/viewpage.action?pageId=4981187 .. are you inlining an attachment? try sending the email with no attachment.

**Comment by ringxw** [comment]
Hi @JohnTheodore  thanks for the update.  I'm using the default.j2 template
It just needed to 
`    actions:
      - type: notify
        template: default`
How can I use the default html? Should I do
`template: default.html`

**Comment by ringxw** [comment]
Using default.html as template works. default just sends attachments.

**Comment by JohnTheodore** [comment]
I'm glad the smtp feature is working for you. Check out priority_headers in your notify section too, you can add an exclamation point or whatever to important emails (like deleting resources).

**Comment by cmedley** [comment]
@ringxw this should fix attachment using default https://github.com/capitalone/cloud-custodian/pull/1220
