### ISSUE TITLE
EMR Unnecessarily Querying for Terminated Clusters

### ISSUE THREAD

**Issue by aiell0** [capitalone/cloud-custodian#1117]
When doing a `list_clusters` call for the EMR resource, AWS and boto currently return ALL of the EMRs, including ones that were terminated. Since the default API rate limits for EMR are low, this causes problems related to throttling when the data from `list_clusters` is augmented with the response from the API call `describe_clusters`, since the latter requires it to be called for each cluster separately.

My solution involves passing the following as `extra_args`: `{'ClusterStates': ['WAITING', 'BOOTSTRAPPING', 'RUNNING', 'STARTING']}`.

This will only list the clusters that have not been terminated. From the current list of actions in cloud custodian for EMR, none of them apply to terminated clusters (or ones that are terminating). This is also to my knowledge and experience. There may be disagreements.

I will fork and submit the fix shortly.

**Comment by kapilt** [comment]
thanks for the pr
