### ISSUE TITLE
Windows Compatability

### ISSUE THREAD

**Issue by astrix37** [capitalone/cloud-custodian#113]
I've noticed when using mu that it has a few lines of code that aren't windows compatible. 

Specfically a call to os.uname() which is not available in windows (https://docs.python.org/dev/library/os.html#os.uname) 

Using tempfile.NamedTempFile which cannot be opened a second time for reading bytes on windows (https://docs.python.org/2/library/tempfile.html)

Are there plans to support Windows? Or am I missing something that overcomes the aforementioned problems?

**Comment by kapilt** [comment]
Thanks!, any efforts to help with Windows support would be welcome.  Attempts have been made to use portable constructs, but none of the core developers or ci infrastructure currently use windows so we only have occasional users questions wrt. The os.uname is easy to fix, the tempfile usage is a bit trickier (delete=False constructor to named tempfile and then wiring in cleanups).

**Comment by astrix37** [comment]
I don't often comment on libraries so it's nice to get a speedy response when I do! Thanks!

I'm glad I could help and will gladly note down any windows issues that I come across.
