### ISSUE TITLE
How to run cloud custodian without access_id and secret_access_key?

### ISSUE THREAD

**Issue by srinivas-anant** [capitalone/cloud-custodian#1133]
Is there a way to run cloud custodian without creating a IAM user? Can it be run by passing only the assume role from an instance? 

@kapilt @scotwk

**Comment by scotwk** [comment]
Sorry, I don't know.  That should be easy to try, right?

**Comment by kapilt** [comment]
@srinivas-anant you can use any aws credential mechanism with custodian. you do not need an iam user. the sdk will automatically source credentials from environment variables and the metadata server if run on instance with an instance role. on the cli you can also pass a profile.

**Comment by srinivas-anant** [comment]
Thanks @kapilt. So I used the temporary credentials provided but the instance profile, after I do a dry run and I try generating report of the dry run I get this error message. 

```Empty policy file(s).  Nothing to do.
Error: Report subcommand requires exactly one policy```

**Comment by scotwk** [comment]
Whats your policy file?  It's saying it is empty (i.e. no policies in it).  

Also, what version of custodian are you running?  There was a bug in master recently that may have printed this message even without an empty policy file.
