### ISSUE TITLE
multi-region support needs to suffix region on output location

### ISSUE THREAD

**Issue by kapilt** [capitalone/cloud-custodian#1152]
on trunk, with the new multi-region support, we effectively generate a separate copy of the policy per region, but we also need to do a region specific output directory, else the outputs of one region will stomp on another region.

@scotwk

**Comment by kapilt** [comment]
this is probably a release blocker

**Comment by scotwk** [comment]
@kapilt - will try to fix tonight.  Both S3 and local?

**Comment by kapilt** [comment]
Fixed in #1150
