### ISSUE TITLE
Seeking to understand value_type: swap as it relates to resource: account

### ISSUE THREAD

**Issue by mgoins01** [capitalone/cloud-custodian#1163]
Am new to CloudCustodian and thought it'd be a good learning opportunity to implement the CIS AWS benchmarks w/CloudCustodian.

Am interested in CIS 1.12 'Ensure no root account access key exists', and CIS 1.13 'Ensure MFA is enabled for the root account', and am having some trouble.

Saw the yml below in the comments of the account.py script.  ? - am not seeing how the code below determines whether mfa is enabled for the root user, or the root user has api keys -?

policies:
- name: root-keys-or-no-mfa
  description: determine if an account has either not been enabled with root mfa or has root api keys.
  resource: account
  filters:
    -type: iam-summary
    key: AccountMFAEnabled
    value: true
    op: eq
    value_type: swap

Thanks.

**Comment by kapilt** [comment]
value_type: swap is when your comparing a scalar value to a list value. by default we assume the scalar is the resource attribute, and the list is the policy value. if you want to reverse that assumption value_type: swap does the trick. ie. normally we might say filter ec2 to see if the ami ids are in a given set then the default semantics work and we can just do an op: in, but say we wanted to match on security group ids to a known security group, now the resource has the list, and the policy the scalar, to do the `op: in` we need to swap the resource and policy value for the comparison operator to work. its a bit of goo, and alternate spelings welcome, but its what we got for now.

in this context, say on iam summary you don't need the value_type: swap, as your comparing two scalars.
