### ISSUE TITLE
are root user credentials queryable via resource: iam-user; type: credential?

### ISSUE THREAD

**Issue by mgoins01** [capitalone/cloud-custodian#1164]
Am new to CloudCustodian & am looking at options re: to CIS 1.12 & 1.13 - saw that account.py (https://github.com/capitalone/cloud-custodian/blob/master/c7n/resources/account.py) runs 'generate-credential-report' & 'get-credential-report', which when i run them from the command line, shows the status of various settings for the root account, leading me to believe i could use the query below to query root account settings, but its output is blank.

- name: iam-filter-for-root
  description: |
    filter for root
  resource: iam-user
  filters:
    - type: credential
      key: arn
      value: arn:aws:iam::<aws account number>:root

If i pick another user listed in the credential report by arn, it works.

? - is there a way to query & act on root user settings via custodian?

**Comment by kapilt** [comment]
root api key status are queryable using the account resource via either `iam-summary` or `credential` filters. root users are not iam users per aws apis.
