### ISSUE TITLE
is there capability to compare two JMESpath attributes?

### ISSUE THREAD

**Issue by mgoins01** [capitalone/cloud-custodian#1173]
Am working on implementing CIS AWS Benchmarks, and am working on CIS 1.23 "IAM users with keys created at user creation time."

Is there a way to compare two JMESpath attributes?

Within resource iam-user, type credential - Am seeking to compare   user_creation_time with access_keys.last_rotated.  If equal, it indicates the keys were created at account creation time.

policies:
- name: iam-users-with-keys-created-at-user-creation-time
  description: |
    CIS 1.23 IAM users with keys created at user creation time.
  resource: iam-user
  filters:
    - type: credential
      key: access_keys.active
      value: true
    - type: credential
      key: user_creation_time
      op: eq
      value: access_keys.last_rotated
#    - access_keys.last_rotated = user_creation_time

**Comment by kapilt** [comment]
there isn't but we could add something like that as a value_type: expr or jmespath

**Comment by mgoins01** [comment]
that'd be great - could see several use cases for having the capability.  thanks for the reply.
