### ISSUE TITLE
Is it mandatory to set --region while running in new version 0.8.24.1 ? This was not the case with previous version

### ISSUE THREAD

**Issue by kumarsiyer** [capitalone/cloud-custodian#1179]

**Comment by scotwk** [comment]
@kumarsiyer - it should not be mandatory.  It still sets a default region if it is not supplied.  Are you getting an error?  If so, please share

**Comment by kumarsiyer** [comment]
@scotwk custodian run --assume xxx -c xxx.yml -s ./out --cache-period 0
2017-05-18 17:53:17,333: c7n.policies:WARNING policy:ami resources:ec2 not available in region:None
Empty policy file(s).  Nothing to do.

**Comment by scotwk** [comment]
@kumarsiyer - looks like it is not finding your default region.  what does this command return for you?

`python -c 'import boto3; print(boto3.Session().region_name)'`

**Comment by kumarsiyer** [comment]
` python -c 'import boto3; print(boto3.Session().region_name)'
None`

**Comment by scotwk** [comment]
@kumarsiyer - set a default in your `~/.aws/config`.  Here is mine:

```
$ cat ~/.aws/config
[default]
region = us-east-1
```

I'm going to close this, but feel free to re-open if you have more questions

**Comment by kumarsiyer** [comment]
yeah, I noticed that. Sorry should have checked the ENV variables :( my bad

**Comment by scotwk** [comment]
@kumarsiyer - no worries - it is not a helpful error message.  I am going to make this more user friendly.  I've submitted PR #1196 for this.
