### ISSUE TITLE
Exponential Backoff not working for EMR

### ISSUE THREAD

**Issue by aiell0** [capitalone/cloud-custodian#1180]
The retry function in utils.py was looking for the wrong throttling exception for EMR. Instead of `Throttled`, it's `ThrottlingException`. I have also added the retry handler for the AddTags API, as that is even more restrictive than the DescribeClusters API.

PR: https://github.com/capitalone/cloud-custodian/pull/1181

**Comment by kapilt** [comment]
thanks for the pr
