### ISSUE TITLE
Report Subcommand Help

### ISSUE THREAD

**Issue by ascott58** [capitalone/cloud-custodian#1199]
Hi, I am trying to run the 'report' subcommand (i.e. custodian report) on a policy file just to see what resources match each policy in the file.

I'm running the command "custodian report -p 'My_Policy_Name' My_Policy_File --output-dir=My_Dir --assume My_Role".

If I run this command, no output is produced, and no resources are shown at all. But if I run 'custodian run' on the same policy file and role beforehand (with --cache-period=0), and THEN run the custodian report command above, it generates the correct output and all correct resources are shown.

Why is this? My goal is to use the report command so I can get a CSV output of resources matching a certain policy of a policy file.

Also, in the 'custodian report -h' output is says output directory is optional, but when running it without an output directory parameter it spits an error.

Thanks.

**Comment by scotwk** [comment]
The input to `report` is what `run` produces, so you are correct that it will produce nothing until you run your policy.  I think what you were hoping in order to find what resources match a policy is `run` with the `--dryrun` option (and then using `report`)

This is a common confusion, and if you have a suggestion for how to improve it we can try to improve the help.  

It doesn't show as optional for me:

```
usage: custodian report [-h] [--profile PROFILE] [--assume ASSUME_ROLE]
                        [-p POLICY_FILTER] [-t RESOURCE_TYPE] [-v] -s
                        OUTPUT_DIR [--days DAYS] [--raw RAW]
                        [--field HEADER=FIELD] [--no-default-fields]
                        [--format {csv,grid,simple}]
                        [configs [configs ...]]
```

Note that it isn't in brackets.

(closing this issue, but feel free to re-open with more comments or questions)

**Comment by ascott58** [comment]
Okay thanks for the info. And that's ddd, it shows up as an option, ad the --format option is not even there.

**usage: custodian report [-h] [--profile PROFILE] [--assume ASSUME_ROLE]
                        [-p POLICY_FILTER] [-t RESOURCE_TYPE] [-v] -s
                        OUTPUT_DIR [--days DAYS] [--raw RAW]
                        [--field HEADER=FIELD] [--no-default-fields]
                        [configs [configs ...]]**

CSV report of resources that a policy matched/ran on

optional arguments:
  -h, --help            show this help message and exit
  -v, --verbose         Verbose logging
  **-s OUTPUT_DIR, --output-dir OUTPUT_DIR
                        Directory or S3 URL For policy output**
  --days DAYS           Number of days of history to consider
  --raw RAW             Store raw json of collected records to given file path
  --field HEADER=FIELD  Repeatable. JMESPath of field to include in the output
                        OR for a tag use prefix `tag:`
  --no-default-fields   Exclude default fields for report.

provider:
  AWS account information, defaults per the aws cli

  --profile PROFILE     AWS Account Config File Profile to utilize
  --assume ASSUME_ROLE  Role to assume

config:
  Policy config file(s) and policy selectors

  configs               Policy configuration file(s)
  -p POLICY_FILTER, --policies POLICY_FILTER
                        Only use named/matched policies
  -t RESOURCE_TYPE, --resource RESOURCE_TYPE
                        Only use policies with the given resource type

**Comment by ascott58** [comment]
optional arguments:
****  -h, --help            show this help message and exit
  -v, --verbose         Verbose logging
  **-s OUTPUT_DIR, --output-dir OUTPUT_DIR
                        Directory or S3 URL For policy output**
  --days DAYS           Number of days of history to consider
  --raw RAW             Store raw json of collected records to given file path
  --field HEADER=FIELD  Repeatable. JMESPath of field to include in the output
                        OR for a tag use prefix `tag:`
  --no-default-fields   Exclude default fields for report.


I'm using version 0.8.23.2.

And thanks for the rest of the info :)

**Comment by ascott58** [comment]
optional arguments:
  -h, --help            show this help message and exit
  -v, --verbose         Verbose logging
  -s OUTPUT_DIR, --output-dir OUTPUT_DIR
                        Directory or S3 URL For policy output
  --days DAYS           Number of days of history to consider
  --raw RAW             Store raw json of collected records to given file path
  --field HEADER=FIELD  Repeatable. JMESPath of field to include in the output
                        OR for a tag use prefix `tag:`
  --no-default-fields   Exclude default fields for report.

I'm using version 0.8.23.2

And thanks for the rest of the info :)

**Comment by scotwk** [comment]
ah, i see the header.  Thanks
