### ISSUE TITLE
Request silent/quiet mode

### ISSUE THREAD

**Issue by JAizen** [capitalone/cloud-custodian#1202]
As title mentions, silent/quiet mode would be great.

**Comment by scotwk** [comment]
@kapilt @JAizen - how quiet is quiet?  Should errors print?  Or swallow everything?

**Comment by JAizen** [comment]
@scotwk personally, shallowing everything would be ideal.

**Comment by scotwk** [comment]
@JAizen - see my comment in PR #1219 and let me know if you have thoughts or suggestions

**Comment by kapilt** [comment]
merged to trunk
