### ISSUE TITLE
explicit validation support on policy as method

### ISSUE THREAD

**Issue by kapilt** [capitalone/cloud-custodian#1240]
previous related #508  #733

**Comment by scotwk** [comment]
Per our phone call - we want to move validation to be an explicit method on policies that we can call after we do variable subtitution.  Right now it happens at policy load.

**Comment by scotwk** [comment]
@kapilt - worked on this tonight and just making sure I have the big picture correct.  When we `run` a set of policies, we:

- Remove the existing schema validation step
- Load all policies into a PolicyCollection (including region or other expansions)
- While creating each `Policy` instance, follow the schema for the policy's resource and swap variables for any field.  (This work may be in a future PR)
- After all `Policy`s are created, validate them and if any are invalid report those and exit before running anything.  This validation method should go beyond the schema validation, it should also catch things like the two issues you mentioned above.

It looks like we can simplify the `validate` command as well, removing a lot of the duplicate code that it is doing.

**Comment by kapilt** [comment]
doh.. i took at stab at the validate part this morning, it was mostly about fixing the tests with the change from implicit filter/action validation on construction to doing it explicitly in policy validate, and additionally doing additional mode validation.

wrt to vars, the only concern is that we'll be moving the validation to effectively late bound instead of at load time, ie. wondering if we need to push expand regions/ expand vars down or just leaving everything in commands.py/cli binding
