### ISSUE TITLE
elasticsearch indexing of metrics and records outputs

### ISSUE THREAD

**Issue by kapilt** [capitalone/cloud-custodian#125]

**Comment by kapilt** [comment]
tools/c7n_indexer provides for cloud watch metrics indexing into influxdb at the moment.

**Comment by pawanaichra-datagrokr** [comment]
@kapilt what needs to be done next related to this??
Can you please give me some ideas or hints??

**Comment by pawanaichra-datagrokr** [comment]
@kapilt what needs to be done next related to this??
Can you please give me some ideas or hints??
