### ISSUE TITLE
c7n_mailer e-mail CC support

### ISSUE THREAD

**Issue by mwkaufman** [capitalone/cloud-custodian#1264]
Feature request to support adding CC addresses for e-mail notifications sent by c7n_mailer. Today there is some logic to support the cc property for notifications, but it currently attaches a Python list of e-mail addresses to message on line 203 of c7n_mailer/sqs_message_processor.py instead of a comma-delimited string, causing any use of the cc property to throw the below error when sending the e-mail:

error: 'list' object has no attribute 'lstrip'

**Comment by kapilt** [comment]
merged in #1265, thanks for the pull request.
