### ISSUE TITLE
Auto Tagging All resources

### ISSUE THREAD

**Issue by football52** [capitalone/cloud-custodian#1296]
I have just started using Cloud Custodian. I'm testing out the auto tagging features to see what is and isn't possible. I don't see anywhere that Security Groups is a supported auto tagged resource.

What resources can you auto tag? Can you specify multiple resources for one policy? Or do you need to have multiple policies per resource?

**Comment by kapilt** [comment]
its currently enabled per resource. we should probably auto enable it for every resource that supports tag modification. `custodian schema --help` can be used to introspect resources and the filters/actions available for each. wrt to the current release and auto-taggable resources, the following set of resources support the action

```
elb
asg
ec2
hostedzone
rds
s3
healthcheck
glacier
lambda```

multiple resources can't be specified per policy, there's an extant issue #1244 wrt to supporting that in the future (under the hood these would be auto expanded into policy per resource). at the moment a policy targets one resource, and you have multiple policies per resource.

**Comment by football52** [comment]
I have already updated c7n to use this feature. It works great. 

Are only the resources mentioned above included in this? Or is every taggable resource included? Such as security groups, VPC, subnet, ect.

> elb
asg
ec2
hostedzone
rds
s3
healthcheck
glacier
lambda

**Comment by kapilt** [comment]
merged

**Comment by FireballDWF** [comment]
Request reopening as the following resources are taggable but custodian is not supporting tag actions:
1. waf
2. waf-regional
3. Elasticsearch (aka es)
4. KMS
4. r53domain

**Comment by scotwk** [comment]
Same comment as in the PR:

@FireballDWF - this PR was to add auto-tag-user to anything that supports the tag action.  It was not to add the tag action everywhere.  I think it would be more appropriate to open a new issue for any resources missing the tag action
