### ISSUE TITLE
Custom offhours schedule

### ISSUE THREAD

**Issue by mrpudn** [capitalone/cloud-custodian#13]
This would allow instances/asgs to define a custom off hours schedule via a tag (`c7n_downtime`).

**Schedule format:**

```py
# up mon-fri from 7am-7pm; eastern time
off=(M-F,19); on=(M-F,7)
# up mon-fri from 6am-9pm; up sun from 10am-6pm; pacific time
off=[(M-F,21),(U,18)]; on=[(M-F,6),(U,10)];tz=pt
```

**Possible values:**

| field | values |
| --- | --- |
| days | `M, T, W, H, F, S, U` |
| hours | `1, 2, 3, ..., 22, 23, 24` |

Days can be specified in a range (ex. `M-F`).

If the timezone is not supplied, it's assumed `et` (eastern time), but this default could be configurable.

**Parser output:**

The schedule parser will return a `dict` or `None` (if the schedule is invalid):
```py
# off=[(M-F,21),(U,18)],on=[(M-F,6),(U,10)],tz=pt
{
  off: [
    { days: "M-F", hour: 21 },
    { days: "U", hour: 18 }
  ],
  on: [
    { days: "M-F", hour: 6 },
    { days: "U", hour: 10 }
  ],
  tz: "pt"
}
```

**Help wanted:**

I was planning on working on the schedule parser, but I'd love to partner up with someone for the rest of it. Besides the schedule parser, what remains is determining the day and hour, taking the schedule `dict`, and determining if the instance/asg should be off.

**Comment by fdosani** [comment]
@mrpudn I'd be interesting in helping with this feature. I'd need to get up to speed with the cloud-custodian internals but would be a useful feature that shouldn't be too hard.

**Comment by fdosani** [comment]
I've been messing around with a parser. Hopefully it is useful (no worries if you wanted to approach it another way, just though it would be fun): https://github.com/fdosani/offhours-parser

**Comment by kapilt** [comment]
@fdosani thanks, that looks reasonable, fwiw, the offhours filter at the moment is localized to c7n/offhours.py

**Comment by fdosani** [comment]
I'll take a stab at integrating the two. 
Heading to DC tonight, so will try and get to it shortly unless @mrpudn wants to give it a go.

**Comment by mrpudn** [comment]
@fdosani - Awesome! I appreciate the help, and I'll take a look at what you've got so far.

I had some personal things to attend to the past couple of days, so I haven't had too much time to work on this. I did brush up on some regex stuff, though, and I'm hoping to prototype some ideas today.

**Comment by fdosani** [comment]
@mrpudn sounds good! 👍

**Comment by mrpudn** [comment]
@fdosani Awesome job on this so far. Great call on using the semicolon to separate each component of the schedule - that's much easier to work with. 👍 

I forked what you had and started converting it into a class:
https://github.com/mrpudn/offhours-parser

I'm guessing a lot of the custom schedules will be the same, so I added a cache feature into the parser to cache already parsed schedules. It probably won't add much of a performance boost, but it seems pretty non-invasive. Let me know what you guys think!

**Comment by fdosani** [comment]
@mrpudn Sorry for the delay. Looking good. the class structure makes sense. I think we should figure out a hard set of rules we'd want to enforce. There seems to be a lot of corner cases which we may want to handle or not. 

For example: Is `F-T` valid?
Can you have 2 of the same days for off?: `off=[(M,9),(M,18)]`

Some of these may not seem intuitive for myself but there could be legit reasons for other. Might make sense to hash some of these rules out?

**Comment by chiradeep** [comment]
You could also adopt a 'cron' style expression
'0 21 * * MON-FRI' would be 9pm MON-FRI.

**Comment by fdosani** [comment]
@mrpudn I might give this a shot on my local fork to see if I can get some integration with the offhours.py. Can always swap out the parser later.

**Comment by mrpudn** [comment]
We could probably get rid of timezones altogether by only supporting UTC time - thoughts?

@chiradeep - We discussed using a cron or cron-esque schedule, but there was some backlash. We could probably build it in later - I actually prefer it to the custom schedule.

`0 7 * * 1-5 on || 0 19 * * 1-5 off` (on Mon-Fri @ 7am; off Mon-Fri @ 7pm)

**Comment by fdosani** [comment]
@kapilt Any thoughts on the following corner cases for the parser. I'm wondering if we should try and catch some cases, and ignore others: https://github.com/fdosani/offhours-parser/blob/master/corner-cases.md

There might be some more which come to mind, but the following 3 jump out.

**Comment by kapilt** [comment]
1. skip
2. not sure i understand that
3. seems worth supporting

re cron -> py parser https://github.com/josiahcarlson/parse-crontab

**Comment by fdosani** [comment]
@kapilt @mrpudn hoping to get your input on what I have so far on my forked branch: https://github.com/fdosani/cloud-custodian/blob/offhours-feature/c7n/offhours.py

Just to summarize:
* I'm using @mrpudn parser which I've added to `offhours.py` at the end. I've made some minor tweaks to check for valid hours (0-23) and valid dates (m-s).
* main logic within `offhours.py` sits in `get_custom_time`

Couple of notes (please let me know if this makes sense or we should revert):
* If the custom schedule tag is malformed it will use the default values and continue on. 
* When it loops through the custom schedule it is a bit verbose and prints something as follows to the shell:
```
2016-05-26 18:49:21,227: custodian.filters:INFO InstanceOffHour 1 of 1 instances
2016-05-26 18:49:21,227: custodian.offhours:DEBUG resource: instance:i-04390fa105ad8911a specifies downtime with value: off=(m-f,18),(s,19);on=(m-f,15),(h,15);tz=et
2016-05-26 18:49:21,371: custodian.offhours:DEBUG resource: instance:i-04390fa105ad8911a checking custom hours, day=m hour=18, and tz=et
2016-05-26 18:49:21,371: custodian.offhours:DEBUG resource: instance:i-04390fa105ad8911a checking custom hours, day=t hour=18, and tz=et
2016-05-26 18:49:21,371: custodian.offhours:DEBUG resource: instance:i-04390fa105ad8911a checking custom hours, day=w hour=18, and tz=et
2016-05-26 18:49:21,371: custodian.offhours:DEBUG resource: instance:i-04390fa105ad8911a checking custom hours, day=h hour=18, and tz=et
2016-05-26 18:49:21,371: custodian.offhours:DEBUG resource: instance:i-04390fa105ad8911a matches custom hours with value now: 2016-05-26 18:00:00-04:00
```

I've been messing around with it on my own account and it seems to be working correctly. If there are any corner cases you think I missed please let me know. the circular dates one isn't implemented just yet, but I'll try to include once I get some feedback on this.

Also wondering if you had any better suggestions with regards to this part:
https://github.com/fdosani/cloud-custodian/blob/offhours-feature/c7n/offhours.py#L312
Since the instance of the class can be on or off I have a "check", but I'm thinking this might not be good form?
