### ISSUE TITLE
EC2 Image-Age filter isn't working

### ISSUE THREAD

**Issue by dommmmm** [capitalone/cloud-custodian#1302]
following the instructions here: 
http://www.capitalone.io/cloud-custodian/docs/_modules/c7n/resources/ec2.html#ImageAge

I get a report of all instances, regardless of the age of the image. In other words, the EC2 resource portion is working but the image-age filter isn't applying.  I've played with all the different operators available and none of them work. If I use the lt operator, I get a count of 0, even if the days are numbered to something really high like 3000. If I use the gt operator, I get a count of the number of instances in the account. 

When I try the same command but use the instance-age filter, it works perfectly. 
![image-age](https://user-images.githubusercontent.com/29580694/27351631-04fc09c2-55cc-11e7-897b-d5c673834a4c.png)

Any assistance on how to get this filter working? I am considering [this option instead,](http://www.capitalone.io/cloud-custodian/docs/usecases/amicomp.html) but it is a lot more tedious to manage.

**Comment by kumarsiyer** [comment]
@dommmmm try this policy? not sure if your indentation is correct in that policy
```
  - name: ami-age30
    resource: ec2
    filters:
      - type: image-age
        days: 30
        op: gt
```

**Comment by dommmmm** [comment]
@kumarsiyer 
Thank you for the response. I tried yours and got the same result.

**Comment by scotwk** [comment]
@dommmmm - I have a guess:

If the image age is no longer available, it defaults to this date:

```
        if i['ImageId'] not in self.image_map:
            # our image is no longer available                                                                                                                                                              
            return parse("2000-01-01T01:01:01.000Z")
```

That date is 6381 days ago.  So your image ages are probably no longer available, and it is setting them to this high value.  You can test this theory by changing your number to 6500 and seeing if `lt` shows your instances and `gt` does not.

**Comment by dommmmm** [comment]
that must be what the issue is. Thank you @scotwk

**Comment by dommmmm** [comment]
that must be what the issue is. Thank you @scotwk
