### ISSUE TITLE
filter for aws config compliance on non config rule policy

### ISSUE THREAD

**Issue by SrikanthSoma** [capitalone/cloud-custodian#1306]
Read the recorded config status on resources and take actions like notify and delete on non-compliant resources which are marked by aws config from a custodian non-config policy

**Comment by kapilt** [comment]
working on this, here's a filter schema, feedback welcome.

```
    schema = type_schema(
        'config-compliance',
        op={'enum': ['or', 'and']},
        states={'enum': [
            'COMPLIANT', 'NON_COMPLIANT', 'NOT_APPLICABLE', 'INSUFFICIENT_DATA']},
        rules={'type': 'array', 'items': {'type': 'string'}})
```

**Comment by kapilt** [comment]
There's also potentially an option to do value type filters on the evaluations from each rule to determine additional match specifics, ie. only show non compliant from last 30 days, etc.

**Comment by FireballDWF** [comment]
Sorry for delay in response, however schema looks like what I expected.  Thanks.
