### ISSUE TITLE
RDS Start/Stop - Flipped MultiAZ check, typo in except block

### ISSUE THREAD

**Issue by ajkerrigan-mdsol** [capitalone/cloud-custodian#1317]
The `is False` part of this MultiAZ condition (https://github.com/capitalone/cloud-custodian/blob/master/c7n/resources/rds.py#L576) should be deleted. The RDS start/stop eligibility check should return False if the instance _is_ MultiAZ.

There are also typos in the `except` blocks of Start and Stop where "DBInstanceIdentier" needs to be changed to "DBInstanceIdentifier":

https://github.com/capitalone/cloud-custodian/blob/master/c7n/resources/rds.py#L610
https://github.com/capitalone/cloud-custodian/blob/master/c7n/resources/rds.py#L635

I have these changes in place locally, will submit a PR when I can. In the meantime, I wanted to at least get the issue documented. These are small tweaks so if someone else wants to take it please go for it :).

**Comment by kapilt** [comment]
thanks for the review and filing an issue.
