### ISSUE TITLE
c7n_traildb support for multiple regions

### ISSUE THREAD

**Issue by kumarsiyer** [capitalone/cloud-custodian#1321]

**Comment by kapilt** [comment]
traildb processes per region on purpose, and then can be stored to an account/region specific prefix  in s3. the trailts indexer for traildb files will utilize that region when indexing into a time series store.

**Comment by kumarsiyer** [comment]
Hey @kapilt did we make any progress on this ?

**Comment by kapilt** [comment]
per previous comment, its already available effectively since we generate a separate traildb per region, and add it when doing trailts/indexing on the traildb files.
