### ISSUE TITLE
onhour policy not filtering out instances, in est time zone. 

### ISSUE THREAD

**Issue by srinivas-anant** [capitalone/cloud-custodian#1322]
```policies:
  - name: start-after-hours
    resource: ec2
    filters:
      - type: onhour
        tag: custodian_uptime
        default_tz: edt
        onhour: 14
    actions:
      - start
```
When I run this policy on a weekday it filters out the resource w.r.t to the tag and turns on the particular instance, but on weekends it does not filter the instance, and on last Friday it didn't filter out the resource. Why does it vary like this?

**Comment by kapilt** [comment]
the `weekends` flag controls this behavior, the default is to not start on the weekends, worth looking at the docs.
http://www.capitalone.io/cloud-custodian/docs/quickstart/offhours.html#resource-scheduling-offhours

**Comment by srinivas-anant** [comment]
Thank you.
