### ISSUE TITLE
off/on hours tag-based configuration incompatible with ElasticBeanstalk and EFS

### ISSUE THREAD

**Issue by jantman** [capitalone/cloud-custodian#1345]
I know that this is a pretty bad issue, given the amount of code that already exists for the tag-based configuration, but we're heavy users of ElasticBeanstalk. Unfortunately, per the [ElasticBeanstalk tagging documentation](http://docs.aws.amazon.com/elasticbeanstalk/latest/dg/using-features.tagging.html):

> Keys and values can contain any alphabetic character in any language, any numeric character, white space, invisible separator, and the following symbols: ``_ . : / + - @``

both parentheses and the equals sign are not allowed in EB environment tags; therefore any attempt at configuring on/offhours for EB instances with policy overrides fail, as the API calls to create/add any tag containing even ``=`` will fail.

I'm not sure I have a good suggestion for how to fix this...

**Comment by jantman** [comment]
Note there are also some EB tools, such as [ThoughtWorks' eb_deployer](https://github.com/ThoughtWorksStudios/eb_deployer) that have issues with empty tag values. Perhaps the simplest logical solution to this is to add support for an "on" tag value, and just tell EB users that they'll need to use tags for binary on/off, and have separate policies for any differing schedules.

**Comment by kapilt** [comment]
whats the implication of offhours for EB? ie. how would that work assuming the time filter was a non issue. (stop asg, disable elb health check, etc?).. not an eb user.

**Comment by jantman** [comment]
@kapilt For our purposes, the assumption is that it would be handled at the resource level... i.e. the EB app would be tagged with ``maid_offhours``, which would that tag on all resources in the application. The resources themselves would be handled under EC2/ASG/etc. policies... we'd just be aware that EB apps would go red offhours. I imagine that others might know a better way to do it, but we're heavy EB users and right now, for us, this is just about getting the tag to propagate out to the resources...

**Comment by kapilt** [comment]
so it sounds like two things needed, an option specifying a different `=` character for the off hours code, and then an action to propagate those values to underlying resources.  does that sounds about right?

**Comment by jantman** [comment]
I _believe_ the propagation to the underlying resources should be automatic. As far as I know, it's just a matter of making the tags work with the EB limitations on tagging.

The tags would need to be specified for the EB Environment at creation time (and as far as I know, there isn't any API call to edit tags on an existing environment), so propagation shouldn't be an issue.

The allowed characters are ``_ . : / + - @`` and tags can't be empty, so if I'm reading that right, we'd need to make a LOT of changes to the time spec... specifically ``=``, ``,``, ``;`` and both parenthesis and square brackets.

Given all of that, and how difficult it would be to come up with something sane from that small character set (especially given that it doesn't include any matched open/close pairs that could be used in place of the parentheses and brackets) I'm wondering if the right solution might be to just allow "on" as a tag value (to get around the empty tag limitation) and just assume/document that things in EB environments can't have their schedule overridden.

**Comment by kapilt** [comment]
that sounds reasonable. atm just having an empty string value in the tag is enough to participate in off hours for opt-in setups, so there is some basic working functionality already afaics. the most common minimal value set though is setting timezone .. i.e. tz=EST which would be good to continue to support. custom schedules are indeed going to be a bit difficult, and I agree its probably best to just leave off on them. although it does feel like we could specify a mapping ala

```
type: offhours
delimiter_map:
   "=" : "@"
   ","  : "."
   ";" : ":"
```

**Comment by jantman** [comment]
Unfortunately there isn't basic functionality... in addition to the symbol issues, EB will _not_ allow an empty tag value - hence my suggestion of adding a tag value of "on" or "enabled" to do the same thing that an empty tag currently does.

I like that idea about a delimiter map. But that's up to you Cap One folks. We don't have much variation in schedules, it usually ends up being one on/off hours schedule per development team, so we'd be fine with just allowing "on" in place of an empty string, and using a custom policy/tag name for any schedule variations.

**Comment by jantman** [comment]
It appears the same problem exists for [EFS volumes](http://docs.aws.amazon.com/efs/latest/ug/API_Tag.html), which becomes a problem if using CloudFormation or EB that's set to propagate tags to all resources.

**Comment by jantman** [comment]
I've documented my current workaround for this in #1421 - for our purposes at least, that will suffice to close the issue.
