### ISSUE TITLE
filter on tag KMSKeyAliases - EBS Snapshots

### ISSUE THREAD

**Issue by srinivas-anant** [capitalone/cloud-custodian#1356]
Is it possible to filter on EBS Snapshot KMSKeyAliases? I want to delete based only on specific name patterns (or regex matching).

**Comment by kapilt** [comment]
the key id is associated to the snapshot, you can filter as attribute filter directly on that. KmsKeyId: xyz

**Comment by srinivas-anant** [comment]
Thank you
