### ISSUE TITLE
Deploy Custodian Lambdas via CI/CD Pipeline

### ISSUE THREAD

**Issue by RogerPrince1** [capitalone/cloud-custodian#1374]
I want to automatically deploy and/or update custodian lambda functions as .yaml files are added to the GitHub repository. Basically, I want to manage the lambdas in an automated fashion via our deployment pipeline.  I understand that lambdas are typically created via the custodian CLI.  Is this the only option for creation of custodian policy lambda functions?

**Comment by RogerPrince1** [comment]
We could configure the EC2 where custodian is installed as a Puppet slave node.  Git signals Jenkins of a new commit, Jenkins pushes the policy .yml to the EC2 instance and runs the custodian CLI command to create/update the lambda.  Your thoughts?

**Comment by kapilt** [comment]
typically for ci/cd pipelines we would do jenkins/drone/etc as a ci system, on pull request or commit, checking out the repo, and doing a 

`custodian validate` on the config files and then a
`custodian run --dryrun` on them as an additional validation test

the ci system has those setup as status web hooks on the GitHub pull request.

the actual deploy happens post that, and is fairly dependent to how your deploying custodian, one option would be to just run the custodian from within the ci system post commit. though you'd need to distinguish lambda policies from other policies. some folks are deploying with containers, and might deploy a new image to their registry with the config. others are doing containers/instances that simply pull their config repos before executions for ci. custodian tries to be open ended wrt to usage and deployment model, which makes a generic answer here rather difficult outside of the validate/dryrun guideline above.

wrt to custodian lambda policy deployment, yes running custodian is the only deployment mechanism. the lambda packaging step embeds the specific policy within the lambda. we could probably build out a separate cli tool for just building the zip such that you could deploy it yourself using preferred lambda tech, but there's a lot of automation that you'd be duplicating (setting up event sources, etc).
