### ISSUE TITLE
Formatting issue with JSON Schema from CLI (e.g. u'properties' )

### ISSUE THREAD

**Issue by hakanson** [capitalone/cloud-custodian#1377]
When I compare the schema output by `custodian schema kms.filters.grant-count` against the online [KMS filters](http://www.capitalone.io/cloud-custodian/docs/policy/resources/kms.html#filters) documentation, there are formatting issues.  The most concerning is the CLI seems to output an invalid JSON Schema (likely due to the Python 2.7 formatting).  An example is `u'additionalProperties': False` which has a leading `u` and uses single (`'`) instead of double (`"`) quotes.

Some questions:
- Is this just an issue for me or my python install, or reproducible?
- Should this contain a link to the online documentation?

Schema from the online docs:
```
{
  "min": {
    "minimum": 0,
    "type": "integer"
  }
}
```

The CLI output:
```
$ custodian schema kms.filters.grant-count

Help
----

Filters KMS key grants

This can be used to ensure issues around grant limits are monitored

:example:

    .. code-block: yaml

        policies:
          - name: kms-grants
            resource: kms
            filters:
              - type: grant-count
                min: 100

Schema
------

{   u'additionalProperties': False,
    u'properties': {   'min': {   u'minimum': 0, u'type': u'integer'},
                       u'type': {   u'enum': [u'grant-count']}},
    u'required': [u'type'],
    u'type': u'object'}
```

**Comment by jmknoble** [comment]
The schema as output appears to be a Python dictionary rather than a JSON document.

**Comment by scotwk** [comment]
@hakanson - it's what @jmknoble said.  It's an easy fix.  Just curious, are you using the output of schema programmatically?

**Comment by hakanson** [comment]
@scotwk I am new to using cloud custodian and was just trying to understand the filters and actions.  I was working with `ec2` but just used `kms` in this issue because the output was shorter.  I noticed this when I pasted the JSON schema into VSCode and got errors.  If i wanted to use programmatically, I would want the schema JSON only (and not the other human readable output).

What do you think of linking to the online docs as part of CLI output?  Maybe a new section like?

```
Docs
----
Docs » Resource-Specific Filters and Actions » Key Management Service (KMS)
http://www.capitalone.io/cloud-custodian/docs/policy/resources/kms.html
```

**Comment by scotwk** [comment]
@hakanson - I think it's a good idea.  For tracking purposes can you submit it as a separate issue (this one can be closed when the bug fix gets merged) and then Kapil can comment?  Thanks

**Comment by scotwk** [comment]
@hakanson - thanks for reporting the JSON vs. dictionary problem.  The fix is merged to master and will be in the next release.
