### ISSUE TITLE
Update "Developer Install" link in README.rst

### ISSUE THREAD

**Issue by hakanson** [capitalone/cloud-custodian#1387]
The "Developer Install" link in the project readme goes to http://www.capitalone.io/cloud-custodian/docs/developer/installing.html

But when you run  `make develop` (on macOS) it errors out
```
$ make develop
make: *** No rule to make target `develop'.  Stop.
```

It looks like #1303 updated the developer docs, but maybe this hasn't be published to the documentation website yet.  Should that link just go to the `installing.rst` file in the repo?

https://github.com/capitalone/cloud-custodian/blob/master/docs/source/developer/installing.rst

**Comment by kapilt** [comment]
@alfredgamulo up for this one, there's a bug in the docs building since the switch out to tox
