### ISSUE TITLE
generic collection element not found retry remainder utility

### ISSUE THREAD

**Issue by kapilt** [capitalone/cloud-custodian#139]

**Comment by jeffastorey** [comment]
also should work for invalid instance states not just not found

**Comment by kapilt** [comment]
the exception string parsing and set of codes does appear to be fairly custom to each resource type/api call. for now we're just adding things on a case by case basis till a better pattern emerges.

**Comment by kapilt** [comment]
there's high variation here by resource type, but a context manager class abstraction would do nicely, with subclasses for different resource collections

**Comment by kapilt** [comment]
so need to handle anything in a ci pipeline, most common asg, ec2, and elb.

An error occurred (ValidationError) when calling the CreateOrUpdateTags operation: AutoScalingGroup not found - AutoScaling Group AsgId not found

**Comment by kapilt** [comment]
There's no way to handle this generically across all types of resources apis, its unclear if the commonality would provide significant value over the site implementations at the moment.
