### ISSUE TITLE
Cache Separate Update Functionality and Read Only Usage

### ISSUE THREAD

**Issue by lorenzoaiello** [capitalone/cloud-custodian#1397]
_this is a new feature request_

In order to run lots of policies against a resource, it would be great to be able to use more of the caching features that Custodian offers.

My idea is to have two features;
- The ability to specify an execution flag to run a policy to against a cache file using read-only (so that it will not attempt to write to the file)
- The ability to specify an execution flag that updates a local cache file from the AWS API for a specified list of resources

The goal being to built a local cache (and refreshing it periodically) of AWS resources and perform compliance policies and other actions against it locally.

Obviously, this presents some risk of performing actions using outdated information, but I believe the same problem exists today if using the cache.

**Comment by kapilt** [comment]
fwiw, you can effectively do this with cli params (to control cache file and cache period) and a few fill cache policies. custodian only writes to cache when the cache file is out of date with respect to the cache period or it sees a new resource policy.

**Comment by kapilt** [comment]
ie. cache usage is read only after population, and lifetime control is explicit.
