### ISSUE TITLE
Can you please provide any documentation to work with security groups and VPCs?

### ISSUE THREAD

**Issue by ss6851** [capitalone/cloud-custodian#1425]
I want to monitor the egress traffic from a VPC using security groups. Can you please provide detailed references?

**Comment by kapilt** [comment]
custodian doesn't directly provide capabilities for indexing and searching flow logs which is equivalent to the monitoring capability I think your referencing,  you could use custodian to determine the capability of various security groups within a vpc to send traffic, but actual monitoring of the traffic requires use of vpc flow logs to capture stats information of the traffic and then a separate db/index store to query that for alarms/visualizations.
