### ISSUE TITLE
Handle Auto Scaling Groups without Launch Configurations

### ISSUE THREAD

**Issue by ewbankkit** [capitalone/cloud-custodian#143]
The LaunchConfigurationName is not a required parameter when creating an Auto Scaling Groups so there may be ASGs without LaunchConfigurations. It seems that Custodian cannot handle this:
```
2016-05-25 14:29:13,342: custodian.output:ERROR Error while executing policy
Traceback (most recent call last):
  File "/src/c7n/policy.py", line 182, in poll
    resources = self.resource_manager.resources()
  File "/src/c7n/resources/asg.py", line 60, in resources
    return self.filter_resources(asgs)
  File "/src/c7n/manager.py", line 66, in filter_resources
    resources = f.process(resources, event)
  File "/src/c7n/resources/asg.py", line 118, in process
    self.initialize(asgs)
  File "/src/c7n/resources/asg.py", line 79, in initialize
    config_names.add(a['LaunchConfigurationName'])
KeyError: 'LaunchConfigurationName'
```

**Comment by ewbankkit** [comment]
The relevant policy is something like
```
  - name: asg-public-ip-compliance
    resource: asg
    filters:
      - type: launch-config
        key: "AssociatePublicIpAddress"
        value: true
    actions:
      - type: delete
        force: true
```

**Comment by ewbankkit** [comment]
Hmm, that is probably incorrect. You must specify either a LaunchConfigurationName or Instance ID when creating the ASG. Let me see what happens if I create an ASG with an Instance ID.

**Comment by ewbankkit** [comment]
In that case the LaunchConfigurationName is the name of the Auto Scaling Group.

**Comment by kapilt** [comment]
aha, thanks! also there's a case i've seen where the launch config gets deleted separate then the asg and leaves an orphan asg.

**Comment by kapilt** [comment]
i'm wondering if this is just a transient issue around asg teardown

**Comment by kapilt** [comment]
going a slightly different route on this by just auto filtering asgs without launch configs for any launch config based filter.
