### ISSUE TITLE
How to find buckets with no bucket policy

### ISSUE THREAD

**Issue by ascott58** [capitalone/cloud-custodian#1430]
Hi, I am still getting my head around how to write Cloud Custodian policies. Could someone please help me write the policy for filtering all S3 buckets which have no (or an empty) bucket policy? I don't need any actions run, as I can report the filtered buckets using the 'report' subcommand. All I need is to capture buckets with an inexistent policy.

I have a feeling I can use the 'missing-policy-statement' filter...

Also, is it possible to find S3 buckets with policies which provide access to the bucket from any source on the Internet? I.e. policies which give public-read/write to the bucket?

Thank you in advance!

**Comment by jtroberts83** [comment]
It's actually very easy.  If you are looking for buckets with NO policy on them just run this:

`policies:
- name: s3-bucket-missing-statement
  resource: s3
  filters:
   - type: missing-policy-statement
`

**Comment by kapilt** [comment]
```
policies:
   - name: s3-missing-policy
     resource: s3
     filters:
        - Policy: null
```

alternatively

**Comment by ascott58** [comment]
Thanks guys! Cloud Custodian is a pretty neat tool which we are currently using to automate compliance checking accross different resources such as instances and buckets, and so far it's been a big help. Thanks for the responses.
