### ISSUE TITLE
SNS Notification issues and unknown resource type error on c7n_mailer lambda with SQS 

### ISSUE THREAD

**Issue by sreeramsanjay** [capitalone/cloud-custodian#1431]
We are trying to send direct SNS topic from policy but it is not working for all the resources. We could able to write all the messages to SQS but when trying to generate notification using lambda function created by c7n_mailer we are getting "unknown resource type" error for few services.
('Unknown resource type', u'account') 
('Unknown resource type', u'iam-group')
('Unknown resource type', u'cloudtrail')  
('Unknown resource type', u'vpc')
('Unknown resource type', u'rds-snapshot')

Is there any simple way to send notifications for all types of resources.

**Comment by kapilt** [comment]
this has more to do with the formatting function in the mailer, then any intrinsic capability. the formatting function is just a helper function in the jinja templates, it can be extended with the additional types, or alternatively use a custom template that references the relevant attributes of those resources.

**Comment by sreeramsanjay** [comment]
Thanks Kapil,

Thanks for quick response, It seems working with default.html template but
message coming in raw html, is there a way to get email as standard html
instead of raw html message.

**Comment by kapilt** [comment]
if your template has .html in the extension it should be sent as html
