### ISSUE TITLE
Running From a Lambda Function

### ISSUE THREAD

**Issue by tiadobatima** [capitalone/cloud-custodian#1445]
Howdy...  Is it possible to run Custodian from Lambda as if we were running it in "poll mode" via the CLI? For example, from a cron triggered Lambda, or from an API gateway call? If yes, how would setup the Lambda?

In [this doc page](http://www.capitalone.io/cloud-custodian/docs/policy/lambda.html) it sounds like we can only run from Lambda when an CWE is triggered, but I think I'm misunderstanding something, as Cloud Custodian seems to be the perfect tool to be executed directly from a Lambda function.

Thanks! :)

**Comment by kapilt** [comment]
so an individual policy can be setup to execute itself as a periodic lambda, ie. run via the cli to provision a periodic policy that runs in lambda with poll mode. its the`mode: periodic`

http://www.capitalone.io/cloud-custodian/docs/policy/lambda.html#periodic-function

**Comment by tiadobatima** [comment]
Great! I missed that.
Say we have 50 policies... would this mean we'd need 50 lambda functions?

**Comment by kapilt** [comment]
yeah at the moment, that's true re 50 periodic policies ~ 50 lambdas, its a tradeoff at the moment. it does give clear operation metrics  at a policy via lambda generic metrics and cloudtrail visibility at a policy level and control of the periodicity per policy, the flip side is the cardinality count. the other aspect to multi policy is that we're not enforcing strict runtime constraints wrt to staying within the lambda 5m, so poll based policies in lambda have to be considerate of the resource set size, and some handful of actions are long running (cross region snapshot transfer, etc). that said, it would be useful to make that tradeoff something user choosable.
