### ISSUE TITLE
Add ClusterIdentifier field to Redshift notifications

### ISSUE THREAD

**Issue by jimmyraywv** [capitalone/cloud-custodian#146]
Notifications sent about Redshift clusters use the DBName which is not unique.  The ClusterIdentifier is unique and should be added to list of actionable nodes, perhaps replacing the DBName.

**Comment by kapilt** [comment]
This applies to the templates for the outbound mailer component of custodian which is not opensource yet due to its ties into ldap/email address lookup which need a little cleanup/genericizing for general utility.
