### ISSUE TITLE
s3 toggle-logging default target_prefix needs a '/' appended

### ISSUE THREAD

**Issue by seth-carroll** [capitalone/cloud-custodian#1464]
If you enable bucket logging with s3.actions.toggle-logging and do not specify a target_prefix, the prefix defaults to the bucket name without a trailing slash. For the sake of organization in the logging bucket, it would be nice if it appended a slash so that you would get a folder structure instead of a bunch of logging objects in the root of the logging bucket.

Ex:
s3://my-logging-bucket/my-source-bucket2017-08-07-17-22-28-D5813C87E6C5A11F

I believe this would be the fix, but wanted to get feedback:
```$git diff
diff --git a/c7n/resources/s3.py b/c7n/resources/s3.py
index d0c4eebe..b80cfe45 100644
--- a/c7n/resources/s3.py
+++ b/c7n/resources/s3.py
@@ -696,7 +696,7 @@ class ToggleLogging(BucketActionBase):

         for r in resources:
             client = bucket_client(local_session(self.manager.session_factory), r)
-            target_prefix = self.data.get('target_prefix', r['Name'])
+            target_prefix = self.data.get('target_prefix', r['Name'] + '/')
             if 'TargetBucket' in r['Logging']:
                 r['Logging'] = {'Status': 'Enabled'}
             else:
```

**Comment by kapilt** [comment]
merged and thanks for the pr
