### ISSUE TITLE
mark-for-op and tag actions missing for resource=kinesis

### ISSUE THREAD

**Issue by FireballDWF** [capitalone/cloud-custodian#1469]
The mark-for-op and tag actions are available for ec2, rds, and other resource types is not available for kinesis, but would desire them to be

**Comment by ocampocj** [comment]
I believe all tag related filters and actions will be much easier to add to resources once this PR is completed:
https://github.com/capitalone/cloud-custodian/pull/1315/files

Definitely agree that this needs to be done - thanks for adding it to the list!

**Comment by FireballDWF** [comment]
@ocampocj Your pull request will also address the issue of tag action missing from cache-cluster as well it appears, right?

**Comment by FireballDWF** [comment]
@ocampocj Your pull request also adds auto-tag-user to all resources, right?

**Comment by alfredgamulo** [comment]
@FireballDWF this PR will add tag filters and actions provided that `universal_taggable` gets added to a resource's resource_type class.

**Comment by kapilt** [comment]
merged re universal taggable

**Comment by kapilt** [comment]
kinesis tag support in #1477
