### ISSUE TITLE
multiple policies from single lambda function 

### ISSUE THREAD

**Issue by sreeramsanjay** [capitalone/cloud-custodian#1490]
Can we use single lambda to run multiple policies and can we move the logs(resource.json) to S3.

**Comment by ocampocj** [comment]
Do you have a particular use-case that would help clarify what your intent is?  Additional context might be helpful.  Thanks!

**Comment by sreeramsanjay** [comment]
Hi Chris,

We have defined a custodian with multiple policies around the resources
like ec2,iam,account,rds,vpc etc. We would like to deploy this custodian as
single lambda function then run against multiple aws accounts then save the
results to S3 bucket.

**Comment by ocampocj** [comment]
@sreeramsanjay - Depending on the number of policies that you end up running eventually and the size of your accounts, I imagine it's possible for a lambda like this to time out.  Maybe you can have a scheduled lambda spin up an EC2 instance, configure Custodian, run your policies and terminate?  That might be a good alternative.

**Comment by kapilt** [comment]
@sreeramsanjay also see my comments on #1445 namely there are tradeoffs.  wrt to s3 saving yes via `execution-options` on a lambda policy you can specify the output_dir to s3.
