### ISSUE TITLE
Feature request - tenancy

### ISSUE THREAD

**Issue by myoung34** [capitalone/cloud-custodian#1508]
Would be nice to look for resources with `dedicated|default|host` tenancy

* [ec2](http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/dedicated-instance.html)
* [rds](http://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/USER_VPC.WorkingWithRDSInstanceinaVPC.html) *this is done at the vpc level*
* [redshift](http://docs.aws.amazon.com/redshift/latest/mgmt/managing-clusters-vpc.html) *this is done at the vpc level*

**Comment by alfredgamulo** [comment]
I see your PR to add this to the query filter.
You should be able to accomplish this already with the value filter

```
filters:
  - type: value
    key: tenancy
    value: dedicated
```

**Comment by myoung34** [comment]
Oh, this wasnt clear via any of the docs. Ill try, if it works ill close the issue and PR
