### ISSUE TITLE
Validate action incorrectly reporting valid configuration when run against multiple config files

### ISSUE THREAD

**Issue by LykinsN** [capitalone/cloud-custodian#1516]
Custodian is currently failing to indicate a validation error when run against multiple policy files, if there is a failure in one or more of the offending items. However, if the validate action is run against a single problematic file then it is reporting the failure properly.

**Comment by scotwk** [comment]
@LykinsN - do you have an example of the failing policy files?  I made a few invalid policies but its catching the errors (even when I include valid files)

**Comment by kapilt** [comment]
@mandeepbal can you confirm this behavior?

**Comment by LykinsN** [comment]
I can't provide sample policies but I can describe the context for the issue. I've been able to reproduce it under version `0.8.24.5`. 

I can run this command: `custodian validate -c ./test1.yml -c ./test2.yml` with `test1.yml` being invalid and `test2.yml`being valid. 

I get this output: `custodian.commands:INFO Configuration valid: ./test2.yml`. 

However, if I execute `custodian validate -c ./test1.yml` then I can produce an error: `custodian.commands:ERROR Configuration invalid: ./test1.yml
custodian.commands:ERROR {'type': 'tag', 'key': 'test', 'value': 'test-value'} is not valid under any of the given schemas`

**Comment by LykinsN** [comment]
@kapilt Have there been any updates on this issue? I can confirm the problem is still happening as of `0.8.27.0`.

**Comment by LykinsN** [comment]
It looks like the proper solution for this is to use a space delineated concatenation of files, rather than specifying `-c` for each one. So `custodian validate -c ./test1.yml ./test2.yml` should work as expected. Closing out this issue.

**Comment by scotwk** [comment]
@LykinsN - Sorry, I didn't catch that you were specifying `-c` multiple times.  The `-c` parameter was deprecated awhile ago.  You can just pass the filenames as positional args, e.g.:

```
custodian validate ./test1.yml ./test2.yml
```
