### ISSUE TITLE
Provide support, or (better) documentation for adding custom policies

### ISSUE THREAD

**Issue by erickascic** [capitalone/cloud-custodian#1518]
Given I need to write custom policies to do my custom dirty work..... I would like to be able to deploy these extra policies without forking c7n.... want to just point to my extra module or directory or whatever.

**Comment by kapilt** [comment]
not sure i understand the question, custom policies are supported out of the box, you pass the path to the config files on the cli to run. if you mean custom filters/actions, we also support those out of tree via python entrypoints see doc string on https://github.com/capitalone/cloud-custodian/blob/master/c7n/registry.py#L20

could you give an example of what your trying to do?

**Comment by erickascic** [comment]
Yep yep yep, sorry - I'm using the wrong terminology for sure.  I'm interested in documentation or examples for writing custom externally defined filters as you guessed.

I'm definitely not a python guy....but I gave it a go and I *think* I've got something working but it diverges from this example a bit so it's probably flawed and not what is expected.  Is it possible to elaborate on this example a bit?

From my experience, it wasn't clear where the call to load_plugins is supposed to happen.  Within the core codebase, I could only find a call upon the PluginRegistry("resources"), so I configured my entry point as:

      entry_points="""
            [custodian.resources]
            missing_resources = new_filters:main
      """

**Comment by kapilt** [comment]
thats basically what there is to it re entry_points, we somewhat down play this as its primarily intended to support private betas of new services, or custom integrations, but doesn't play well with some of the other core feature sets (lambda execution, etc) without additional configuration.
