### ISSUE TITLE
Lambda support for S3 item encryption

### ISSUE THREAD

**Issue by tim-elliott** [capitalone/cloud-custodian#153]
Rather than use a scheduled job to encrypt all unencrypted items in S3 buckets, it would be useful (and more scalable) to encrypt items as soon as they are uploaded to a bucket.  The count of log files can grow very quickly, bogging down a scheduled run.

**Comment by kapilt** [comment]
we already have support for doing that, via the action attach-encrypt which attaches a lambda encrypt function to a bucket. for non log buckets recommend is to use an encryption-policy action. custodian has filters on s3 buckets for automatically determining buckets that are log targets (s3, elb, cloudtrail, cfn) that can be used in conjunction with the attach-encrypt action.

**Comment by tim-elliott** [comment]
Thanks.
