### ISSUE TITLE
Custodian version conflict with latest awscli

### ISSUE THREAD

**Issue by kumarsiyer** [capitalone/cloud-custodian#1531]
```
aws --version
aws-cli/1.11.144 Python/2.7.6 Linux/3.13.0-128-generic botocore/1.7.2
```

> custodian version
> Traceback (most recent call last):
>   File "/usr/local/bin/custodian", line 5, in <module>
>     from pkg_resources import load_entry_point
>   File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2749, in <module>
>     working_set = WorkingSet._build_master()
>   File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 446, in _build_master
>     return cls._build_from_requirements(__requires__)
>   File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 459, in _build_from_requirements
>     dists = ws.resolve(reqs, Environment())
>   File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 632, in resolve
>     raise VersionConflict(dist,req) # XXX put more info here
> pkg_resources.VersionConflict: (botocore 1.7.2 (/usr/local/lib/python2.7/dist-packages), Requirement.parse('botocore>=1.6.0,<1.7.0'))

**Comment by kapilt** [comment]
looks like a version conflict on our transitive dependencies to boto3 -> botocore with awscli

**Comment by kapilt** [comment]
great example of why using a virtualenv is a recommended practice in python world, alternatively docker.. custodian doesn't actually have a hard dep here, so i suggest you need to upgrade your version of boto3. ie a fresh install would be fine. try `pip install -U boto3`

**Comment by kumarsiyer** [comment]
I did a fresh install of pip install c7n where the CLI was already installed. Am I missing something ?
