### ISSUE TITLE
Can we have a remove-encrypt action for S3 resource

### ISSUE THREAD

**Issue by kumarsiyer** [capitalone/cloud-custodian#1548]
custodian schema s3
s3:
  actions: [attach-encrypt, auto-tag-user, delete, delete-global-grants, encrypt-keys,
    encryption-policy, invoke-lambda, mark-for-op, no-op, notify, put-metric, remove-statements,
    remove-website-hosting, set-inventory, tag, toggle-logging, toggle-versioning,
    unmark]
  filters: [and, cross-account, event, global-grants, has-statement, is-log-target,
    marked-for-op, metrics, missing-policy-statement, missing-statement, no-encryption-statement,
    not, or, value]

**Comment by kapilt** [comment]
i suspect what your actually asking for is the ability to remove/modify bucket notifications

**Comment by kumarsiyer** [comment]
Yes you are right. I was thinking the exact opposite of attach-encrypt 😉

**Comment by ocampocj** [comment]
@ewbankkit - possible to prioritize this work for this week?  Essentially, we need an additional action for 'remove-notifications'.

**Comment by ewbankkit** [comment]
My thoughts on approaching this are to have an additional `s3` resource filter type `bucket-notification` and additional action type `delete-bucket-notification` that would delete those bucket notifications matched by the filter.
This is similar to the `listener` filter and `modify-listener` action on ALBs.
