### ISSUE TITLE
Custodian ouptut does not output to stdout

### ISSUE THREAD

**Issue by thisisshi** [capitalone/cloud-custodian#1549]
Capturing the output of a Custodian command doesn't work with stdout:

```
+ custodian run -c some_policy.yml --dry-run -s ./output > output.txt
2017-09-08 13:55:14,686: custodian.policy:INFO policy: some-policy:rds region:us-west-2 count:2 time:0.1
+ cat output.txt

```

Right now, you can get the custodian run log by looking in the output in the `output/some-policy/custodian-run.log` but that requires going through each policy folder to read the log.

**Comment by kapilt** [comment]
logs go to stderr per best practices, stdout is for output.

**Comment by kapilt** [comment]
&> output.txt
