### ISSUE TITLE
c7n-s3-encrypt not handling spaces in key path

### ISSUE THREAD

**Issue by tim-elliott** [capitalone/cloud-custodian#1554]
If a space character is in an object key path it is being translated to a "+" when it is passed to the Lambda and it not being handled correctly.  For example, an object (template) named "2017235Abc-Create one dev rds instance.json" gets passed to the function as "2017235Abc-Create+one+dev+rds+instance.json", and the function throws an object not found error.

While I understand that a space character is not in the list of "safe" characters given by AWS for object names, it is in the "Characters That Might Require Special Handling" section of the [S3 documentation](http://docs.aws.amazon.com/AmazonS3/latest/dev/UsingMetadata.html#object-keys).

(NOTE: Issue updated to no longer mention colons, as those are correctly handled in the current version of the function.)

**Comment by alfredgamulo** [comment]
I'm surprised these are getting encoded as a + instead of %20

**Comment by ewbankkit** [comment]
@alfredgamulo If you use one of the lambda templates to create an S3 event handler for the bucket the generated code uses the `urllib.unquote_plus` method to convert the key name to a form suitable for passing back to boto.
As a test I created a simple lambda and uploaded a file with spaces in the name `File - Copy.pdf`:
```python
def lambda_handler(event, context):
    bucket = event['Records'][0]['s3']['bucket']['name']
    raw_key = event['Records'][0]['s3']['object']['key']
    raw_key_utf8 = raw_key.encode('utf8')
    key_unquote = urllib.unquote(raw_key_utf8)
    key_unquote_plus = urllib.unquote_plus(raw_key_utf8)
    print('********')
    print('Bucket: %s' % (bucket))
    print('Raw key: %s' % (raw_key))
    print('Raw key (UTF-8): %s' % (raw_key_utf8))
    print('Unquoted: %s' % (key_unquote))
    print('Unquoted plus: %s' % (key_unquote_plus))
    print('********')
    # s3.get_object(Bucket=bucket, Key=key)
```
```
********
Bucket: kit-test-bucket
Raw key: File+-+Copy.pdf
Raw key (UTF-8): File+-+Copy.pdf
Unquoted: File+-+Copy.pdf
Unquoted plus: File - Copy.pdf
********
```

**Comment by ewbankkit** [comment]
I'll modify `ufuncs/s3crypt.py` to use this functionality.
Thanks @tim-elliott for bringing this to our attention.
