### ISSUE TITLE
Feature Request - auto-tag-create-date  for EC2

### ISSUE THREAD

**Issue by jtroberts83** [capitalone/cloud-custodian#1582]
With protected tag ability it would be nice to be able to tag the current date and time of server creation to an instance at launch when triggering off of RunInstances API.  It would just need to grab the LaunchTime value from the RunInstances event and drop the value into a tag of sorts like c7n_creation_date.  That way there is an easy way to see the true launch date of a server as the regular LaunchDate of EC2 gets reset with every stop and start of the server.

**Comment by kapilt** [comment]
depends on what you mean by true launch date... the instance age filter uses the volume time of the root ebs vol. i'm a little unclear on the use case for this.
