### ISSUE TITLE
For tracking purpse - issue while running the c7n-org cli

### ISSUE THREAD

**Issue by kumarsiyer** [capitalone/cloud-custodian#1583]
> Traceback (most recent call last):
>   File "/usr/local/bin/c7n-org", line 9, in <module>
>     load_entry_point('c7n-org==0.0.2', 'console_scripts', 'c7n-org')()
>   File "/usr/local/lib/python2.7/dist-packages/click-6.7-py2.7.egg/click/core.py", line 722, in __call__
>     return self.main(*args, **kwargs)
>   File "/usr/local/lib/python2.7/dist-packages/click-6.7-py2.7.egg/click/core.py", line 697, in main
>     rv = self.invoke(ctx)
>   File "/usr/local/lib/python2.7/dist-packages/click-6.7-py2.7.egg/click/core.py", line 1066, in invoke
>     return _process_result(sub_ctx.command.invoke(sub_ctx))
>   File "/usr/local/lib/python2.7/dist-packages/click-6.7-py2.7.egg/click/core.py", line 895, in invoke
>     return ctx.invoke(self.callback, **ctx.params)
>   File "/usr/local/lib/python2.7/dist-packages/click-6.7-py2.7.egg/click/core.py", line 535, in invoke
>     return callback(*args, **kwargs)
>   File "/usr/local/lib/python2.7/dist-packages/c7n_org/cli.py", line 228, in report
>     fields=prefix_fields)
> TypeError: __init__() got an unexpected keyword argument 'fields'

**Comment by kapilt** [comment]
thanks for filing, i need to merge some output module changes from my `next` branch to resolve this. the c7n-org merge should have included those.

**Comment by kapilt** [comment]
fixed with #1622
