### ISSUE TITLE
Ability to enable bucket life cycle using custodian

### ISSUE THREAD

**Issue by kumarsiyer** [capitalone/cloud-custodian#1615]
> s3:
>   actions: [attach-encrypt, auto-tag-user, delete, delete-global-grants, encrypt-keys,
>     encryption-policy, invoke-lambda, mark-for-op, no-op, notify, put-metric, remove-statements,
>     remove-website-hosting, set-inventory, tag, toggle-logging, toggle-versioning,
>     unmark]
>   filters: [and, cross-account, event, global-grants, has-statement, is-log-target,
>     marked-for-op, metrics, missing-policy-statement, missing-statement, no-encryption-statement,
>     not, or, value]

Not available in current actions set

**Comment by kapilt** [comment]
see #1198 .. there's another pr for this as well in #1211

**Comment by scotwk** [comment]
@kumarsiyer - #1635 will hopefully be in soon.  Any comments?

**Comment by ewbankkit** [comment]
@kumarsiyer https://github.com/capitalone/cloud-custodian/pull/1635 has been merged. s3 `configure-lifecycle` action will be available.

**Comment by kumarsiyer** [comment]
Awesome thanks @ewbankkit 👍
