### ISSUE TITLE
Feature Request: ASG filter by image

### ISSUE THREAD

**Issue by hav3wb** [capitalone/cloud-custodian#1629]
EC2 has the filter `image` in addition to `image-age` while ASG only has `image-age`. To implement a Cloud Custodian policy involving custom AMIs with ASGs, I need this filter since you are checking the tag "AMIExpiration" in the custom AMI, not the AMI's actual age. Should be a quick implementation as would mirror EC2's `InstanceImage` class and ASG's `ImageAgeFilter` class already properly gets the AMI attached to ASG launch config.

**Comment by kapilt** [comment]
yeah, it could base of launch config as a base filter. currently launch config limits to image id check, having full image attributes as an asg filter sounds good.

**Comment by hav3wb** [comment]
First pull request #1646 has been uploaded for review. Tested locally using tox

**Comment by hav3wb** [comment]
Closed by PR #1646
