### ISSUE TITLE
Tags defined in action section of policy should be available as tags in notify action 

### ISSUE THREAD

**Issue by FireballDWF** [capitalone/cloud-custodian#1631]
For any tags added/changed during a Policies actions: should be available within the notify: action so when email template is being processed the values of the tags are available.

**Comment by kapilt** [comment]
the policy itself is available in the notify action for providing additional context, maintaining/patching the resource state through all possible action transforms isn't something we want to try to do at the moment.  there's a variety of tag implementations in play if we do change this.

**Comment by kapilt** [comment]
its one of the variables in the template per https://github.com/capitalone/cloud-custodian/tree/master/tools/c7n_mailer#writing-an-email-template
