### ISSUE TITLE
validation error not graceful when filter marked-for-op missing op: 

### ISSUE THREAD

**Issue by FireballDWF** [capitalone/cloud-custodian#1640]
The error "AttributeError: 'Policy' object has no attribute 'get'" should be changed to a more graceful error like "Filter type "marked-for-op" requires an "op:" attribute.

Example error:
```
$ custodian validate delete-rds-marked.yml
Traceback (most recent call last):
  File "/mnt/home2/opensrc/cloud-custodian/.tox/py27/bin/custodian", line 11, in <module>
    sys.exit(main())
  File "/mnt/home2/opensrc/cloud-custodian/.tox/py27/local/lib/python2.7/site-packages/c7n/cli.py", line 398, in main
    command(options)
  File "/mnt/home2/opensrc/cloud-custodian/.tox/py27/local/lib/python2.7/site-packages/c7n/commands.py", line 187, in validate
    p.get('name', 'unknown'), e)
AttributeError: 'Policy' object has no attribute 'get'
```

Example Policy:
```
  - name: delete-rds-marked
    resource: rds
    filters:
      - type: marked-for-op
```
Appending the following fixed the error:
```
        tag: custodian_status
        op: delete
```

**Comment by scotwk** [comment]
Thanks @FireballDWF .  It's actually not specific to `marked-for-op`.  It would dump a stack trace anytime `validate` produced an exception.  I've submitted a PR to fix it.

**Comment by kapilt** [comment]
@scotwk that's not related to the error here

**Comment by kapilt** [comment]
oh. it does, but you submitted two one line pull requests, and it was unclear i was reviewing the wrong one since they both touched the same code.
