### ISSUE TITLE
Add Tag actions to resources which support tagging api's

### ISSUE THREAD

**Issue by FireballDWF** [capitalone/cloud-custodian#1671]
The following resource types have aws Tagging apis but lack custodian action tagging support:
- [ ] storage-gateway
- [x] sqs
- [ ] waf
- [ ] waf-regional
- [x] Elasticsearch (aka es)
- [x] kms-key
- [ ] r53domain
- [x] datapipeline
- [x] Directory
- [x] log-group
- [ ] user-pool

**Comment by kapilt** [comment]
converted to action list, thanks, i hadn't realized some of those were now taggable (sns, sqs)

**Comment by JohnTheodore** [comment]
I have an interest in adding the tag action to elasticsearch. I think there is some new universal tagger thing I saw referenced in the code at some point. Is there a PR I can be pointed to for implementing a tag action to a resource?

**Comment by joshuaroot** [comment]
I do not believe SNS supports tagging at this time.

**Comment by FireballDWF** [comment]
You are correct, I've updated the list.

**Comment by tim-elliott** [comment]
I'm working on datapipeline.
