### ISSUE TITLE
Add tagging to SQS

### ISSUE THREAD

**Issue by salwandhruvdev** [capitalone/cloud-custodian#1679]
SQS Tags introduced on 10/19.

**Comment by salwandhruvdev** [comment]
@kapilt I am working on this.

**Comment by salwandhruvdev** [comment]
SQS is not supported in `ResourceGroupTaggingAPI`. We can `augment` tags the traditional way, where we add tag related `actions` and `filters` per resource type. For now, waiting a couple of days to get another update(support SQS tags in ResourceGroupTagging) from AWS on this.

**Comment by kapilt** [comment]
the resource tagging api has not been updated with any resources since announce, none of the new resources that support tagging use that api, the work for this is still the same as when it was claimed..
