### ISSUE TITLE
add --sse AES256 command line option to work with --output-dir s3://<bucketname>

### ISSUE THREAD

**Issue by FireballDWF** [capitalone/cloud-custodian#1694]
For accounts where all roles have iam policies requiring Server side encryption for all PutObjects, need the s3:PutObject api clients to include the
"x-amz-server-side encryption: AES256" header.

**Comment by kapilt** [comment]
we do this already by default for any custodian generated outputs.

**Comment by FireballDWF** [comment]
Sorry, figured out the bucket policy had not been correctly coded, once fixed, it worked.
