### ISSUE TITLE
Need modification to document

### ISSUE THREAD

**Issue by naveenlj** [capitalone/cloud-custodian#1695]
Need to set $ virtualenv --python=python2.7 custodian

pip install c7n
DEPRECATION: Python 2.6 is no longer supported by the Python core team, please upgrade your Python. A future version of pip will drop support for Python 2.6

**Comment by kapilt** [comment]
what platform does python 2.6 by default, that was released this decade?

**Comment by kapilt** [comment]
also this error is coming from pip, custodian also supports python3.6 so we don't want to mandate python versions for end users, outside of using something released in the last 5 years.
