### ISSUE TITLE
Default location fix for attach-encrypt action

### ISSUE THREAD

**Issue by jhnlsn** [capitalone/cloud-custodian#1720]
Error:
`An error occurred (InvalidArgument) when calling the PutBucketNotificationConfiguration operation: The notification destination service region is not valid for the bucket location constraint`

Sometimes a LocationConstraint can be null.

```
"Location": {
      "LocationConstraint": null
    },
```
This will cause the service region to be null for the put_bucket_notification_configuration operation, which is invalid.

Need to add a check that LocationConstraint is not None here as well.
https://github.com/capitalone/cloud-custodian/blob/master/c7n/resources/s3.py#L1026

**Comment by kapilt** [comment]
fix merged per #1721
