### ISSUE TITLE
Can we add get_bucket_inventory_configuration added to this list?

### ISSUE THREAD

**Issue by kumarsiyer** [capitalone/cloud-custodian#1722]
https://github.com/capitalone/cloud-custodian/blob/9aa8cc9c1e7bf69b2212e9973daaa07e47529345/c7n/resources/s3.py#L384-L396

**Comment by jhnlsn** [comment]
@kapilt do you think it might be better to allow this to be subsidized by the filter requirements instead of the list being hardcoded?  Something that would map the filter constraints the augmented get request.

**Comment by kapilt** [comment]
i'd rather have this as a supplementary filter not inline, we're roughly aligned here with aws config augmentation for s3 buckets. the inlining costs is a balance against common query and against resource retrieval time as its additional api calls, inventory isn't a typical one.

**Comment by kumarsiyer** [comment]
my goal was to pull the actions denied for c7n? so as per the above comment @kapilt there will be a separate filter to get-bucket-inventory ?

**Comment by jhnlsn** [comment]
@kumarsiyer there is already filter for s3 inventory

**Comment by kumarsiyer** [comment]
ah I see !
s3:
  filters: [and, cross-account, data-events, event, global-grants, has-statement,
    inventory, is-log-target, marked-for-op, metrics, missing-policy-statement, missing-statement,
    no-encryption-statement, not, or, value]

I missed that inventory filter :)
