### ISSUE TITLE
Add support for S3 default encryption

### ISSUE THREAD

**Issue by ewbankkit** [capitalone/cloud-custodian#1750]
AWS [recently](https://aws.amazon.com/about-aws/whats-new/2017/11/amazon-s3-adds-new-features-for-data-security-and-compliance/) [announced](http://docs.aws.amazon.com/AmazonS3/latest/dev/bucket-encryption.html) support for S3 default encryption.
Add support to Custodian for this feature.

**Comment by ewbankkit** [comment]
Not 100% sure this would look like yet as [botocore](https://github.com/boto/botocore) has not yet been updated.

**Comment by kapilt** [comment]
easy enough to make it work via json file distrib but hard to distribute if doing so

**Comment by jhnlsn** [comment]
Botocore released support in 1.7.41 today.

**Comment by thisisshi** [comment]
I can pick this up

**Comment by thisisshi** [comment]
Proposal for schema:

```    """Action enables default encryption on S3 buckets

    :example:

        .. code-block: yaml

            policies:
              - name: s3-enable-default-encryption
                resource: s3
                actions:
                  - type: configure-default-encryption
                    status: enable # or true?
                    encryption-type: kms
                    key: 1234abcd-12ab-34cd-56ef-1234567890ab

              - name: s3-disable-default-encryption
                resource: s3
                actions:
                  - type: configure-default-encryption
                    status: disable # or false
    """

```

new action: `configure-default-encryption` requires `status` and `encryption-type`. If `encyrption-type == kms` also require `key`.

Could also possibly use `key-name` for use with multi account runs that have keys that are named the same.

i.e. Account A has `key-id: 1234-5678` and `key-name: my-key`
Account B has `key-id: 2345-4567` and `key-name: my-key`

```
policies:
  - name: key-name-s3-default-encrypt
    status: enable
    encryption-type: kms
    key-name: my-key
```

c7n will do a `list_keys` lookup against kms and parse the arn

**Comment by jhnlsn** [comment]
Instead of a toggle action named `configure-default-encryption`, lets use an action named `set-bucket-encryption` to upsert and `delete-bucket-configuration` to delete encryption.  The rest of the setup looks good.  

The filter can include type and key as well.

**Comment by jhnlsn** [comment]
As for the `KMSMasterKeyID`, we can remove a lot of unnecessary logic if we just require the ARN and not allow for anything else.

**Comment by thisisshi** [comment]
requiring just an arn can be problematic for multi-account runs, getting a list of kms ids by alias is trivial with `list_aliases` while adding a lot of maintainability

**Comment by jtroberts83** [comment]
Agree with @thisisshi  that KMS arns are a pain when using across multiple accounts where the alias would work a lot better.  Having the enable/disable default S3 encryption action will be a great feature add to custodian!  Thanks for your work on it!
