### ISSUE TITLE
Resource dynamoDB-table wrong cloudtrail event source

### ISSUE THREAD

**Issue by cpollard0** [capitalone/cloud-custodian#1751]
Following policy: 
- name: ddb-auto-tag-user
  resource: dynamodb-table
  mode:
    type: cloudtrail
    role: arn:aws:iam::{account_id}:role/service-role/custodianrole
    events:
      - CreateTable
  filters:
    - tag:creator: absent
  actions:
    - type: auto-tag-user
      tag: creator

results in a cloudtrail event pattern that looks like: 
`
{
  "detail": {
    "eventName": [
      "CreateTable"
    ],
    "eventSource": [
      "dynamodb.amazonaws.com\""
    ]
  },
  "detail-type": [
    "AWS API Call via CloudTrail"
  ]
}
`
The extra quote in EventSource causes the Lambda not to fire.

**Comment by kapilt** [comment]
thanks for the bug report.

**Comment by cpollard0** [comment]
Fixed it in this PR: https://github.com/capitalone/cloud-custodian/pull/1879
