### ISSUE TITLE
rds retention errors

### ISSUE THREAD

**Issue by kapilt** [capitalone/cloud-custodian#178]
2016-06-07 19:26:05,278: custodian.policy:INFO policy: rds-retention-window resource:rds has count:27 time:6.50
2016-06-07 19:26:06,784: custodian.actions:ERROR Exception setting rds retention  
 An error occurred (InvalidDBInstanceState) when calling the ModifyDBInstance operation: DB Backups not supported on a read replica for engine postgres

**Comment by kapilt** [comment]
2016-06-07 19:42:16,678: custodian.actions:ERROR Exception setting rds retention  
 An error occurred (InvalidDBInstanceState) when calling the ModifyDBInstance operation: Database instance is not in available state.

**Comment by kapilt** [comment]
re ebs snapshots, this one can safely be ignored, but its polluting some of the logs, potentially move this to a warning and explicitly check error code
2016-06-07 19:37:03,291: custodian.actions:ERROR Exception creating snapshot set 
 An error occurred (IncorrectState) when calling the CreateSnapshot operation: The volume 'vol-771e4bd2' is 'retired'

**Comment by kapilt** [comment]
An error occurred (InvalidParameterCombination) when calling the ModifyDBInstance operation: The specified DB Instance is a member of a cluster and its backup retention should not be modified directly. Instead, modify the backup retention of the cluster using the ModifyDbCluster API

**Comment by ewbankkit** [comment]
I'll take this one as we may be seeing some of these errors in our accounts 😃 .

**Comment by ewbankkit** [comment]
I see yet another one:
```
2016-06-13 21:44:36,835: custodian.actions:ERROR Exception setting rds retention  
 An error occurred (InvalidDBInstanceState) when calling the ModifyDBInstance operation: DB Backups not supported on a read replica running a mysql version before 5.6.
```
