### ISSUE TITLE
Question: is it possible to see the code of a lambda function that is being deployed for a given policy?

### ISSUE THREAD

**Issue by fforloff** [capitalone/cloud-custodian#1791]
Hi Guys,

As per the subject. 
I can think of at least 2 cases why this can be good
- to stop guessing which actions I need to add to the Lambda policy
- to be able to deploy and lifecycle-manage resulting lambda(s) with my existing CI/CD tools.

Thanks and regards,

Victor.

**Comment by kapilt** [comment]
custodian is basically deploying itself as the lambda, along with the policy in question. you can use standard lambda api/cli to download the function code and examine `aws lambda get-function`. 

the policy execution is isomorphic to the execution mode, so a) is handled by just running the policy out of lambda and authoring it to taste (actions, filters, etc). b) lifecycle is handled by invoking custodian from existing ci/cd tools to validate the policy and deploy/update the lambda. 

could clarify the goal here re integration existing ci/cd tools?

**Comment by fforloff** [comment]
Thanks for the get-function tip, @kapilt!
Re integration with the existing ci/cd tools - say, we are using Jenkins/CloudFormation. Until custodian has an ability to delete Lambda's we could've used CloudFormation to provision/update/delete them.

**Comment by kapilt** [comment]
we distribute tools/ops/mugc.py for the purpose of deleting custodian policy lambdas no longer extant in config files if that helps.

**Comment by fforloff** [comment]
Thanks @kapilt , I'll give mugc a go.
