### ISSUE TITLE
Lambda CloudWatch log groups expiry.

### ISSUE THREAD

**Issue by fforloff** [capitalone/cloud-custodian#1792]
I've noticed that lambda cloud watch groups set data retention to "Never Expire". Is there any way to change to some other value? 
I guess, knowing naming convention, I could provision log groups before lambda deployment...

**Comment by kapilt** [comment]
its easy to write a custodian policy for this, ie find all log groups with a given prefix name, and set their retention period.

**Comment by fforloff** [comment]
Thanks @kapilt !
For those wondering here is how my policy for that looks like:

`policies:
- name: cloudwatch-set-log-group-retention
  resource: log-group
  filters:
    - type: value
      key: logGroupName
      op: regex
      value: ^\/aws\/lambda\/custodian\-.+$
  actions:
    - type: retention
      days: 14
`
