### ISSUE TITLE
c7n-mailer Fixed LDAP lookup in Assumed Roles #1350

### ISSUE THREAD

**Issue by JCarey23** [capitalone/cloud-custodian#1839]
Wondering what the status of this is.  I don't see it in master or latest.

jtroberts83 committed on Jun 29

commit 2e06be6c87ff6b41ed74894294e5e910bf79810c

contains needed code in email_delivery.py:
```
        if identity['type'] == 'AssumedRole':
            assume_role_msg = 'AssumedRole Found: %s' % identity['arn']
            self.logger.debug(assume_role_msg)
            user_id = identity['principalId'].split(':', 1)[-1]
            return user_id
```

**Comment by jhnlsn** [comment]
@JCarey23 it looks like the original PR was closed by @jtroberts83 and was not merged.

https://github.com/capitalone/cloud-custodian/pull/1350

**Comment by jhnlsn** [comment]
does not look like any further action is needed here.  Please feel free to reopen or raise an issue if you do not believe this is resolved.
