### ISSUE TITLE
c7n Unicode Decode Error

### ISSUE THREAD

**Issue by IDT-kcrook** [capitalone/cloud-custodian#1853]
This is the first pip install that has thrown this error for me. Looking into this issue shows that it may be the setup.py file reading a file without specifying the encoding as utf-8. I've tried to change it, but still I can't seem to get pip to install c7n

(custodian) PS C:\Users\myuser\Repository\cloud-custodian\custodian\Scripts> pip install c7n
Collecting c7n
  Using cached c7n-0.8.27.1.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\myuser\AppData\Local\Temp\pip-build-yq9yhtyi\c7n\setup.py", line 13, in <module>
        long_description=read('README.rst'),
      File "C:\Users\myuser\AppData\Local\Temp\pip-build-yq9yhtyi\c7n\setup.py", line 6, in read
        return open(os.path.join(os.path.dirname(__file__), fname)).read()
      File "c:\users\myuser\repository\cloud-custodian\custodian\lib\encodings\cp1252.py", line 23, in decode
        return codecs.charmap_decode(input,self.errors,decoding_table)[0]
    UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 2231: character maps to <undefined>

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in C:\Users\myuser\AppData\Local\Temp\pip-build-yq9yhtyi\c7n\

**Comment by kapilt** [comment]
yeah we noticed that at our sprint recently, its some odd characters in the readme, with particular system encodings, thanks for the filing the issue. @calvinhp you had a fix for this?

**Comment by calvinhp** [comment]
This fixes, but until this is released, the tox stuff is still broken due to the requirements files in the tools section are listing `c7n` as a dependancy and it will install the egg even if you use the `—develop` option

**Comment by ahmadzaikk** [comment]
@kapilt Hello,

I am getting the following error while using an encrypted SMTP password

error: 'utf-8' codec can't decode byte 0xa3 in position 1: invalid start byte

Thanks
Khalid
