### ISSUE TITLE
c7n-org account config regions should have precedence if no --region cli flag is specified.

### ISSUE THREAD

**Issue by kapilt** [capitalone/cloud-custodian#1860]

**Comment by jhnlsn** [comment]
@kapilt it looks like this is already being handled as defined below.  Is that not what your describing?

https://github.com/capitalone/cloud-custodian/blob/d7c44af8601239ab349fca3ef9aca41e7f25fb35/tools/c7n_org/c7n_org/cli.py#L397-L399

**Comment by joshuaroot** [comment]
No, because `region` is predefined in the click default (never None), it never gets the opportunity to check a['regions'].
