### ISSUE TITLE
Ability to reference resource attributes in tag values

### ISSUE THREAD

**Issue by aardvarq** [capitalone/cloud-custodian#1872]
Our use case is to tag all EBS volumes with the instance id and device name. Currently we use `Volumes.Attachments[0].InstanceId` and `Volumes.Attachments[0].Device` to create a tag value like `i-1234567890abcdef0:/dev/sdc`;  thus would also need the ability to construct a value from multiple attributes.

**Comment by jhnlsn** [comment]
What would the use case be for setting a tag to a value that is an attribute of the instance?  I could see the possibility of adding a jmes path expression as the tag value in the tag action.

**Comment by kapilt** [comment]
yeah. i was thinking of the tag value (with some discrimnator) as jmespath expr, the issue here is the example use case is actually a compound attribute of the instance, and the volume attachment, which would be readily feasible.

**Comment by aardvarq** [comment]
We've revisited our requirement for this capability and decided we won't require it. I think it's probably a useful capability, but I no longer have a use case. Thanks.

**Comment by jhnlsn** [comment]
Closing, as it looks like there are no further actions to be taken at this time.  We can reopen or create a new ticket if it looks like it would be useful in the future.
