### ISSUE TITLE
How to setup life-cycle policy for cleaning multi-part upload?

### ISSUE THREAD

**Issue by kumarsiyer** [capitalone/cloud-custodian#1877]
> policies:
> 
>           - name: s3-apply-lifecycle
>             resource: s3
>             filters:
>               - type: value
>                 key: Name
>                 value:
>                   - bucket-name
>                 op: in 
>             actions:
>               - type: configure-lifecycle
>                 rules:
>                   - ID: aborttest
>                     Status: Enabled
>                     Prefix: ""
>                     AbortIncompleteMultipartUpload:                  
>                       - DaysAfterInitiation: 10

the above policy is giving me a schema error

```
custodian.commands:ERROR [{'DaysAfterInitiation': 10}] is not of type u'object'

Failed validating u'type' in schema[20][u'properties'][u'rules'][u'items'][u'properties'][u'AbortIncompleteMultipartUpload']:
    {u'additionalProperties': False,
     u'items': {u'DaysAfterInitiation': {u'type': u'integer'}},
     u'type': u'object'}

On instance[u'rules'][0][u'AbortIncompleteMultipartUpload']:
    [{'DaysAfterInitiation': 10}]
```

**Comment by taohungyang** [comment]
@kumarsiyer 
This one is confirmed. I already have a fix for this.
Other than that there is still a problem about if the `Prefix` is required in your case. FYI

**Comment by jhnlsn** [comment]
@kumarsiyer `AbortIncompleteMultipartUpload` is an object and should be built like this:

```yaml
AbortIncompleteMultipartUpload:                  
  DaysAfterInitiation: 10
```

**Comment by kumarsiyer** [comment]
thank you @jhnlsn

**Comment by deshike22** [comment]
I am getting the below error when my bucket is configured with other lifecycle rules such transition to different tiers, etc.

2025-03-13 22:46:31,400: custodian.actions:ERROR error modifying bucket lifecycle: <bucketname>
Parameter validation failed:
Unknown parameter in LifecycleConfiguration.Rules[0]: "c7n:MatchedFilters", must be one of: Expiration, ID, Prefix, Filter, Status, Transitions, NoncurrentVersionTransitions, NoncurrentVersionExpiration, AbortIncompleteMultipartUpload
Unknown parameter in LifecycleConfiguration.Rules[1]: "c7n:MatchedFilters", must be one of: Expiration, ID, Prefix, Filter, Status, Transitions, NoncurrentVersionTransitions, NoncurrentVersionExpiration, AbortIncompleteMultipartUpload
2025-03-13 22:46:33,045: custodian.output:ERROR Error while executing policy

It works well when the bucket has no lifecycle rules.

`policies:
  - name: s3-lifecycle-incomplete-mpu-expiry
    resource: s3
    filters:
      - not:
          - type: list-item
            key: Lifecycle.Rules[]
            attrs:
              - Status: Enabled
              - Filter.Prefix: empty
              - AbortIncompleteMultipartUpload.DaysAfterInitiation: not-null
    actions:
      - type: configure-lifecycle
        rules:
          - ID: "AbortIncompleteMultipartUpload"
            Status: "Enabled"
            Filter:
              Prefix: ""
            AbortIncompleteMultipartUpload:
              DaysAfterInitiation: 7

`
