### ISSUE TITLE
Add CWER and ConfigRule cleanup to mugc.py

### ISSUE THREAD

**Issue by jtroberts83** [capitalone/cloud-custodian#1884]
Many users have requested a solution to cleanup cloud custodian items from their environment and mugc.py cleans lambdas but not the Cloudwatch Event Rules or Config Rules so adding that functionality would be great to have.

**Comment by ewbankkit** [comment]
* CWE rules should already be GCed - I added some logging to provide feedback
* Config rules GCed - https://github.com/capitalone/cloud-custodian/pull/1886
