### ISSUE TITLE
Add KMS support for c7n_mailer when not deploying via lambda

### ISSUE THREAD

**Issue by thisisshi** [capitalone/cloud-custodian#1892]
Currently c7n_mailer does a kms decrypt of the `ldap_bind_password` for lambda based executions but not when using `--run`

**Comment by kapilt** [comment]
should probably just do it in a try/except with a default of use what was given, so its automatic.

**Comment by thisisshi** [comment]
Alternatively should we use the ‘ldap_password_in_kms’ option that is already for the configuration file and move the logic to resolve the kms key out of handler.py?

**Comment by thisisshi** [comment]
@alfredgamulo do you want to pick this up?
