### ISSUE TITLE
Bucket policy cross account regression

### ISSUE THREAD

**Issue by jhnlsn** [capitalone/cloud-custodian#1894]
Two new assertions were added to iamaccess that are currently failing against bucket policies that did not previously fail and i'm trying to determine the path forward.

## First case:
https://github.com/capitalone/cloud-custodian/blob/125438cc11082c88a077e95a7ff74d8965917bb1/c7n/filters/iamaccess.py#L190

This affects a bucket policy condition that looks like the following:

```json
{"Condition": {
    "StringLike": {
        "aws:userid": "USERID",
        "aws:username": "USERNAME"
    }
}}
```

If a bucket has that condition, the code will assert and not process the bucket.  One issue with this is that someone could write a condition like this to avoid cross account checks on their bucket.  Maybe a policy like this should be removed if it's not supposed to be valid?

## Second case:
https://github.com/capitalone/cloud-custodian/blob/125438cc11082c88a077e95a7ff74d8965917bb1/c7n/filters/iamaccess.py#L183

**example condition**
```json
{
"Condition": {
    "StringNotEquals": {
        "s3:x-amz-server-side-encryption": "AES256",
        "something-else":"AES256"
    },
    "IpAddress": {
        "aws:SourceIp": "10.207.*.*"
    }
}
}
```

This also might not be a valid condition.  I was not able to find anywhere in the documentation that outlined this as being invalid.

**Comment by kapilt** [comment]
thanks for the bug report, offhand i think both of these are valid, i'll have a look at fixing this up.  i think i had those asserts in the refactor as afaics none of the iam docs reference multiple conditions, but searching around i do see that syntax in usage.

**Comment by jhnlsn** [comment]
Also it looks like the check for to many principals might have been removed, or it's just covered by a different case that i'm not immediately seeing.

this was in the previous version:
```assert len(s['Principal']) == 1, "Too many principals %s" % s```

**Comment by kapilt** [comment]
i'm not going to have a chance to work on this for a few days, removing myself in case anyone else wants to have a look before i free up.

**Comment by kapilt** [comment]
merged
