### ISSUE TITLE
Question: Execute lambda in multiple accounts

### ISSUE THREAD

**Issue by ferrangrau** [capitalone/cloud-custodian#1909]
Hello, 

I'm really new in cloud-custodian and I have a question, sorry if it is too easy or repeated. I have an AWS account A and I want to run a custodian policy to clean available EBS en aws accounts A, B, C... And I want to do this in a lambda. I crated the roles and the lambda works great working on A account to clean AWS account A, or working on AWS account A to clean AWS account B or C. But my problem is that I want to clean all the accounts in one execution, is there a way to do this? (I have about 50 AWS accounts and I don't want to create 150 lambda functions to do this...)

My policy is this:
`
policies:
  - name: ebs-mark-unattached-deletion
    resource: ebs
    mode:
      type: periodic
      schedule: "rate(1 day)"
      role: arn:aws:iam::AAAAAAAA:role/custodianAdministrationRole
      execution-options:
          assume_role: arn:aws:iam::BBBBBBBBB:role/CustodianCrossRole
          metrics_enabled: false
...
`
And works great on BBBBB account but I want to add more accounts...

Thanks!

**Comment by kumarsiyer** [comment]
Hey @ferrangrau you should look at [c7n-org](https://github.com/capitalone/cloud-custodian/tree/master/tools/c7n_org) This will help you achieve what you are looking for. Make sure your master role can assume roles in other accounts.

**Comment by ferrangrau** [comment]
Hi @kumarsiyer , thanks for your answer, yes I know c7n-org and it runs fine from an ec2 instance in my A aws account to clean A, B, C... accounts but doesn't works with set a lambda function that can do that. The c7n-org is compatible with lambda function? can setup a lambda that work with different roles?

Thanks for all!

**Comment by kapilt** [comment]
the out of the box answer here is typically the lambda per account, the failure modes and reporting with a multi account lambda get very deployment and policy specific wrt to error handling. could you clarify your concern with the separate lambdas per account? or with doing c7n-org fargate style?

**Comment by ferrangrau** [comment]
Hi @kapilt, The problem with the lambda per account is that now I have 79 accounts and growing (in another part of my company they have about 300), only for clean EBS I need 3 lambda for each account and I want to do more... so it means a lot of lambda's to control, a lot of crones... the c7n-org style works well but requires a instance running, it's not server less, and I prefer it because I'm the only one tech man in my department so I don't want to maintain servers. But if it's the only way we have it's fine for me the c7n-org, it's not hard to maintain... when I write the question I wasn't sure if there was another way to do this with 3 lambdas for all the accounts because I'm really starting with c7n.

**Comment by kapilt** [comment]
one option we could look at is having a lambda in the control account and making it parameterized on the role, such that each execution is still single account, but you'd still need to do something custom to manage the invoke, i think ecs fargate c7n-org is probably a better multi-account setup that qualifies as serverless ;-), in general c7n-org is where we're focusing custodian multi-account efforts.

**Comment by ferrangrau** [comment]
ok @kapilt I will try ECS Fargate then! thank you! when I work more on custodian I hope I can collaborate with the project!

Thank you!
