### ISSUE TITLE
Question: example on skip-days-from for off hours

### ISSUE THREAD

**Issue by mgarces** [capitalone/cloud-custodian#1910]
I am not fully understanding how to specify **_skip-days-from_**, for public holidays.
Which format of the CSV or JSON file on S3 should I have? I have read the the docs for **_value_from_** but I am still confused. 

My example list:
`2017-12-27,2018-01-01,2018-03-30,2018-04-01,2018-04-25,2018-05-01,2018-05-31,2018-06-10,2018-08-15,2018-10-05,2018-11-01,2018-12-01,2018-12-08,2018-12-25,2019-01-01,2019-04-19,2019-04-21,2019-04-25,2019-05-01,2019-06-20,2019-06-10,2019-08-15,2019-10-05,2019-11-01,2019-12-01,2019-12-08,2019-12-25`

Is it possible to give me an example on each type (JSON, CSV, csv2dict) so I can implement this feature? I am looking into reading these values from HR db, and generating that file. 
Thanks

**Comment by kapilt** [comment]
hopefully this helps re format, nutshell its configurable per format, via the expression usage. http://www.capitalone.io/cloud-custodian/docs/generated/c7n.html?highlight=values_from#c7n.resolver.ValuesFrom
