### ISSUE TITLE
network-addr aka EIP tagging support

### ISSUE THREAD

**Issue by FireballDWF** [capitalone/cloud-custodian#1912]
Support tag actions for network-addr resource now that AWS supports it per
https://aws.amazon.com/about-aws/whats-new/2017/12/amazon-virtual-private-cloud-vpc-now-allows-customers-to-tag-their-elastic-ip-addresses/

**Comment by kapilt** [comment]
hmm, this might already work, or be a one liner, we do ec2 tags generically across the service.

**Comment by rbowlby** [comment]
Addition of the `copy-instance-tags` action to the EIP resource would be awesome.

**Comment by rbowlby** [comment]
Addition of a `release` action would prove useful as well. 👍
