### ISSUE TITLE
Add support for rest-api-stage resource

### ISSUE THREAD

**Issue by FireballDWF** [capitalone/cloud-custodian#1913]
Add support for a "stage" subresource of rest-api, aka API Gateway.  Stages now support tagging, which is useful for cost allocation purposes

Example of how to retrieve:
http://boto3.readthedocs.io/en/latest/reference/services/apigateway.html#APIGateway.Client.get_stages

**Comment by kapilt** [comment]
we'll be looking at this within the next week.

**Comment by kapilt** [comment]
merged, no tag support yet.
