### ISSUE TITLE
Notify with sns/sqs transport type sending message base64 encoded

### ISSUE THREAD

**Issue by jfi247** [capitalone/cloud-custodian#1916]
Policy looks like this:

`policies:
  - name: account-service-limits
    resource: account
    filters:
      - type: service-limit
        threshold: 80
    actions:
      - type: notify
        to: 
          - 
        transport:
          type: sns
          topic: arn:aws:sns:us-east-1:123456789012:custodian_limit_test`

sqs/sns (email subscription) message body comes in like this:

`eJzNWGtvqswW/t5fQfppv8nmBBBR+s0LIl5RRKsnJ2SEQZDLIAOo7Jz/foZLu9vuvuklp82bGIQ1izXPsy7DzPp1cwtME6VhYrjW7R11K3JMoyW2GgzPirc/b25hBsOEDISp7/98VC40LegngLZRGhd6McTkzoSYDP375tdbZh9GQxDAP42ZrfBOg3HmmnDiBm6CpYsJoQWtB+OmA02veG+t9nDxBq60a1FpA/koLp7lGMKw1ElAkhb4bpFXQT64KCyeU0xDgBOaLcQRJDTCBBwKaxzzL4bI/AJFodksfXJJQOUD9vbmvz+fAVLCBMYhTKgDSOAZXP9Z6LR0T7BhilihcHlPHWKURi9ALvva/w8k+wIkxzxHyRGUN/95Lepk9NeTzNLSIADx9YVUjRG54jI3OJZ/morKIURxOcA8FQ98cDj8KdbSKIofLDGF5yq/KWUCw01rOGT81kh8zQ8mCfYBxVctgqZru+YzqCbCyTxKCKXcDQ+VDGLyTF6ypihMHP+qgYyMFRYrbz2Oq5UrX1MjbitAEkWiDYKoci7bphmWZvgVK97xrTuO3RUA7Yrz8mWVus9p28DH8IlTKu6tLQCaPlAakaJpZt47GePV5NLZjNK1KANrPm+FIi83fcnWi7kCmAALJKCc43lidNIEaSbwCz/Uj1T9XCViWS4cU6ZIealSr8yP9yRfnfDvojVe9KFxpFW2u3AWaquhHwXnmJ/R0tjaPVscK4xh20G3g07nj9GagDQ0HcpEoe0e0hgkBOZ3Etu7ziBS0QazHj2DsTj0xB0Pm6es3+b9NVylXSQ0hck6d703iEndciHomImbQQqHIMIOSkouLMNUbMQvZjNjBbfZGO+H3TDhZEcWe5MpMz+PeUEezPricdcWaXO46KaS+SE2GfJTUjmFpMl8T2CmYnxiBaA1PZ1NV/Rs63pG7KAu3lliV9iuVNznWyo6zTbvpEIWv8zFBBO0KGWuatQPTev/Re
EExWTxpX7IbvevKlgc/z0U5ynyljlsuLqAUj+bRPfrsCEE2mwzlKaeYK8XB7mbnnzafGfuTcGBfKZcs47Xn9w4hm9/CzUe9PtTQW2LodnkAlkcYtjFg3Tg0IOzICLlNJqNQWcv6xr/uejVS8Q3JePpGKAczlpnfqQYwip39Jmu8KNRPBfW+sZmtgp7GTOGy4bvjJQMQxgDn1LTOEIY1rn4d2H7vpTsACTM0cboNlfz01IZjJqZOJk2XZ3ZcRZtL3a5xI2gPUiu7beI9rjyzycSkpGKSgHLKmfH1A9JUXHJrPkdpMxxa0LeTOUBmrZCLx+1s3wM9K3AQvPcmDWcE6dvs53ZXL/18apJka0B2XsVmRgSrCHZI1A0FZEJHUBiWe7eqB9BtQ2p645c62PBFxKV/NVi6iEzbGj7TInO23RyaCvdqXIWe+NsvadFlcUGWq7nnTeI1lvvhyNDGSb2i8PE9VV15wykw8zrdKLZdTkVfCMXh8dVx7asGSm/aYCPE1HoMO9D/+r54nuodHryToOOKXKLMJnMrSWXK+PtucWzkq1B2OMDLW7v2JYxfXcgqDdKia1WCP6LqfU8N7fy6zIKhyfB7AJel/LoYNrGodVTsvsYDXdOR0rbQFXeoFafnLQnZ6t6h/EdIYoEp7u9ekcbz4Nrp7ed+FYyOnej+Lw7LbTIFfr7jb2OAtn7EI/Xz4vVOY77YkrHdmLomdGd5+mhgRxB8OXL0RqN+n3xvqduRfGkZT7rZryK3qCkSSWlPnD9K4VhaBWHjlOKiPJXbs2fI6LLGu5Mq1KuFloqipHt+vBxW13+v53zT900hHmmb8mJOp2jzMfrxk44Jl0zmjWP9+x9e9KxNwfv3BrkA+nTeJfoBUau+SGM92ygscEoOV+kvRrqGufLR3gNJX60aXL9XGisjHS5aJ/WDvNpjPJjxTWYd5bcU4hAuMj5Xt8L49PAwJ7ckqcS7cTMxh2MzIA9LI0Gwis
rRqfppyHq5Dv77NTR/hDErUFr+WDlNbSZZ/XbF7BqDLOjM3dYLI3twOdFzjh3vGtf+rwXiy4MqXgTxknRzSBfGvy74t8ukWdfjU1nfLzOdXHortn9KHCvSjjYseO+vXHRtLnF+tpZNm10unzeoyryXdOtc7NZOfVjqWmz4n5n91zdkC4KG6nB9MyK9HQj0TQKXHcm6+fJQLhX5q1O2a0qWi+l2b9pgAEzqcSEToIqxInjYor8AghCsvSQWsIVtCQGIY5QnNT616hswuGqZ5CgyDXL3IzDO3DGd0R+9zjZ3dPG6p2Zkm225YLQKPdrBolbcls1iWqjISIRvVayqHDbi3ZaOVHd4yUqZFlKimytu0WP0KouHV319ArzDjHgIL9wJsvUvnno7db26Gdv4d9u+m3+H+mpKtr/A02o5G8=`

Maybe the above is not base64 encoded??? Anyways the notifications cannot be deciphered.

**Comment by kapilt** [comment]
notifications actions send data messages (base64 / gzip'd json), there's a separate software component for sending doing delivery with templates via ses or smtp, w/ ldap lookups,, etc. see   https://github.com/capitalone/cloud-custodian/tree/master/tools/c7n_mailer

**Comment by jhnlsn** [comment]
To read the message off the sqs queue, you need to base64 decode and then decompress.  For example in python:

```python
zlib.decompress(base64.b64decode(msg))
```
