### ISSUE TITLE
Syntax Error

### ISSUE THREAD

**Issue by SrikanthSoma** [capitalone/cloud-custodian#1941]
Syntax error in module 'custodian_policy': invalid syntax (ipaddress.py, line 474)

**Comment by jhnlsn** [comment]
Hello @SrikanthSoma, thank you for the bug report.  Would you please provide some more details to help identify the issue.  What version of python are you running?

**Comment by SrikanthSoma** [comment]
Python 2.7 @jhnlsn

**Comment by kapilt** [comment]
hmm, thats odd, whats the full traceback look like?

fwiw, i'm not seeing issues with either 2.7 or 3.6
```
(custodian) scythe:custodian kapilt$ python2.7 c7n/ipaddress.py
(custodian) scythe:custodian kapilt$ python3.6 c7n/ipaddress.py
```

which python version are you using?

**Comment by SrikanthSoma** [comment]
@kapilt You mean lambda python runtime version right? which is python 2.7 In my local I'm using 3.7  I don't think it's not related which python version I'm using on my local as long as lambda python run time is 2.7 right?

**Comment by kapilt** [comment]
thats helpful to know, thanks, so 3.6.3 local cli run deploying 2.7 lambda.

**Comment by jhnlsn** [comment]
@SrikanthSoma would you mind exporting the lambda function and pasting the code at line 474 from ipaddress.py?

**Comment by SrikanthSoma** [comment]
@jhnlsn  
471 - @classmethod
472   def _report_invalid_netmask(cls, netmask_str):
473           msg = '%r is not a valid netmask' % netmask_str
474           raise NetmaskValueError(msg) from None

**Comment by jhnlsn** [comment]
Ahh ok.  in december we added ipaddress.py to the probject so that we could be compatible with py 2 and 3.  It looks like you are pushing python3 version of ipaddress to the 2.7 lambda, which is not compatible.

please try installing the latest version of custodian as it will pick up the ipaddress.py in the project instead.

**Comment by SrikanthSoma** [comment]
@jhnlsn How can Install the latest version?

**Comment by jhnlsn** [comment]
I'm not exactly sure how you have installed your current version, but you can always install using pip or from source.

`pip install c7n` or see the [quick install](https://github.com/capitalone/cloud-custodian#quick-install) from the readme

**Comment by SrikanthSoma** [comment]
@jhnlsn  I did that pip install c7n in virtualenv it says requiremt already satisfied

**Comment by jhnlsn** [comment]
`pip install c7n --upgrade` should do the trick.

you can also run `pip list` in your virtualenv to see what version you are running.

**Comment by SrikanthSoma** [comment]
@jhnlsn It worked and creating tags for resources I think it only creates tags for instances which are just created right? not for already running instances right?

**Comment by kapilt** [comment]
you can run on cli to evaluate whole fleet, or periodic in lambda.
