### ISSUE TITLE
request-limit-increase action (account resource) fails to create AWS support tickets for some service resources

### ISSUE THREAD

**Issue by leehaines** [capitalone/cloud-custodian#1950]
This is our policy that we use to monitor service limits.
policies:
  - name: account-service-limits
    resource: account
    filters:
      - type: service-limit
        threshold: 60
    actions:
      - type: request-limit-increase
        percent-increase: 20

We get a parameter validation error when the request-limit-increase action is invoked to raise support tickets for certain AWS resources (specifically IAM and CloudFormation).

`Invalid type for parameter serviceCode, value: None, type: <type 'NoneType'>, valid types: <type 'basestring'>`

This happens because the service code mappings in `master/c7n/resources/account.py` does not include mappings for all of the service codes generated by the service limit filter.

https://github.com/capitalone/cloud-custodian/blob/master/c7n/resources/account.py#L515

    service_code_mapping = {
        'AutoScaling': 'auto-scaling',
        'ELB': 'elastic-load-balancing',
        'EBS': 'amazon-elastic-block-store',
        'EC2': 'amazon-elastic-compute-cloud-linux',
        'RDS': 'amazon-relational-database-service-aurora',
        'VPC': 'amazon-virtual-private-cloud',
    }

**Comment by kapilt** [comment]
thanks, we should probably be generating the code mapping dynamically rather than having a static listing here.

**Comment by leehaines** [comment]
I did some research on this. There is an aws support describe-services call to fetch a mapping from service names to services code.

However the service names in that mapping do not match up to the service names that are retrieved from the trusted advisor metadata. Therefore, this can't be used to dynamically fetch the service codes. This is probably why a static mapping is defined.

I'm going to submit a pull request to update this static map with the extra values (IAM and CloudFormation) that are currently breaking our cloud custodian deployment.

**Comment by jhnlsn** [comment]
@leehaines it looks like this issue is resolved via your merged PR.  If it is not please feel free to reopen.
