### ISSUE TITLE
sagemaker jobs should default to not querying completed.

### ISSUE THREAD

**Issue by kapilt** [capitalone/cloud-custodian#1951]
same sort of issue as emr, long expanding list, rarely of interest, compared to whats running, stalled, starting, etc.. 

see review comments in #1949

**Comment by joshuaroot** [comment]
@kapilt unlike emr, however, the `list_training_jobs` field `StatusEquals` only takes a `string` value, not a `list` like the emr `ClusterStates`

**Comment by joshuaroot** [comment]
also, it appears the pagination for all of the sagemaker resources is not handled at all in the current version of botocore in the custodian requirements (1.8.29) and needs to use 1.8.35. boto3 package version is not an issue
