### ISSUE TITLE
API Gateway (rest-account) needs variable interpolation for CloudWatchRoleArn Account ID to support multiple accounts

### ISSUE THREAD

**Issue by jtroberts83** [capitalone/cloud-custodian#1969]
Please add {account_id} variable interpolation for the cloudwatch role arn so this can run against multiple accounts.  Right now it can't be used by us until this is fixed.  Here is our policy:

```
- name: apigw-set-cw-logging-role
  resource: rest-account
  filters:
     - 'cloudwatchRoleArn': absent
     - or:
       - not:
         - type: value
           key: 'cloudwatchRoleArn'
           op: regex
           value: \w*CloudWatch_Custodian_Role\b
  actions:
     - type: update
       patch:
         [ {op: 'replace',
           path: '/cloudwatchRoleArn',
           value: "arn:aws:iam::{account_id}:role/CloudWatch_Custodian_Role"}]
```

**Comment by kapilt** [comment]
this would need to be done generically on all patch operation values, there's possibility of overlapping with builtin configuration formatting on resources though (velocity template mappings syntax), so its probably best to limit to this the rest-account, and rest-stage update actions.

**Comment by jtroberts83** [comment]
ok thanks fine with me.  We just need it for account update

**Comment by kapilt** [comment]
so we now support variable interpolation on account_id generically across policies in any filter/action, etc.
