### ISSUE TITLE
Invalid dead letter queue ARN when provisioning Lambda policies

### ISSUE THREAD

**Issue by ajkerrigan-mdsol** [capitalone/cloud-custodian#1990]
Provisioning a Lambda policy works in 0.8.27.3, but the same policy fails with the latest code:

```InvalidParameterValueException: An error occurred (InvalidParameterValueException) when calling the CreateFunction operation: Invalid dead letter queue ARN: ARNs must start with 'arn:':```

It looks like the issue stems from the change in [this commit](https://github.com/capitalone/cloud-custodian/commit/7a96ee15cc8888be91e5c86e0d05df3fd830ce1e#diff-3b6d052df3306ec5a910d7c6055b0e57). Changing the empty `DeadLetterConfig` from `{'TargetArn': ''}` to `{}` gets things working again. I'll open a PR for that change (including the necessary test changes), and will happily tweak the PR if there's a better way to handle it.

**Comment by kapilt** [comment]
merged
