### ISSUE TITLE
Feature Request - Tagging CloudFormation stack

### ISSUE THREAD

**Issue by cpollard0** [capitalone/cloud-custodian#1994]
Does it make sense to add the ability to tag CloudFormation stacks? If we can add a creator auto-tag to a cfn stack then it should take care of tagging the underlying resources.

**Comment by kapilt** [comment]
sure re tag actions on cfn,  however its a bit of race on auto-tag wrt to stack resources.

**Comment by jhnlsn** [comment]
Tag propagation from a CFT is dependent on the resource type.  As long as the resource supports tagging, I believe the CFT will propagate the tags.  Docs outlined here: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-resource-tags.html

We currently don't have the `create_stack` or `update_stack` functionality implemented in custodian, which would be the precursor to CFN tagging.  Maybe @kapilt can weigh in as to why we chose not to add that.  My guess is that supporting the creation of resource via a CFT is out of custodian's wheel house.  Considering resources can be created/deleted with their individual custodian resource actions.

**Comment by kapilt** [comment]
the notion was that its better to tag the underlying resources directly, doing auto tag on a stack is racy wrt to where the stack is in its creation process and whether the stack tags will propagate to resources all created.
