### ISSUE TITLE
c7n_salactus incorrectly handling keys with null version ID in versioned buckets

### ISSUE THREAD

**Issue by ewbankkit** [capitalone/cloud-custodian#2003]
* If an S3 buckets is not versioned, each object in the bucket has a version of `null`
* When versioning is enabled on a bucket the version ID of existing objects stay the same - `null`
* Suppose a new version of an existing object is written - the new version will have a non-null version ID and be the latest version and the previous version will have a null version ID
* See docs [here](https://docs.aws.amazon.com/AmazonS3/latest/dev/ObjectVersioning.html)

Such an object will get entries in an S3 Inventory report like
```
"my-bucket","data.txt","","false","false","998","2017-07-17T20:20:55.000Z","NOT-SSE"
"my-bucket","data.txt","FWlIvVG7ZLwpLjwDgQyY0ZPLszk2zkvd","true","false","999","2018-01-03T20:47:17.000Z","SSE-S3"
```
so the version ID is read as an empty string.

When encrypting the old (`null` version ID) object this code
https://github.com/capitalone/cloud-custodian/blob/630b5a3f323f7013491cf25cdd04731b1b848d70/c7n/resources/s3.py#L1821-L1825
gets an HTTP 400 error as `VersionId=""` is an invalid value. The correct value is the string `"null"`, i.e. `VersionId="null"`.

**Comment by ewbankkit** [comment]
This won't be happening for the other caller of `EncryptExtantKeys.process_version`
https://github.com/capitalone/cloud-custodian/blob/630b5a3f323f7013491cf25cdd04731b1b848d70/c7n/ufuncs/s3crypt.py#L49-L57
as in this case the latest version of an object is encrypted and it will always have a non-null version ID in a versioned bucket.

**Comment by kapilt** [comment]
the lambda will always be processing new versions as written. i think the subtle distinction here is the null version id gets json deserialized as None in python, but the api wants the literal string 'null' for operations.
