### ISSUE TITLE
Add Encryption action and filter for DynamoDB

### ISSUE THREAD

**Issue by jtroberts83** [capitalone/cloud-custodian#2009]
Now that Encryption at REST is supported for DynamoDB (SDKs will soon)  I wanted to put in a request to get the filter and actions added to cloud custodian once python supports it.  https://aws.amazon.com/about-aws/whats-new/2018/02/amazon-dynamodb-now-supports-server-side-encryption-at-rest/

**Comment by LykinsN** [comment]
I'm looking into adding this functionality but it looks like encryption is supported during table creation only right now. A new field has been added to the `describe_tables` response, to indicate whether encryption is enabled, and can be filtered on with a value filter only.

https://docs.aws.amazon.com/amazondynamodb/latest/APIReference/API_SSEDescription.html

As more capabilities are built into this, I'll look into expanding it further.

**Comment by kapilt** [comment]
there is no such thing as an encryption action for dynamodb, tables must be encrypted at creation, and the filter is already supported using the value filter.

**Comment by mason67git** [comment]
what is the exact filter for dynamo db encryption. I have tried 

```
filters:
   - Encryption: false
```

Which works for other resources but not DynamoDB
