### ISSUE TITLE
Lambda-Specific Resource Actions Enhancement

### ISSUE THREAD

**Issue by IDT-kcrook** [capitalone/cloud-custodian#2019]
We use Cloud Custodian to report on non-compliant Lambda functions, and having an action that suspends them like other resource types would be useful.

(I realize it's not really due to cost, it's more about maintenance and being able to contact someone when their code goes sideways.)

A really effective way of disabling lambdas is setting their concurrency to 0. Below is the script we've been using - it just takes as input a file name that has lambda function names deliminated by a newline char.

```
> import boto3
> 
> __filepath__ = 'lambda.txt'
> 
> def suspend_lambda(client, function_name):
>     response = client.put_function_concurrency(
>         FunctionName=function_name,
>         ReservedConcurrentExecutions=0
>     )
>     return response
> 
> def main():
>     
>     client = boto3.client('lambda', region_name = 'us-west-2')
>     
>     with open(__filepath__) as fp:
>         line = fp.readline()
>         while line:
>           try:
>             line = fp.readline().strip()
>             print(line)
>             response = suspend_lambda(client, line)
>           except Exception as e:
>             print(e)
>             pass
>     return
> 
> if __name__ == '__main__':
>     main()
```
If this is already a feature that I'm not aware of, please let me know 👍

EDIT: the code looks a little funny because github isn't commenting out the code right...

**Comment by kapilt** [comment]
one caveat we'll need to add a separate filter (at the cost of an api call per lambda) to retrieve extant reserved concurrency allocation. i took a stab at the action earlier today, for setting concurrency to a static value, deleting concurrency, and setting concurrency to a cw metric queried value.
