### ISSUE TITLE
Unable to import module 'exporter': No module named exporter

### ISSUE THREAD

**Issue by NSmeef** [capitalone/cloud-custodian#2041]
I've deployed `c7n_logexporter` utilising the cloudformation and running the following commands -
`make install && make deploy`.

Looking at the logs coming from the lambda in cloudwatch it prints the following error - 

`Unable to import module 'exporter': No module named exporter`

**Comment by kapilt** [comment]
hmm.. is it possible you deployed from a system with a restrictive umask?
