### ISSUE TITLE
Add CloudWatch to the limit-increase namespace to allow for CWER increases

### ISSUE THREAD

**Issue by jtroberts83** [capitalone/cloud-custodian#2049]
@kapilt 
Due to having lots of lambda custodian policies I have hit the limit of CloudWatch Event Rules in every one of our 75+ accounts and all 15 regions with my new tag enforcement policy set and need an automated way to detect these limits and request increases to avoid failed policy deploys.

**Comment by kapilt** [comment]
there isn't any mechanism to detect the account limit / usage on for cloud watch event rules afaics
