### ISSUE TITLE
It seems that the command will not be excuted repeatedly in seconds while running the same command?

### ISSUE THREAD

**Issue by youzhoutai** [capitalone/cloud-custodian#2070]
e.g. To count the number of instances which specific tags absent. at the beginning, the result is correct, after modifying tags in some instances, the excution result still the same, while it should be different. And i found that the execution time was "0.00" from the log in the terminal(Xshell). So each command will not be excuted repeatedly at the backend in short time?

2018-03-02 06:23:04,466: custodian.policy:INFO policy: ec2-tag-compliance resource:xxx region:xxx count:8 time:0.00
2018-03-02 06:23:05,834: custodian.policy:INFO policy: ec2-tag-compliance resource:xxx region:xxx
count:8 time:0.00

**Comment by thisisshi** [comment]
Custodian caches resources to avoid rate limiting and degrading the api. You can set the cache period to 0 to disable that with `—cache-period 0`

**Comment by youzhoutai** [comment]
thanks for ur kindly reply, then whats the default value for this cache?

**Comment by thisisshi** [comment]
Defaults to 15 minutes: https://github.com/capitalone/cloud-custodian/blob/master/c7n/cli.py#L108-L110
