### ISSUE TITLE
How to use tool c7n-org, credentials required?

### ISSUE THREAD

**Issue by youzhoutai** [capitalone/cloud-custodian#2074]
when trying c7n-org tool for multi aws accounts according to https://github.com/capitalone/cloud-custodian/tree/master/tools/c7n_org, "Unable to locate credentials" shown in terminal after excuting the command"c7n-org run -c custodian-all-cnf.yml -s output -u ec2tagging.yml --dryrun"

2018-03-05 03:38:06,354: c7n_org:ERROR Exception running policy:ec2-tag-running account:account-012345678901 region:xxxxx error:Unable to locate credentials
2018-03-05 03:38:06,357: c7n_org:ERROR Exception running policy:ec2-tag-running account:account-012345678902 region:xxxxx error:Unable to locate credentials
2018-03-05 03:38:06,358: c7n_org:ERROR Exception running policy:ec2-tag-running account:account-012345678903 region:xxxxx error:Unable to locate credentials

**Comment by ferrangrau** [comment]
Hi @youzhoutai I think the problem is the place you rune the c7n-org. When you run it it tries to assume the role of the account you want to perform the action, I run it from an EC2 instance with a role that can assume roles form other accounts and works fine but If I run the o7n-org from my computer I have the same error. 

Can you provide more information about where are you running the c7n-org command to can help you better?

**Comment by youzhoutai** [comment]
thank you so much for ur kind reply, it is the same what u said. Then it seems that i need one aws master account to eslablish trust by using assume role, when i want to do multi accounts implementation with c7n-org? like this, Account A for master, account B, C, D ... to be implemented c7n?

**Comment by ferrangrau** [comment]
I don't know if there is another option but yes, is the way I use. I have a governance account that we only use for this kind of stuff (the account are free so it's not problem having n accounts) and the other accounts has a role that give right to the governance account to do the c7n-org stuff. If you want I can give you samples of the CloudFormation of the roles.

**Comment by youzhoutai** [comment]
thanks, by the way, did u use this c7n-org tool to implement lambda function for multi aws accounts?

**Comment by youzhoutai** [comment]
@ferrangrau, i just found that u raised one similar question before. After u executed the policy in ur issue(https://github.com/capitalone/cloud-custodian/issues/1909), lambda created only in B or both A and B? And whats exact meaning for "role: arn:aws:iam::AAAAAAAA:role/custodianAdministrationRole" and "assume_role: arn:aws:iam::BBBBBBBBB:role/CustodianCrossRole"? As my opinion, regarding assume_role, u can only have access to do something under permission of CustodianCrossRole, but when u want to create lambdain B, one B's lambda role also required. 

when i was trying, showing that "when calling the CreateFunction operation: EnvironmentVariablesFeature is not supported in my region"


my policy:

policies:
  - name: my-first-policy-cross-account
    mode:
        type: periodic
        schedule: "rate(1 day)"
        role: arn:aws-cn:iam::AAA:role/lambdaforlab
        execution-options:
          assume_role: arn:aws-cn:iam::BBB:role/CustodianEC2Tagging
          metrics_enabled: false
    resource: ec2
    filters:
      - "tag:Custodian": present
    actions:
      - stop

**Comment by youzhoutai** [comment]
@kapilt , may i ask if it means that EnvironmentVariables Feature not support in my region as error showing above? And custodian for lambda support uses EnvironmentVariables in deploying lambda?

**Comment by thisisshi** [comment]
@youzhoutai That sounds like a limitation on AWS's side; environment vars don't seem to be supported in the CN regions

**Comment by youzhoutai** [comment]
@thisisshi got it. thank you.
