### ISSUE TITLE
How do you generate / find jmespath information for filtering?

### ISSUE THREAD

**Issue by marvinestreet** [capitalone/cloud-custodian#2081]
I noticed that custom filtering is capable as is done here: https://github.com/capitalone/cloud-custodian/issues/2056

But what I want to know is how can I find the jmespath for various AWS resources I may want to filter on. For instance, I know that running `get-bucket-lifecycle-configuration` will net me Rules[].Transitions.Days, but where does the "Lifecycle" parent come from? How do I map the various aws cli calls to usable jmespaths for Cloud Custodian? 

Thanks and I apologize if this is already called out clearly in the docs somewhere that I missed.

**Comment by thisisshi** [comment]
The Lifecycle key comes from an augment on the S3 resource: https://github.com/capitalone/cloud-custodian/blob/master/c7n/resources/s3.py#L389-L401

This is a s3 specific implementation, it makes the corresponding api calls (`get_bucket_lifecycle_configuration`, `get_bucket_versioning `, etc.) and maps it back to a key (`Lifecycle`, `Versioning`, etc.) in the resource. You can run a policy like so:

```yaml
policies:
  - name: s3-resources
    resource: s3
```

and then inspect the resulting `resources.json` and generate a jmespath for whatever key/value you want to query on.

Other resources typically just return the result of a `describe` call as the resource and may make different AWS API calls in the filter itself on the specific resource.

**Comment by marvinestreet** [comment]
Perfect. That's exactly what I needed. Thanks.
