### ISSUE TITLE
S3 - is-log-target

### ISSUE THREAD

**Issue by timbo256** [capitalone/cloud-custodian#2095]
What does the 'is-log-target' use to identify S3 buckets that are used for logging? 

Just trying to verify that the policy is working correctly in terms of the results it returns.

**Comment by kapilt** [comment]
its primarily elb, cloudtrail, and s3 at the moment. It looks like we should extend this for a few other s3 logged resources

- [ ] alb
- [ ] redshift debug logging
- [ ] ?

**Comment by timbo256** [comment]
Thanks Kapil - I was really asking which fields are used from these items - e.g. is it LogFileValidationEnabled in Cloudtrail?

**Comment by kapilt** [comment]
is-log-target is primarily concerned with the existence of log source, not its optional parameters. If thats of interest, i'd suggest constructing a policy directly against the source (trail also has a filter on the account fwiw).
