### ISSUE TITLE
add glue-connection resource

### ISSUE THREAD

**Issue by FireballDWF** [capitalone/cloud-custodian#2096]
Use cases:
1. filters:
1.1. security-group filter (like EC2's) where SG's have right tags
1.1. subnets are public 
1.1. connections don't specify SSL 
2. actions
2.1. delete
2.2 notify

http://boto3.readthedocs.io/en/latest/reference/services/glue.html#Glue.Client.get_connections

**Comment by kapilt** [comment]
could you clarify the use case a bit, haven't used glue yet, its a bit unclear on the connection as resource, its basically describing vpc connectivity to an underlying rds/redshift system, wouldn't it make more sense to check on the underlying resource vs checking a connection to the same?

**Comment by FireballDWF** [comment]
Think of glue connections as a combination of a JDBC connection string and ENI for a Lambda (or container task).  Just like Lambda's can have Security Groups, so can Glue Connection objects.  Glue connections are describing the client side of a connection to a datasource.

**Comment by kapilt** [comment]
thanks for clarification

**Comment by FireballDWF** [comment]
Another policy use case: Delete action if subnets are public.
