### ISSUE TITLE
NFR: network-addr resource could really use a delete action

### ISSUE THREAD

**Issue by swl09** [capitalone/cloud-custodian#2103]
I'd like to be able to delete network-addr's that are not associated via policy. It looks like network-addr does not have a delete action at the moment, a feature that would facilitate that. Can that be added?

**Comment by alfredgamulo** [comment]
@jonathana

**Comment by jonathana** [comment]
@kapilt and others: what would the expected behavior be for a network address that's currently attached to a resource?  Should delete only work on unattached network addresses?

**Comment by kapilt** [comment]
yeah. delete for network-ip should only be active non attached by default, perhaps a `force` parameter to do attached.
