### ISSUE TITLE
Is it possible to pass a command line argument to cloudcustodian command, to replace a value in YML file ?

### ISSUE THREAD

**Issue by josenrihernand** [capitalone/cloud-custodian#2105]
Hi all, is there a way to pass a parameter (command-line argument) to the cloudcustodian command ?

I am executing the command as here:
custodian run --region ${AWS_REGION} --metrics -s src/cloud-custodian/reports src/cloud-custodian/custodian-generated.yml

What I want to do, is to pass a command-line argument to replace the account_id (01234567890), in the yml file, so it can be changed dynamically. Is it possible ?

----------- yml file --------------
    resource: ec2
    mode:
      type: periodic
      role: arn:aws:iam::**01234567890**:role/my-role-cloudcustodian
      schedule: "rate(3 days)"
-----------------------------------

thanks a lot !

**Comment by thisisshi** [comment]
It seems like you're trying to execute a single policy against multiple accounts. Have you considered using [c7n-org](https://github.com/capitalone/cloud-custodian/tree/master/tools/c7n_org)? c7n-org will run a set of policies against a set of accounts and use the role specified in the config file to assume into that account and execute as that user/role.

**Comment by josenrihernand** [comment]
@thisisshi thanks for the info about c7n-org. I will try it. 
Should I have any other question, I'll open a new issue.
