### ISSUE TITLE
datadog & slack integration

### ISSUE THREAD

**Issue by ferrangrau** [capitalone/cloud-custodian#2109]
Hi, 

I've done a little python script that reads the output of cloud custodian and send the information to datadog (to generate alerts and other stuff) do you think it's interesting to add to cloud custodian? If you want (with time)  can do a PR. In our case we send the data we have wen we clean EBS volumes.

I will do something similar with slack, do you think it's good to add to cloud custodian too?

Thanks

**Comment by kapilt** [comment]
slack and pagerduty / ops* integrations would be useful, generally folks have been doing them adhoc via `invoke-action` stuff. re output to datadog, afaics isn't that covered by the -m flag to send cloudwatch metrics, where datadog can slurp up along with its other cw metric ingestion?

**Comment by kapilt** [comment]
perhaps the right way to do this is to enhance tools/mailer directly. also of interest pagerduty.

**Comment by ferrangrau** [comment]
Sorry for the delay...

Yes, I think this fits really well in the c7s_mailer because what I do is notify to datadog/slack (or pageduty, finally it's the same) the result of the policy and I like the way to do it with the action. 

So you find it's useful? I cant start a PR with a proposal, if you are agree.

**Comment by kapilt** [comment]
thats sounds useful, and a pr/proposal would be great, thanks.

**Comment by LykinsN** [comment]
I'm planning to add notification support for Slack to Custodian. Implementation details are TBD.

**Comment by LykinsN** [comment]
@ferrangrau If you'd like to collaborate on this effort, please reach out to me on Gitter, and we can discuss.

**Comment by bcatubig** [comment]
A datadog event per policy execution run would be really useful as DD can plug into other ops monitoring tools to alert teams if a resource/thing is in a bad state. 

I would be interested in helping with this @LykinsN .

**Comment by kapilt** [comment]
@bcatubig its not a datadog event, but we do output cloudwatch metrics per execution that data dog can already display.

**Comment by ferrangrau** [comment]
Hi!, I start the datadog integration in my fork:
https://github.com/ferrangrau/cloud-custodian/settings/collaboration

If someone more wants to collaborate or discus if it's the correct way tell me and I will add as a collaborator.

**Comment by salwandhruvdev** [comment]
Reviewing goals for slack integrations:
- Message resource-owner on DM for policy validation
- Stream of room messages for policy executions
- Templates for Slack messages

**Comment by ferrangrau** [comment]
@salwandhruvdev, what do you mean exactly with "Message resource-owner on DM for policy validation", sorry, my english it's not as good as I need. I'm agree with the goals, another I have, and probavly is you first one is I use c7n-org and I need to send notifications in different channels depening on the aws account the resource/actions happens.

Another concern is that slack have 2 ways to interact, with a python module and a token or with a simply request were each channel/person have a unique url, what do you think? Use only the token or both ways.

In all the cases normally I prefer do short PR, so to do all the goals probably we need to do more than one PR.

**Comment by salwandhruvdev** [comment]
To answer your first question: Direct Message(DM) `resource-owner` on Slack for Custodian policy violation. 

@LykinsN and I have started work on putting together a **standalone** tool which you can track [here](https://github.com/salwandhruvdev/cloud-custodian/tree/incoming-slack-integration). Please feel free to contribute. We are using the first approach(slackclient lib and token) to interact with Slack. 

I definitely agree on short and more than one PR for all the goals. @kapilt Please suggest if I have missed something.

**Comment by ferrangrau** [comment]
@salwandhruvdev yes! If you are agree I want to collaborate.
