### ISSUE TITLE
Why is SNS compressed?

### ISSUE THREAD

**Issue by marvinestreet** [capitalone/cloud-custodian#2117]
Maybe, I'm doing something wrong, but it looks here (https://github.com/capitalone/cloud-custodian/issues/1131) like it's compressed. Is there any way to configure this to send through SNS in a way that's easily human readable directly from the message?

Right now, this is what I get and it's not very useful: https://d.pr/i/wdzTkl

**Comment by kapilt** [comment]
if you want to send human messages via sns use tools/c7n_mailer.. the sns message is compressed because its a data message and sns message have a size limit. its a one liner to decompress and get raw json zlib.decompress(base64.b64decode(sns['Message']))
