### ISSUE TITLE
Invalid filter type - flow log configuration check

### ISSUE THREAD

**Issue by youzhoutai** [capitalone/cloud-custodian#2130]
i followed the example shown in the doc. But when validating the policy, error showing below:

aws.account.actions Invalid filter type {'status': 'active', 'traffic-type': 'all', 'log-group': 'myVPCFlowLogs', 'type': 'flow-logs', 'enabled': True, 'set-op': 'or', 'op': 'equal'}

policies:
  - name: account-flow-log-check
    resource: account
    filters:
      - not:
           - type: flow-logs
             enabled: true
             set-op: or
             op: equal
             traffic-type: all
             log-group: myVPCFlowLogs
             status: active

**Comment by kapilt** [comment]
flow log filters are on a vpc not an account afaicr
