### ISSUE TITLE
No way to explicitly tag resource with creation time

### ISSUE THREAD

**Issue by hvidal-ebsco** [capitalone/cloud-custodian#2138]
While there are resources that have a time created as part of their object schema (e.g. EC2 Instances have LaunchTime), there is no way to use that as a value for a tag.

In the scenario where a separate system is polling an account for resources based on a datetime tag, this would be handy.

As an actual implementation, there could be a new action, similar to auto-tag-user. The time of the CloudTrail event (e.g. eventTime for RunInstances) could be used as the generalized value for time of resource creation.

This gives us a UTC timestamp for free and allows resources to be tagged with their creation time very close to when they were created.

**Comment by hvidal-ebsco** [comment]
Here is an implementation of the feature
https://github.com/capitalone/cloud-custodian/pull/2136

**Comment by kapilt** [comment]
I'm a little unclear what the use cases for this are, many resources that are taggable do have some form of creation date builtin, and that can be used when filtering them in policies, ie this information is often redundant in a tag. Could you elaborate what you mean by separate system polling by date time? are the resources immutable, ie how does it catch modified resources, honestly it sounds like that external system should be using a different api, like say aws config. Is it just ec2 that your interested in this for?

ec2 launch time is really start time, we typically use the age of the root volume as instance time.

**Comment by hvidal-ebsco** [comment]
Filtering within custodian policies using the built in creation date works very nicely, but for many external third party tools filtering of resources is based on tags. Custodian's policy format for autotagging user is very simple, and it seemed reasonable to mimic it for tagging event times when in CloudTrail mode.

**Comment by kapilt** [comment]
most of the aws resource apis don't support tag value filtering (ec2 is an exception in that), so its unclear what these third party tools are doing per se with the tag values since it has very limited application, and given its duplicate data in many cases for the data already in the resource. as a result doing this as an action across all taggable resources seems questionable since it can't fulfill the stated use case. as i said if those tools want a date based poll interval api they should be using an aws api that supports that more naturally across a wider resource set, like config. are these public third party tools or some inhouse thing?

**Comment by chris-march** [comment]
We are working with a 3rd part cost management tool where the primary data source is the AWS generated CSV billing file. The only way to pass additional information to the product is via tags.
When there are unexpected costs the first question is what changed. Have the creation date in the cost management system would allow us to find all the resources that were created on a given day or month.

**Comment by chris-march** [comment]
Thanks for getting back to me. We will look at #2127. Will this be merged into master any time soon?

A creation date tag would allow us to search for resources in our cost management system with a filter of:

CreationDateTag contains "2018-02"

It's a simple text search but it meets our needs.

**Comment by kapilt** [comment]
#2127 is merged

**Comment by kapilt** [comment]
hopefully that resolves i think its a better generic capability that addresses this and other use cases, if there's question about it feel free to ask or reopen this issue.

**Comment by hvidal-ebsco** [comment]
https://github.com/capitalone/cloud-custodian/pull/2127 looks like it can be used to apply the current time as a tag. Would it be possible to allow for values other than current time, region, and account_id such as values included in a CloudTrail event? Being able to access event time might be more informative about a detected event than the (current) time at which the event was detected by custodian.

**Comment by whyname** [comment]
I need event time, too
