### ISSUE TITLE
whats the logic to delete unattached volumes as scheduled - use case :EBS - Garbage Collect Unattached Volumes

### ISSUE THREAD

**Issue by youzhoutai** [capitalone/cloud-custodian#2141]
i deployed the policy as showing in the docs(use case :EBS - Garbage Collect Unattached Volumes), and i created one unattached volume for test, found that there is one new tagging on the volume as expected(to be deleted tomorrow). but i found that there is no lambda or config rule created there, even no crontab job in the ec2 where the command excuted, so how to make sure that the volume will be deleted tomorrow?

**Comment by kapilt** [comment]
run the tool again, ie. how you setup the cron job on your instance is up to you, not custodian. for smaller accounts, some folks setup those policies as periodic lambdas. custodian is context free with regard to how you want to deploy/operate/use it.
