### ISSUE TITLE
filtration NOT complete(can not filter ALB)? use case:ELB - Delete Unused Elastic Load Balancers

### ISSUE THREAD

**Issue by youzhoutai** [capitalone/cloud-custodian#2150]
the policy created as doc shown(ELB - Delete Unused Elastic Load Balancers), and i did one test, one ALB(one type of ELB) created, which also no instances attached. And one classic LB created with no instances attached. then after running the command, only one instance tagged, it seems that ALB can not be filtered.

**Comment by tim-elliott** [comment]
@youzhoutai ALB = resource type app-elb
