### ISSUE TITLE
Where do I place my my c7n_mailer message templates?

### ISSUE THREAD

**Issue by clembm2w** [capitalone/cloud-custodian#2176]
This is how I installed c7n_mailer.

cd /app
virtualenv c7n_mailer
source c7n_mailer/bin/activate
git clone https://github.com/capitalone/cloud-custodian
cd cloud-custodian/tools/c7n_mailer
pip install -r requirements.txt
python setup.py develop
cd /app/c7n_mailer
c7n-mailer --config /root/mailer.yml --update-lambda

The source directory was placed under /app/cloud-custodian and c7n_mailer was installed under /app/c7n_mailer

Now....what path do I put my message templates?

**Comment by clembm2w** [comment]
I have figured this out for those that run into this same problem.  The way to recompile templates and use them is not very well documented so here goes:

1. Pull the cloud-custodian repo from git
2. Place your template(s) in cloud-custodian/tools/c7n_mailer/msg-templates
3. run python setup.py clean && python setup.py develop
4. c7n_mailer --config <yourconfigfile> --update-lambda 

Every time you need to update a template or add/delete/whatever a template, make sure you follow steps 2-4.

**Comment by thisisshi** [comment]
@clembm2w feel free to add a PR into the mailer's README, issues like this can get lost easily so having it in the docs would be useful.
