### ISSUE TITLE
Pinned Tabulate package in Azure-cli prevents integrating auth/subscription defaults

### ISSUE THREAD

**Issue by stefangordon** [capitalone/cloud-custodian#2196]
Because Azure has pinned this to an older version, we'd have to pin Custodian back to an older version for users to be able to cleanly install via pip.  By changing this people are going to get dependency failures they have to manually resolve, and it is going to be ugly.

Azure-CLI probably shouldn't be pinned to an old version of that popular package, so lets just do the compatiblity tests for them and fix any broken unit tests so they can support a broader range of Tabulate versions.  Win-win.

**Comment by stefangordon** [comment]
Turns out their unit tests pass with everything after 0.7.5 (where they first encountered problems and pinned the package) - so submitted PR
https://github.com/Azure/azure-cli/pull/5985

**Comment by stefangordon** [comment]
That is merged, expected in their 4/10/2018 release - will keep the issue open until then.

**Comment by stefangordon** [comment]
Looks like we were just released in https://github.com/Azure/azure-cli/releases/tag/azure-cli-2.0.31

**Comment by kapilt** [comment]
sounds like this is closed/resolved then.
