### ISSUE TITLE
Is there a work-around for iam-user has-inline-policy

### ISSUE THREAD

**Issue by marvinestreet** [capitalone/cloud-custodian#2225]
I see that this feature has been merged here: https://github.com/capitalone/cloud-custodian/pull/1657

However, the latest build (0.8.28.0) does not have this code in it. I was wondering if there's a way to filter on iam-users who have direct policies attached (instead of say via groups or roles) without having to wait for the version of cloud-custodian to be released with this merge? 

Thanks.

**Comment by kapilt** [comment]
outside of waiting for a release, the other option is running from a source checkout. We'll have another release in the next few days (week of 4/15)
