### ISSUE TITLE
SQS tag calls being throttled

### ISSUE THREAD

**Issue by ocampocj** [capitalone/cloud-custodian#2226]
SQS tag calls are easily getting throttled:

ClientError: An error occurred (RequestThrottled) when calling the ListQueueTags operation (reached max retries: 4): Request is throttled.

Reducing workers seems to mitigate the issue:  https://github.com/capitalone/cloud-custodian/blob/master/c7n/resources/sqs.py#L87

However, switching out to universal tags might also help...

**Comment by kapilt** [comment]
addressed in #2229
