### ISSUE TITLE
Need help with defining the best practice for a centralized architecue of CloudCustodian which will span across multiple accounts

### ISSUE THREAD

**Issue by amansukhaniEBSCO** [capitalone/cloud-custodian#2244]
Hey Guys, 
The tool looks awesome and I cant wait to use it, thanks for all the efforts. 
I was just curious to know if you guys have defined a best practice for a centralized CloudCustodian architecture that will let me use it across multiple accounts, I did see some issues where people mentioned c7n-org but I did not see a best practices part for he architecture anywhere. 

What I am looking to do: 
I would like to have CloudCustodian in one central place (maybe the master payer account) and  use it to govern all the sub accounts. 

Please let me know if I am on the right track. 

Thank you

**Comment by thisisshi** [comment]
Some arch includes running from a single account and using c7n-org and its corresponding config file to assume into the subsequent child accounts. You'll want to do an audit of the permissions required to execute each policy and ensure that the corresponding roles have access.

In terms of the cloudtrail/lambda based policies, those will be deployed into whichever account is being targeted, so there's a limited amount of centralization you can do on that front.

**Comment by amansukhaniEBSCO** [comment]
Thanks for the quick response thisisshi, going through and think about the potential security risks of what we are trying to accomplish with custodian I am just curious is there a way to define resources that are off-limits, or things that should not be deleted, as they are mission critical? 

Also what is a good way to test the policies that we create? Is there an equivalent of something like the AWS policy simulator for cloud custodian?

**Comment by kapilt** [comment]
typically you define filters to exempt resources either  on the basis of policy exceptions/mission critical. typically folks run a differential for policies in prod vs dev to also cover off on mission critical risk. wrt to testing policies using --dryrun gives the effect of filtering without taking action.

**Comment by thisisshi** [comment]
closing for now, if you have additional questions feel free to ask
