### ISSUE TITLE
Classic Azure resources do not support tags

### ISSUE THREAD

**Issue by aluong** [capitalone/cloud-custodian#2248]
An example of a classic resource is Cloud Services, and it doesn't support tags. As we add support for these resources, we need to somehow identify them so that we don't add the Tag action to their PluginRegistry.

**Comment by stefangordon** [comment]
Or the inverse - only add the tag action to the ARM resource types I guess.

**Comment by kapilt** [comment]
easiest mechanism might be to use a registry subscriber and a resource manager model attribute to distinguish classic and then subscriber function register common behavior to arm resources.
