### ISSUE TITLE
Parallelizing updates to Azure resources

### ISSUE THREAD

**Issue by aluong** [capitalone/cloud-custodian#2249]
We need to figure out how to parallelize SDK calls out when updating Azure resources.

Ex: We want to add the same set of tags to a set of resource groups. Currently, it is being done sequentially, but we could optimize and have it done in parallel.

**Comment by stefangordon** [comment]
Note that this does happen for AWS I believe, so we should go look at examples of how they do it.

**Comment by thisisshi** [comment]
You can use the ThreadPoolExecutor and tune the amount of concurrency like so: https://github.com/capitalone/cloud-custodian/blob/master/c7n/tags.py#L178
