### ISSUE TITLE
AWS Decoupling - Eliminate requirement for AWS region

### ISSUE THREAD

**Issue by stefangordon** [capitalone/cloud-custodian#2250]
Need to eliminate the need for an AWS region when executing GCP or Azure policies.

**Comment by kapilt** [comment]
could you elaborate where your seeing that?

**Comment by stefangordon** [comment]
Maybe just delusional - Was running some policies and was blocked on lack of AWS region (e.g. `AWS_DEFAULT_REGION`) - so filed an issue to remind myself.  But it looks like that is fixed, so I'm guessing I was on an older commit.
