### ISSUE TITLE
Azure Scenario - Identify VMs with a Public IP address

### ISSUE THREAD

**Issue by stefangordon** [capitalone/cloud-custodian#2271]
Find any virtual machine that has a public IP address assigned to it directly.  It is often desirable to prevent users from deploying VM's that are directly publicly accessible (As opposed to going through load balancers and such).

In addition to any new filters/functionality required please:

1) Add a recorded unit test for this based on the existing `vm` ARM template
2) Add a sample policy file to the Azure documentation under `use cases` folder

**Comment by tbarlow12** [comment]
@stefangordon There is a current [limitation of the API](https://github.com/Azure/azure-sdk-for-python/issues/897) that makes it look like it will be 3 different API calls, but I can start looking at it

**Comment by stefangordon** [comment]
We can do this via the RelatedItemsFilter probably, although we have never tried going 3 levels with it. Probably we are just missing the `NetworkInterfaceCard` resource and then attempting to come up with a policy to do it.  (Maybe also some `get_resources` implementations, don't think the base class one is sufficient).

**Comment by tbarlow12** [comment]
So just looking at the `NIC` resource, it does specify an ID for a public IP address, which may be enough in this circumstance. We may not need to make that 3rd call. If the filter is whether or not they have one, would it be sufficient to check and see if there is one?
