### ISSUE TITLE
'c7n_status' in docs should be 'maid_status'

### ISSUE THREAD

**Issue by mandeepbal** [capitalone/cloud-custodian#230]

**Comment by mandeepbal** [comment]
in http://www.capitalone.io/cloud-custodian/usecases/usecases/ebsgarbagecollect.html ..
you need to update the op: deletion in the first policy to op: delete
or change the filter in the 3rd policy from op: delete to op: deletion
because those ops are different

**Comment by mandeepbal** [comment]
@kapilt should we be using `maid_status` or try to switch the code to `c7n_status`? I thought this should've been when we did the name change.

**Comment by kapilt** [comment]
its going to be a little painful either way.

**Comment by mandeepbal** [comment]
Anyway we can maintain backwards compatibility by allowing users to specify the status prefix in the policy yaml? Or should we just leave it and move on. Either way I'll submit a PR to fix the docs today.

**Comment by kapilt** [comment]
they can already specify the key in the yaml

**Comment by mandeepbal** [comment]
I'll just close this issue then. Submitted a PR to fix the typo.
