### ISSUE TITLE
Azure - ID Parsing Utilities

### ISSUE THREAD

**Issue by stefangordon** [capitalone/cloud-custodian#2304]
```
+            resource_group = id.split('/')[4]
+            name = id.split('/')[8]
```

These two extractions of data from the Azure Resource ID happen periodically.  Can we get them in a common utilities class or in some appropriate base class that we have everywhere and then go bulk replace any usages?

**Comment by thisisshi** [comment]
This looks similar to some of the ARN generation that happens for AWS resources, possibly add a function in c7n.utils for that.

reference: https://github.com/capitalone/cloud-custodian/blob/master/c7n/utils.py#L314-L326

**Comment by stefangordon** [comment]
Oh yep we should just copy that model and have a utils.py under Azure plugin so with things that are not applicable to core c7n.

**Comment by stefangordon** [comment]
this is done
