### ISSUE TITLE
Count values for custodian '--dryrun' versus 'run' return differently

### ISSUE THREAD

**Issue by davidclin** [capitalone/cloud-custodian#2316]
This is a follow up on #2310.

I noticed when I perform a --dryrun, the count shows 1 match when I'm expecting to see 3 matches (eg: I have 3 known EC2 instances with subnets that are tagged with the Location:Internet key/value pair.

When I perform the actual run (eg: in absence of --dryrun), the count returns a value of 3 which matches the environment.

I was expecting the count for the 'run' and '--dryrun' to be the same.  Is this expected behavior?

----------------  dry-run example output  -------------------
(custodian) $ custodian run --dryrun -s . public-subnet-instance-audit.yml                                                  2018-05-02 08:48:12,729: custodian.policy:INFO policy: public-subnet-instance-audit resource:ec2 region:us-east-1 count:0 time:0.08

----------------  run example output  -------------------
(custodian) $ custodian run -s . public-subnet-instance-audit.yml                                                           2018-05-02 08:53:46,491: custodian.policy:INFO policy: public-subnet-instance-audit resource:ec2 region:us-east-1 count:3 time:0.40
2018-05-02 08:53:46,493: custodian.actions:INFO Stop 3 of 3 instances
2018-05-02 08:53:46,707: custodian.policy:INFO policy: public-subnet-instance-audit action: stop resources: 3 execution_time: 0.21

**Comment by kapilt** [comment]
they should be the same, do you have an example policy? perhaps your running into cache issues --cache-period=0 to disable

```
$ cat ec2.yml 
policies:
  - name: running-instances
    resource: ec2
    filters:
     - State.Name: running

$ custodian run --dryrun -c ec2.yml -s out
2018-05-02 06:11:18,624: custodian.policy:INFO policy: running-instances resource:ec2 region:us-east-2 count:2 time:1.12
$ custodian run  -c ec2.yml -s out
2018-05-02 06:11:26,907: custodian.policy:INFO policy: running-instances resource:ec2 region:us-east-2 count:2 time:0.01
```

**Comment by davidclin** [comment]
The --dryrun is returning the correct count now. 

Oddly, I didn't change anything in my environment from last night.

Does the cache have a timeout value?  

Below is an example of my policy:

policies:
  - name: public-subnet-instance-audit
    resource: ec2
    description: |
      Filter ec2 resources based on the attributes of the network
      they are attached to then take action. For example, subnets with tag 
      'Location' and value that matches 'Internet' should be stopped.
    filters:
      - type: subnet
        key: "tag:Location"
        value: "Internet"
    actions:
      - stop

**Comment by kapilt** [comment]
yeah.. it has a default 15m period (per custodian run --help output).

**Comment by davidclin** [comment]
Thanks, that clarifies everything. 👍
