### ISSUE TITLE
Cloud Watch events execution mode with target RunInstances

### ISSUE THREAD

**Issue by davidclin** [capitalone/cloud-custodian#2321]
This is a follow on of #2257 

I'm unable to get the following policy to stop newly launched EC2 instances that are assigned to subnets with key/value pair of Location:Internet.  

The policy is executed using the Cloud Watch events mode :

<pre>
 policies:
  - name: subnet-audit
    resource: ec2
    mode:
      type: cloudtrail
      role: arn:aws:iam::xxxxxxxxxxxx:role/CloudCustodianRole
      events:
        - source: ec2.amazonaws.com
          event: RunInstances
          ids: "responseElements.instanceSet.items[].instanceId"
    filters:
      - type: subnet
        key: "tag:Location"
        value: "Internet"
    actions:
      - stop
</pre>

Execution run
<pre>
(custodian) $ custodian run -s . public-subnet-instance-audit-lambda.yml
2018-05-02 21:19:52,473: custodian.policy:INFO Provisioning policy lambda subnet-audit
2018-05-02 21:19:52,704: custodian.lambda:INFO Publishing custodian policy lambda function custodian-subnet-audit
</pre>

The lambda is successfully created and viewable from the AWS management console.

Need tips/guidance on how to troubleshoot the Lambda. This is all new to me.

**Comment by davidclin** [comment]
Also tried having Lambda receive EC2 instance state event without success:

<pre>
policies:
  - name: subnet-audit
    resource: ec2
    mode:
      type: ec2-instance-state
      role: arn:aws:iam::xxxxxxxxxxxx:role/CloudCustodianRole
      events:
        - pending
    filters:
      - type: subnet
        key: "tag:Location"
        value: "Internet"
    actions:
      - stop
</pre>

I am launching the test EC2 instance from the management console and making sure I'm selecting a subnet with the tag Location:Internet.

**Comment by davidclin** [comment]
I was able to get the Lambda working by:

(1) using ec2-instance-state 
(2) adding EC2 permissions for the role (namely, to stop instances)
(3) changing the events from 'pending' to 'running'

It's not entirely clear to me why the lambda will not trigger when a new EC2 instance is launched and is in 'pending' state.

**Comment by kapilt** [comment]
instances in pending state can't be stopped, only terminated. See https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ec2-instance-lifecycle.html

for more details.

**Comment by kapilt** [comment]
There should have been a note in the policy lambda logs about having to implicitly filter those out for the stop action as well.

**Comment by davidclin** [comment]
For the benefit of fellow Cloud Custodian users who are getting their feet wet and following this thread as part of the troubleshooting process, I was able to view the Lambda error logs in CloudWatch by adding permissions to the Lambda role. 

Namely, I added CloudWatch Log permissions for  "logs:CreateLogGroup","logs:CreateLogStream","logs:PutLogEvents":

<pre>
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": [
                "logs:CreateLogStream",
                "ec2:*",
                "logs:CreateLogGroup",
                "logs:PutLogEvents"
            ],
            "Resource": "*"
        }
    ]
}
</pre>

While I'm still unable to find anything in the logs related to having to implicitly filter out the same for the stop action, I'm at least able to see the logs of the entire workflow and see what the lambda is doing.

Snip from lambda logs:
<pre>
[DEBUG]	2018-05-03T19:44:52.127Z	708b88c8-4f0a-11e8-b5a1-85c41233ee4e	metric:ResourceCount Count:1 policy:subnet-audit restype:ec2 scope:policy
[INFO]	2018-05-03T19:44:52.127Z	708b88c8-4f0a-11e8-b5a1-85c41233ee4e	**Invoking actions** [<c7n.resources.ec2.Stop object at 0x7f94049570d0>]
[INFO]	2018-05-03T19:44:52.127Z	708b88c8-4f0a-11e8-b5a1-85c41233ee4e	policy: subnet-audit **invoking action: stop** resources: 1
[INFO]	2018-05-03T19:44:52.128Z	708b88c8-4f0a-11e8-b5a1-85c41233ee4e	**Stop** 0 of 1 instances
</pre>

**Comment by davidclin** [comment]
I think we can close this out. I have a working policy now. 👍
