### ISSUE TITLE
Azure Docs - Resource type documentation pages

### ISSUE THREAD

**Issue by stefangordon** [capitalone/cloud-custodian#2349]
We have a few resources types with custom filters/actions now.  These need to be documented fully like AWS does in \policy\resources.

We need to add this section into our Azure docs and document NSG, Resource Group and anything else with custom actions filters at the first priority.

**Comment by stefangordon** [comment]
Yeah that should probably be another work item, in this case I was referring to the subset that had some hand written docs (I assumed they are hand written).

**Comment by tbarlow12** [comment]
This issue can be closed
