### ISSUE TITLE
Update s3 bucket encryption filter to have a `state: disabled` option

### ISSUE THREAD

**Issue by theCMack** [capitalone/cloud-custodian#2401]
When using `type: bucket-encryption` there is no way to filter by buckets without encryption.

**Comment by abhilashjavvaji** [comment]
Is this option state working in the policy ?? I get validation error when I am trying to find buckets without encryption. Here is my policy and error 

policies:
- name: s3-bucket-encryption-off
  resource: s3
  region: us-east-1
  filters:
    - type: bucket-encryption
      state: false


ERROR Additional properties are not allowed ('state' was unexpected)

Failed validating u'additionalProperties' in schema[0]:
    {u'additionalProperties': False,
     u'properties': {'crypto': {u'enum': [u'AES256', u'aws:kms'],
                                u'type': u'string'},
                     'key': {u'type': u'string'},
                     u'type': {u'enum': [u'bucket-encryption']}},
     u'required': [u'crypto', u'type'],
     u'type': u'object'}

On instance:
    {'state': False, 'type': 'bucket-encryption'}
