### ISSUE TITLE
Azure - Metric support

### ISSUE THREAD

**Issue by stefangordon** [capitalone/cloud-custodian#2444]
http://capitalone.github.io/cloud-custodian/docs/quickstart/usage.html#metrics

Need to figure out what the equivalent story is for Azure and queue work items for it.

We can use this thread for design discussion leading up to filing issues for implementation.

**Comment by tbarlow12** [comment]
Looks like [Azure Monitor](https://www.quora.com/What-is-Windows-Azures-equivalent-of-Amazon-CloudWatch) is what we're looking for. I'll start poking at this one and see what I can find
