### ISSUE TITLE
Clarify 'ASG Structurally Invalid' error w.r.t. EBS snapshot

### ISSUE THREAD

**Issue by gasserk** [capitalone/cloud-custodian#2478]
For apps with lots of data and application snapshots, it would help immediately clarify the source of the structural issue if this error were qualified as 'EBS' snapshot issue:

https://github.com/capitalone/cloud-custodian/blob/master/c7n/resources/asg.py#L338

Suggest just updating the error string to: `invalid-EBS-snapshot`.

**Comment by kapilt** [comment]
For an asg, there isn't any other kind of snapshot. The intent is that this is an error code and that a mailer message template can format/present that error for human users. Ie. think i18n. The right place to change this for better ux is at the presentation layer in the notification template that's being used.

**Comment by gasserk** [comment]
OK gotcha thanks @kapilt makes sense -- will fix the context boilerplate in the message template.
