### ISSUE TITLE
KeyError for a cloudtrail policy

### ISSUE THREAD

**Issue by ctippur** [capitalone/cloud-custodian#2483]
Use case: A trail has not been created for a region, or logging is turned off for a trail.
```yaml
policies:
- name: test
  resource: cloudtrail
  filters:
  - not:
    - type: value
      key: HomeRegion
      op: regex
      value: '.*-.*-.*'
```

I am getting an error:
```
File "/Users/shekartippur/PycharmProjects/cloudcustodian/venv/lib/python3.6/site-packages/c7n/filters/core.py", line 256, in <dictcomp>
    resource_map = {r[resource_type.id]: r for r in resources}
KeyError: 'TrailArn'
```

Couple of questions:
1. Is this the right approach for my use case?
2. Why is it looking for TrailArn key?
3. Could there be a typo as resources.json has TrailARN (Caps ARN)?

**Comment by thisisshi** [comment]
This is a bug, I'll be fixing it shortly
