### ISSUE TITLE
Date math to check expiration on certificates

### ISSUE THREAD

**Issue by ctippur** [capitalone/cloud-custodian#2487]
I have a couple of use cases where I need to check validity of a resource based on expiration date

Use case 1:  Resource: iam-user - The access key is active and has not been rotated in the last 2 years
Use case 2: Resource: acm-certificate - A custom SSL certificate expires in the next seven days.

I couldnt find a way to do this.

**Comment by kapilt** [comment]
both of these use cases are built into the generic value filter, using `value_type: age` and `value_type: expiration`  respective, the former lets you match against the (current time - date attribute of a resource), the later lets you match on (date attribute of a resource - current time).

**Comment by ctippur** [comment]
Thanks for the clarification. I see it now
https://www.capitalone.io/docs/filters.html
