### ISSUE TITLE
Azure - Fill out setup.py metadata fully

### ISSUE THREAD

**Issue by stefangordon** [capitalone/cloud-custodian#2500]
Description/Long Description/url/etc - so it looks good on PyPi

**Comment by kapilt** [comment]
also do you have a pypi login, i can add you to the c7n_azure maintainers there.

**Comment by stefangordon** [comment]
https://pypi.org/user/stefangordon/

**Comment by aluong** [comment]
Can I be added as well? https://pypi.org/user/aluong/
