### ISSUE TITLE
Occasionally EC2 describe_instances returns no tags

### ISSUE THREAD

**Issue by ewbankkit** [capitalone/cloud-custodian#252]
If no tag filters are specified to the EC2 `describe_instances` call (or similar calls to describe other resource types) then AWS is allowed to return no tags at all:
* http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/Using_Tags.html#Using_Tags_CLI

If this happens then EC2 filters on tag values fail as there are no tags to filter on.
This causes unexpected behavior.

**Comment by kapilt** [comment]
it seems this may apply to any resources using the ec2 api, which all seem to return tags as part of their base describe calls. i checked other services documentation (asg, etc), none exude this caveat, on results outputs going awol.
