### ISSUE TITLE
Network Security Group schemas

### ISSUE THREAD

**Issue by stefangordon** [capitalone/cloud-custodian#2541]
Was trying to use this today and noticed lots of capitalized fields mixed into the schemas for ingress/egress/etc.  I believe all field names should be lower case so it looked sort of funky.  We probably need to refactor those everywhere.

Also it wasn't really clear what ports vs. onlyports does, we could flush out that doc page more to explain some of those, just a bulleted list of field names/descriptions for some of the less obvious ones.  OnlyPorts name implies it would catch items with only those ports open but the example indicates it works like "ExceptPorts" or "ExcludePorts" or maybe "PortsOtherThan:".

@tbarlow12

**Comment by tbarlow12** [comment]
@stefangordon I agree. The thinking at the time was to remain consistent with the AWS side of things. But I think it should definitely be a little more clear. I'll get going on this

**Comment by stefangordon** [comment]
It looks to me like the AWS ones are wrong too, lol - I'll ask someone who worked on it if I'm crazy

**Comment by kapilt** [comment]
yeah.. its is more of an except ports implementation for only ports
