### ISSUE TITLE
Link to quickstart guide broken

### ISSUE THREAD

**Issue by naveenb29** [capitalone/cloud-custodian#2578]
http://www.capitalone.io/cloud-custodian/docs/index.html

**Comment by thisisshi** [comment]
Thanks for the bug report, looks like the link came from here: https://developer.capitalone.com/opensource-projects/cloud-custodian/

here's a valid link to the docs: http://capitalone.github.io/cloud-custodian/docs/

**Comment by thisisshi** [comment]
The link there should be fixed now, closing
