### ISSUE TITLE
PyYaml conflict

### ISSUE THREAD

**Issue by stefangordon** [capitalone/cloud-custodian#2594]
So I guess the brand new PyYaml==4.2b4 is required for Python 3.7 compatibility so people are starting to require it.  Azure-CLI now requires it... 

We have a variety of conflicts.  I can pin an old version of Azure CLI now, but realistically we probably need to eliminate these old ones so we can work in Python 3.7

![image](https://user-images.githubusercontent.com/4087345/42241712-5b00dd2a-7ec0-11e8-9fef-c4795bbd438f.png)

**Comment by stefangordon** [comment]
Removing P0 tag as I have worked around this for now, but we should decide if we want to bump all these other dependencies.  I updated them but I'm not sure I know how to test all those other modules.

**Comment by kapilt** [comment]
fwiw, I've been using `pipdeptree` to debug the version conflicts. its got a reverse mode dep mode as well  ie `pipdeptree -r -p pyyaml`

**Comment by stefangordon** [comment]
So my workaround here just makes it harder for us to get to Python 3.7 - assuming that is a goal we should probably go move pyyaml to latest on all those modules.   I can certainly do it without breaking the build but won't be able to test some of those tools probably.  

I'll have to do it soon anyway as we can't stuck to older Azure versions or we'll miss new API's.

**Comment by kapilt** [comment]
so it looks like we can just fix those two reverse deps that have hard pins on 3.x to do `>=` and things should be good.
