### ISSUE TITLE
Azure Functions - Deploy Azure Monitor Alerts

### ISSUE THREAD

**Issue by stefangordon** [capitalone/cloud-custodian#2607]
The policy provider for event based functions will need to setup the monitor alerts *after* the function is published.

These are the new preview monitor alerts and action groups, with an action group type of `webhook` (NOT function, which won't support auth).  With webhook we'll (later) be able to include Auth key in the URL.

We can start with hard-coding the alert to be subscription wide on the resource type in the policy, and just on the 'create or update' (write) activity logs.

We'll need to check if one already exists (and if so just add us as another action to it if we aren't already in the existing actions) or make it if not.  

I think they are scoped to resource groups, if everything is scoped to resource group I'm good with reusing alerts and actions in the RG we are deploying the function to to keep things clean.

**Comment by aluong** [comment]
It seems like Event Grid (#2806) is a better option for an Event Based trigger at this time.
