### ISSUE TITLE
return list of inline policies for an iam role

### ISSUE THREAD

**Issue by mukavik** [capitalone/cloud-custodian#2630]
Use case - To check if an IAM policy has certain inline policies. 
The current check is limited to whether there is an inline policy = True/False. 
It would useful to have an expanded policy to check for specific inline policies. 

Thanks

**Comment by thisisshi** [comment]
hey @mukavik I've pushed an update to our iam-role/user/group to return back the inline policies in the resources.json, there's an example of how to filter on inline policies as well in the pr: #2636

**Comment by mukavik** [comment]
Appreciated.
