### ISSUE TITLE
Offhours schedule doesn't accept time zone identifiers

### ISSUE THREAD

**Issue by affoliveira** [capitalone/cloud-custodian#2640]
If I add a timezone identifier that is not a part of the TZ_ALIASES list but is a valid time zone identifier I get "Could not resolve tz on resource" error.

As a test I also changed the test_onhour test tz to "America/Los_Angeles" in the offhours test file and running  the test provides the same error:

"offhours.py                417 WARNING  Could not resolve tz on resource:i-1aebf7c0 value:tz=america/los_angeles
"
In the filters/offhours.py file, we have function get_tag_values that is storing the value of the tag as lowercase. This also converts the time zone identifiers which causes the tz to become "america/los_angeles" which is not recogbized by dateutil `zoneinfo.gettz:`

def get_tag_value(self, i):
        """Get the resource's tag value specifying its schedule."""
        # Look for the tag, Normalize tag key and tag value
        found = False
        for t in i.get('Tags', ()):
            if t['Key'].lower() == self.tag_key:
                found = t['Value']
                break
        if found is False:
            return False
        # enforce utf8, or do translate tables via unicode ord mapping
        **value = found.lower().encode('utf8').decode('utf8')**
        # Some folks seem to be interpreting the docs quote marks as
        # literal for values.
        value = value.strip("'").strip('"')
        return value

**Comment by affoliveira** [comment]
In the filters/offhours.py file, we have function get_tag_values that is storing the value of the tag as lowercase. This also converts the time zone identifiers which causes the tz to become "america/los_angeles" which is not recogbized by dateutil zoneinfo.getttz:

def get_tag_value(self, i):
        """Get the resource's tag value specifying its schedule."""
        # Look for the tag, Normalize tag key and tag value
        found = False
        for t in i.get('Tags', ()):
            if t['Key'].lower() == self.tag_key:
                found = t['Value']
                break
        if found is False:
            return False
        # enforce utf8, or do translate tables via unicode ord mapping
        value = found.lower().encode('utf8').decode('utf8')
        # Some folks seem to be interpreting the docs quote marks as
        # literal for values.
        value = value.strip("'").strip('"')
        return value

**Comment by kapilt** [comment]
Thanks for the bug report.
