### ISSUE TITLE
c7n-org run for multiple azure subscription

### ISSUE THREAD

**Issue by durgadeviramadoss** [capitalone/cloud-custodian#2646]
Hi Team,

I am trying to setup c7n-org to run across multiple azure subscriptions.

Generated subscriptions.yaml using below command,
python /home/ubuntu/cloud-custodian/tools/c7n_org/scripts/azuresubs.py -f subscriptions.yml

Command used to run
(custodian) ubuntu@Custodian:~$ c7n-org run -c /home/ubuntu/cloud-custodian/tools/c7n_org/scripts/subscriptions.yml -s . -u policies/tag.yml

Error
Traceback (most recent call last):
  File "/usr/local/bin/c7n-org", line 11, in <module>
    sys.exit(cli())
  File "/home/ubuntu/.local/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/ubuntu/.local/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/c7n_org/cli.py", line 434, in run
    config, use, debug, verbose, accounts, tags, policy)
  File "/usr/local/lib/python2.7/dist-packages/c7n_org/cli.py", line 107, in init
    jsonschema.validate(accounts_config, CONFIG_SCHEMA)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/jsonschema/validators.py", line 541, in validate
    cls(schema, *args, **kwargs).validate(instance)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/jsonschema/validators.py", line 130, in validate
    raise error
jsonschema.exceptions.ValidationError: 'accounts' is a required property

Failed validating 'required' in schema:
    {'$schema': 'http://json-schema.org/schema#',
     'additionalProperties': False,
     'definitions': {'account': {'additionalProperties': True,
                                 'anyOf': [{'required': ['role',
                                                         'account_id']},
                                           {'required': ['profile',
                                                         'account_id']}],
                                 'properties': {'account_id': {'type': 'string'},
                                                'email': {'type': 'string'},
                                                'name': {'type': 'string'},
                                                'profile': {'type': 'string'},
                                                'regions': {'items': {'type': 'string'},
                                                            'type': 'array'},
                                                'role': {'oneOf': [{'items': {'type': 'string'},
                                                                    'type': 'array'},
                                                                   {'type': 'string'}]},
                                                'tags': {'items': {'type': 'string'},
                                                         'type': 'array'}},
                                 'type': 'object'}},
     'id': 'http://schema.cloudcustodian.io/v0/orgrunner.json',
     'properties': {'accounts': {'items': {'$ref': '#/definitions/account'},
                                 'type': 'array'},
                    'vars': {'type': 'object'}},
     'required': ['accounts'],
     'type': 'object'}

On instance:
    {'subscriptions': [{'name': 'Visual Studio Professional',
                        'subscription_id': 'xxx-xxxx-xxx'},
                       {'name': 'Pay-As-You-Go',
                        'subscription_id': 'xxx-xxxx-xxx'}]}

Please check this

**Comment by aluong** [comment]
I could not repro this issue.
