### ISSUE TITLE
SNS Message Attributes

### ISSUE THREAD

**Issue by marvinestreetcr** [capitalone/cloud-custodian#2649]
I was just wondering if it's possible to add message attributes to SNS messages via the custodian mailer?

**Comment by thisisshi** [comment]
As of now no, that functionality does not exist within the notify action currently. Do you have a use case for adding additional user-defined attributes?

**Comment by marvinestreetcr** [comment]
We currently have a lot of notifications being generated by cloud custodian. And it would be nice to add attributes, such as "account number" to the SNS topics, so that end-users can subscribe more granularly to notifications.

**Comment by thisisshi** [comment]
Sounds like a valid use case for me, I have some changes locally in a branch that implements this feature, still need to do some testing for it though, i'll submit a pr sometime later this week possibly
