### ISSUE TITLE
s3 as url in `value_from` is not working

### ISSUE THREAD

**Issue by aardvarq** [capitalone/cloud-custodian#2655]
I've got a json file hosted on a web server that I'm using as my url in a value_from expression. Works great. If I move it locally and change to a `file:` url, it also works fine. However, when I move that same file to s3 and use that in my url, it fails with what appears to be an invalid json file error. If I specify a path to a bogus file like `/etc/services` I get the very same error, leading me to believe it's not reading it properly from s3? I've tried specifying `format: json` and also not specifying it, no change. I've validated that it's accessing the file correctly.

**Comment by aardvarq** [comment]
I'm seeing no decoding of the bytestream for s3 uris here:
https://github.com/capitalone/cloud-custodian/blob/master/c7n/resolver.py#L37 upstream

If I decode the `contents` object first, my policy fires successfully.

**Comment by kapilt** [comment]
yeah this is an artifact from py2->py3 compat that got missed, unfortunately the rest recorders normalized s3 responses with encoding it looks like. thanks for the bug report.

**Comment by thisisshi** [comment]
@aardvarq I've worked with @troylar on https://github.com/capitalone/cloud-custodian/pull/2657 to address this issue + another py2->3 string decode issue

**Comment by jonathanwcrane** [comment]
I've had the same issue so fixing this would be very helpful.  Thanks.

**Comment by thisisshi** [comment]
@aardvarq can you pull the latest version of cloud custodian from master and try again? https://github.com/capitalone/cloud-custodian/pull/2657 was merged that should have addressed this issue.
