### ISSUE TITLE
Enable c7n to release Elastic IP addresses

### ISSUE THREAD

**Issue by IDT-kcrook** [capitalone/cloud-custodian#2678]
I can report on unattached elastic IP addresses, but I have to then manually release them.

Cloud Custodian already receives the allocation id, which is the only piece of information needed for AWS to release an address.

The documentation here is not correct as releasing the address is not a supported action: https://bit.ly/2Lr84up

**Comment by thisisshi** [comment]
This was actually added here: https://github.com/capitalone/cloud-custodian/issues/2290, it hasn't been release in a pip version yet. You can use it if you do the developer install and run from source

**Comment by IDT-kcrook** [comment]
Is there a timeline or plans to adding this to the pip version?

**Comment by thisisshi** [comment]
new release is tbd, more details will probably show up in this issue: https://github.com/capitalone/cloud-custodian/issues/2679

**Comment by IDT-kcrook** [comment]
This feature is live in the newest release.
