### ISSUE TITLE
When is the next release?

### ISSUE THREAD

**Issue by eamonnfaherty** [capitalone/cloud-custodian#2679]
I was wondering if you were planning a release soon? 

Github is saying there has been 282 commits since the last release.

**Comment by aughban** [comment]
+1

**Comment by eamonnfaherty** [comment]
Thanks for labeling this one @kapilt  

Do you have any idea when this will be?  Even a rough estimate would be great.

**Comment by kapilt** [comment]
0.8.30 got released mid august.
