### ISSUE TITLE
Output directory is being requested even when cloudwatch log group is specified.

### ISSUE THREAD

**Issue by choonming** [capitalone/cloud-custodian#2694]
Custodian is requesting for the output directory even when the log group for cloudwatch is being specified.  The documentation states that the `-s` parameter is optional and not mandatory. Looking into the code, I found the following:

```
100     if 'output-dir' not in blacklist:
101         p.add_argument("-s", "--output-dir", required=True,
102                        help="Directory or S3 URL For policy output")
```

```
$ custodian run policies/offhours.yml -l /cloud-custodian
usage: custodian run [-h] [-r REGION] [--profile PROFILE]
                     [--assume ASSUME_ROLE] [--external-id EXTERNAL_ID]
                     [-p POLICY_FILTER] [-t RESOURCE_TYPE] [-v] [-q]
                     [-l LOG_GROUP] -s OUTPUT_DIR [-f CACHE]
                     [--cache-period CACHE_PERIOD] [-d] [-m]
                     [configs [configs ...]]
custodian run: error: argument -s/--output-dir is required
```

Is this a code error or documentation is not updated?

**Comment by kapilt** [comment]
The output directory is always required. We have json records we need to place in an object storage independently of any log sinks. Where in the docs do you see that it is specified as optional?

**Comment by choonming** [comment]
You can find it here in the documentation http://capitalone.github.io/cloud-custodian/docs/quickstart/index.html#monitor-resources and from the cli itself

```
optional arguments:
  -h, --help            show this help message and exit
  -l LOG_GROUP, --log-group LOG_GROUP
                        Cloudwatch Log Group to send policy logs
  -s OUTPUT_DIR, --output-dir OUTPUT_DIR
                        Directory or S3 URL For policy output
  -f CACHE, --cache CACHE
                        Cache file (default ~/.cache/cloud-custodian.cache)
  --cache-period CACHE_PERIOD
                        Cache validity in minutes (default 15)
  -d, --dryrun          Don't execute actions but filter resources
  -m, --metrics-enabled
                        Emit metrics to CloudWatch Metrics
```

**Comment by kapilt** [comment]
ah.. yeah thats related to how the library we use for option parsing presents parameters, there is unfortunately not a whole lot we can do to fix that without switching out cli libraries. argparse help customization is pretty limited from what I remember.

**Comment by thisisshi** [comment]
thanks for opening the issue, i've clarified the usage of -s in the cli by adding `[REQUIRED]` into the description of the `-s` flag and fixed the example in the docs

https://github.com/capitalone/cloud-custodian/pull/2702
