### ISSUE TITLE
azure - better documentation for using the mailer

### ISSUE THREAD

**Issue by erwelch** [capitalone/cloud-custodian#2708]
currently the docs for the mailer are in a readme file in the mailer application, but docs for azure policies show to use the activity notify without an explanation of how to setup the mailer.

**Comment by stefangordon** [comment]
At a minimum we should add a note to any place notify action shows up in the docs pointing people to the external mailer tool and its readme.    We should also remove the notify action from places that it isn't necessary in the example as it's an advanced usage that requires the user to figure out how to use mailer in their environment.

**Comment by jdogg89** [comment]
@stefangordon I'm kind of at a stand still with trying to setup mailer notifications in my Azure account with cloud custodian, I don't see what should be entered under the 'role' piece in the mailer.yaml file, as this isn't a 1:1 mapping form AWS to Azure: 

 1 queue_url: https://mybucket.queue.core.windows.net/taskqueue
  2 role: ????
  3 from_address: myMailerAddress
~

**Comment by stefangordon** [comment]
https://github.com/capitalone/cloud-custodian/blob/master/tools/c7n_mailer/README.md#using-on-azure

You don't need role, the below is a mailer config:

```queue_url: asq://storageaccount.queue.core.windows.net/queuename
from_address: you@youremail.com
sendgrid_api_key: SENDGRID_API_KEY```

**Comment by jdogg89** [comment]
@stefangordon Follow up on the credentials piece, I'm able to use `custodian run` commands and run ad hoc items just fine, when trying to run `c7n-mailer --config mailer.yml`, I'm receiving "botocore.exceptions.NoCredentialsError: Unable to locate credentials". Do credentials have to be passed differently when running c7n-mailer? I must be missing something here.

**Comment by stefangordon** [comment]
@aluong maybe someone can check on this when they have a moment to make sure mailer CLI hasn't had some new bug introduced.  If I recall it uses the normal custodian credentials search path so if custodian is running Azure policies successfully *and* latest mailer from GitHub is in use, then it ought to work.  It'll be a couple days before I can pull latest and check.

**Comment by stefangordon** [comment]
I know we sort of sent snippets back and forth already, but can you also share your mailer.yml (obscured as appropriate).  @jdogg89

**Comment by jdogg89** [comment]
This is just what I took from the readme, to fill this out from this, if there's a lot more that I'm missing that I need in addition to this, let me know, and perhaps I can make a PR to the docs page in case anyone else tries this and runs into this.  

```
  queue_url: https://XXXXXXX.queue.core.windows.net/taskqueue
  sendgrid_api_key: XXXXXXX
  from_address: username@XXXXXX.com
```

**Comment by stefangordon** [comment]
Re: slack - the Azure support and slack support were going in at the same time and a few things ended up missing to enable it, relatively minor #2633

Regarding the error, the easy answer could be there was just some junk in the queue perhaps that wasn't a message for it?  Its basically saying it wasn't properly formatted gzip data (all the messages get zipped).

I'd expect an action to look something like this:
(Note:  the HTTPS vs ASQ prefix on the queue URL in the action doesn't matter, it will do either)

    actions:
      - type: notify
        template: default
        priority_header: '2'
        subject: Hello from C7N Mailer
        to:
          - you@youremail.com
        transport:
          type: asq
          queue: https://storageaccount.queue.core.windows.net/queuename

**Comment by jdogg89** [comment]
This is great, thanks again. You accept PR's if I end up digging into this enough to contribute?

**Comment by stefangordon** [comment]
There is a little contributor agreement you will have to accept, but yes for sure.

**Comment by stefangordon** [comment]
Closing as we are covering all discussed issues in dedicated work items.
