### ISSUE TITLE
rds unmark action throws NotImplementedError

### ISSUE THREAD

**Issue by jeffastorey** [capitalone/cloud-custodian#273]
Using the `unmark` action on an rds instance throws the following error:

```
2016-07-06 17:38:43,679: custodian.output:ERROR Error while executing policy
Traceback (most recent call last):
  File "/development/workspace/cloud-custodian/c7n/policy.py", line 213, in poll
    results = a.process(resources)
  File "/development/workspace/cloud-custodian/c7n/tags.py", line 339, in process
    tags, self.id_key, f.exception()))
  File "/development/workspace/cloud-custodian/c7n/tags.py", line 60, in id_key
    raise NotImplementedError()
NotImplementedError
```

**Comment by kapilt** [comment]
thats in the exception handler while going to log. nutshell tags.py needs to rely on the meta-model more instead of typegen registration or subclasses.

**Comment by kapilt** [comment]
besides the log err, underlying issue seems to be account_id on rds resource manager is only populated on non cache lookups, it should always be populated for rds.

**Comment by ewbankkit** [comment]
I'm taking a look at this one.

**Comment by ewbankkit** [comment]
It looks like I can replace the use of the `ResourceTag` class in `tags.py` with use of the resource meta-model, for example:
```
self.manager.query.resolve(self.manager.resource_type)
```
to get the model and then `model.id` to get the ID field name.
