### ISSUE TITLE
Custom Snapshot Scheduling

### ISSUE THREAD

**Issue by jimmyraywv** [capitalone/cloud-custodian#274]
We would like to be able to define custom times/windows to perform nightly backups via Cloud Custodian.  This is a cost reduction effort as well as snapshot resource reduction effort.  One-size-fits-all backup times are leading to duplicate nightly backups for EBS resource.  Without owner defined windows, we will use tags to exclude backups via nightly Cloud Custodian executions.  This is not the best solution as it requires manual tag intervention and is restricted by the AWS custom tag limit.

  - name: ec2-nightly-backup
    tags:
      - backups
    resource: ec2
    filters:
      - "tag:nightly_bu_exclude": absent
    actions:
     - snapshot

**Comment by kapilt** [comment]
this isn't really a sw request, its more a local installation request. ie. its more a question of how custodian is being employed by an org. the sw itself can be run on any schedule, or use periodic lambdas for arbitrary schedules.
