### ISSUE TITLE
AWS Cloud Custodian - Filter to VPC

### ISSUE THREAD

**Issue by miles-collier** [capitalone/cloud-custodian#2756]
It doesn't appear natively you can filter down to a particular VPC with Cloud Custodian. If that's not the case, let me know. Is there any "hacky" way to do this? 

At the moment my only solution would be to add tags to show which project/vpc we're in, but with our workflow that would be less than ideal. Any ideas?

**Comment by tim-elliott** [comment]
If I understand what you are asking for...most if not all resource types that exist withing a VPC have a reference to the VPC Id in their output resource information (ex: for ELB it is `VPCId`, for RDS it's `DBSubnetGroup.VpcId`, etc).  So you can filter on that field and specify the VPC you want.

**Comment by miles-collier** [comment]
Correct, that would be ideal! At the moment I may just Terraform a tag for reference

**Comment by kapilt** [comment]
can you elaborate with a full example. ie. you want to find all ec2 instances in a vpc based on the tag of the vpc?

**Comment by miles-collier** [comment]
@kapilt This was more of a feature request-ish. 

Instead of a direct tag on an EC2 instance, being able to simply take the VPC Id and isolate policies to that would be ideal as @tim-elliott stated. E.g. an EC2 scheduler will only filter to a particular VPC Id.

I am creating an IAM policy now (vpc isolated), think that may be a good option.

**Comment by miles-collier** [comment]
I am currently trying to use a filter from the docs:
```      - type: value
        key: "attachment.vpc-id"
        value: xxx```

Fetches: `LexerError: Bad jmespath expression: Unknown token '-':`
