### ISSUE TITLE
azure - Add support for offhour, onhour filters on VMs

### ISSUE THREAD

**Issue by billpratt** [capitalone/cloud-custodian#2773]
I think we could use the [currently implemented filter](https://github.com/capitalone/cloud-custodian/blob/master/c7n/filters/offhours.py) and add it to Azure VMs similar to [aws ec2](https://github.com/capitalone/cloud-custodian/blob/master/c7n/resources/ec2.py#L451)

**Comment by kapilt** [comment]
yeah. its pretty generic / independent of provider. the only consideration is populating tags into the same structure, and if the tag value restrictions allow the same syntax usage.

**Comment by aluong** [comment]
PR #2807
