### ISSUE TITLE
unsupported config type

### ISSUE THREAD

**Issue by namanan** [capitalone/cloud-custodian#2815]
So we have a policy that looks for cache-cluster resource types and reports the resources back. The policy runs just fine over c7n CLI without 'mode' defined but when its run with 'mode' defined it blows up with the following error message.

`$ custodian run -s . policy.yml`

```
name: policy-name
    description: Notify when elasticache-redis clusters have insecure configurations
    resource: cache-cluster
    filters:
       ......
```

When mode is defined, it blows up

```
name: policy-name
    description: Notify when elasticache-redis clusters have insecure configurations
    resource: cache-cluster
    mode:
        type: config-rule
        role: arn:aws:iam::<accountid>:role/<role>
   filters:
       ......
```

Here is the error message. May be I need to change the mode-type to something else, config-rule may not be the right choice but I couldn't find any help on other mode-types.

```
custodian.commands:ERROR Error while executing policy elasticache-redis-insecure, continuing
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/c7n/commands.py", line 227, in run
    policy()
  File "/usr/lib/python2.7/site-packages/c7n/policy.py", line 812, in __call__
    resources = mode.provision()
  File "/usr/lib/python2.7/site-packages/c7n/policy.py", line 511, in provision
    role=self.policy.options.assume_role)
  File "/usr/lib/python2.7/site-packages/c7n/mu.py", line 289, in publish
    if e.add(func):
  File "/usr/lib/python2.7/site-packages/c7n/mu.py", line 1444, in add
    params = self.get_rule_params(func)
  File "/usr/lib/python2.7/site-packages/c7n/mu.py", line 1408, in get_rule_params
    raise Exception("You may have attempted to deploy a config "
Exception: You may have attempted to deploy a config based lambda function with an unsupported config type. The most recent AWS config types are here: http://docs.aws.amazon.com/config/latest/developerguide/resource-config-reference.html.
```

Any insight would be appreciated.

Thank you

**Comment by kapilt** [comment]
aws config don't support elasticache, so custodian can't generate a config rule policy for that resource type. the link in the error message shows you what types are supported by aws config. alternatively you can do a periodic, or cloudtrail mode to have a lambda policy that targets them, or run a non lambda policy. 

see docs for more info https://capitalone.github.io/cloud-custodian/docs/policy/lambda.html

**Comment by namanan** [comment]
I see, so this is shortcoming from AWS side. I will dig some more into the alternatives and will close this then.

Thank you
