### ISSUE TITLE
cannot auto-tag-user s3 buckets with aws: tags on them

### ISSUE THREAD

**Issue by tjstansell** [capitalone/cloud-custodian#2834]
The s3 resource should use the resourcegrouptaggingapi instead of put_bucket_tagging, as the latter requires posting the full set of tags.  If you have an s3 bucket managed by cloudformation (which includes `aws:` tags), you get:
```Exception tagging bucket my-s3-bucket: An error occurred (InvalidTag) when calling the PutBucketTagging operation: System Tags cannot be removed by requester
Traceback (most recent call last):
File "/var/task/c7n/resources/s3.py", line 516, in modify_bucket_tags
Bucket=bucket['Name'], Tagging={'TagSet': tag_set})
File "/var/runtime/botocore/client.py", line 314, in _api_call
return self._make_api_call(operation_name, kwargs)
File "/var/runtime/botocore/client.py", line 612, in _make_api_call
raise error_class(parsed_response, operation_name)
ClientError: An error occurred (InvalidTag) when calling the PutBucketTagging operation: System Tags cannot be removed by requester
```

**Comment by camschaus** [comment]
It appears that commenting out the line containing:
`not t['Key'].startswith('aws') and`

in the modify_bucket_tags function allows put_bucket_tagging to update the S3 bucket tags that contain the `aws:` tags.  The put_bucket_tags API call will replace tags on the bucket with those in the tag set, which means it will attempt to remove any tags that exist on the bucket, but aren't in the tag set.  Including existing `aws:` tags in the tag set when modifying tags will allow the put_bucket_tagging to succeed.

I don't have enough background to understand why the `aws:` tags were excluded when updating the tag set with the existing bucket tags.

**Comment by tjstansell** [comment]
wow.  AWS must have fixed their backend to allow that... we used to get permission denied problems if you were trying to use put-bucket-tagging if any of the tags included an `aws:` tag, even if you weren't changing those tags.

**Comment by camschaus** [comment]
While it is good that their backend change now allows bucket tags to be updated in the presence of an unchanged `aws:` tag, I agree that your initial suggestion to use the resourcegrouptaggingapi would be the preferred approach.  

Let me know if you want me to put together a pull request with this change.

**Comment by kapilt** [comment]
would be great for a pull request, else we'll look at getting to it this week, nutshell its a breaking api change on put bucket tags.
