### ISSUE TITLE
RDS Policy errors when use Hours in mark-for-op

### ISSUE THREAD

**Issue by timbo256** [capitalone/cloud-custodian#2838]
Trying to run a policy against RDS resource with a mark-for-op using hours. It works if use days but gives the following error when use  hours parameter:

ubuntu@ip-10-186-101-166:~/custodian$ custodian run -d policies/ves-rds-started-public-facing-mark.yml -r eu-west-2 -s .
Traceback (most recent call last):
  File "/usr/local/bin/custodian", line 9, in <module>
    load_entry_point('c7n', 'console_scripts', 'custodian')()
  File "/home/ubuntu/custodian/cloud-custodian/c7n/cli.py", line 357, in main
    command(config)
  File "/home/ubuntu/custodian/cloud-custodian/c7n/commands.py", line 66, in _load_policies
    collection = policy_load(options, fp, validate=validate, vars=vars)
  File "/home/ubuntu/custodian/cloud-custodian/c7n/policy.py", line 73, in load
    errors[1], errors[0]))
Exception: Failed to validate on policy rds-started-public-facing-mark
 'rds' is not one of [u'aws.rds-snapshot', u'rds-snapshot']

Failed validating u'enum' in schema[114][u'allOf'][1][u'properties'][u'resource']:
    {u'enum': [u'aws.rds-snapshot', u'rds-snapshot']}

On instance[u'resource']:
    'rds'

Policy is as follows:

policies:
  - name: rds-started-public-facing-mark
    resource: rds
    description: |
        Mark any RDS instance created that is public facing
    mode:
       type: cloudtrail
       role: arn:aws:iam::{account_id}:role/Veolia-CloudCustodian
       function-prefix: dev-lbd-cc-
       events:
          - source: rds.amazonaws.com
            event: StartDBInstance
            ids: "requestParameters.dBInstanceIdentifier" 
#
    filters:
        - PubliclyAccessible: true
        - type: value
#
    actions:
       - type: tag
         tag: VES-RDS-PUBLICALY-ACCESSIBLE
         value: "RDS Instance is publicly accessible"
       - type: mark-for-op
         op: stop
         hours: 1
         tag: ves-stop-rds-instance-public-flag
       - type: notify
         template: vesmailtemplate.html
         priority_header: '1'
         subject: "Custodian - RDS Instance publicly accessible - marked for immediate stop [{{ account }} - {{ region }}]"
         action_desc: |
           "Marked for immediate stop"
         to:
          - resource-owner
         owner_absent_contact:
          - xxx
         transport:
          type: sqs
          queue: https://sqs.eu-west-1.amazonaws.com/{account_id}/CloudCustodianAlerts

**Comment by timbo256** [comment]
I believe that hours may not be part of the RDS schema - but not sure why it shouldn't be?

**Comment by kapilt** [comment]
they are..  i think there's something else going on with the policy.

```
$ custodian schema rds.filters
aws.rds:
  filters: [and, config-compliance, db-parameter, default-vpc, event, health-event,
    kms-alias, marked-for-op, metrics, network-location, not, offhour, onhour, or,
    security-group, subnet, tag-count, upgrade-available, value]
``

**Comment by kapilt** [comment]
copying and pasting and running shows that its valid, what version of custodian are you on? latest is 0.8.30
```
$ custodian validate -c foo.yml 
2018-09-05 18:44:45,692: custodian.commands:INFO Configuration valid: foo.yml
```

**Comment by timbo256** [comment]
Currently on 0.8.28.2

**Comment by timbo256** [comment]
Updated to 0.8.30.0 and it seems to work! Will close the issue.
