### ISSUE TITLE
Cloud Custodian AWS Filter

### ISSUE THREAD

**Issue by thisRalff** [capitalone/cloud-custodian#2853]
Can't find an answer for it specifically, but I am looking for a way to filter AWS Account Numbers.

We have a use case where we need to run a specific filter in a specific region in a specific account number as we run multiple AWS accounts.

I can always script it in, but I need to know if there is a way to do it across all filters provided by CC.

**Comment by kapilt** [comment]
ic. so you have a policy file with a set of policies, one of which should only run against a particular account, and your using something like c7n-org to run those policy files across accounts? The common solution here is to just have a separate file to run against the particular account, c7n-org supports tags on accounts in its config files to run a particular policy file/set against a class of accounts. Custodian doesn't really dictate on how users want to map policies to a given account. Wrt to region filtering, you can specify a `region` attribute on the policy to have it only execute in a particular region.

**Comment by thisRalff** [comment]
Well, crap. I build a compliance system around Tags that spans multiple accounts, and didn't think to add a simple tag that dictates the account. Such a simple solution. Thanks.
