### ISSUE TITLE
c7n package bug

### ISSUE THREAD

**Issue by bharath403** [capitalone/cloud-custodian#2862]
i installed custodian using virtualenv --python=python2 custodian and i see some changes are missing to c7n package. Any fix ?

 missing pending events in policy.py

@execution.register('ec2-instance-state')
class EC2InstanceState(LambdaMode):
    """a lambda policy that executes on ec2 instance state changes."""

    schema = utils.type_schema(
        'ec2-instance-state', rinherit=LambdaMode.schema,
        events={'type': 'array', 'items': {
            'enum': ['running', 'shutting-down',
                     'stopped', 'stopping', 'terminated']}})

**Comment by kapilt** [comment]
Not a bug, its called waiting for the next release, which will happen this week.

**Comment by bharath403** [comment]
Thanks for the clarification kapil !!!!
