### ISSUE TITLE
APP-ELB not filtering/actioning in Lambda

### ISSUE THREAD

**Issue by timbo256** [capitalone/cloud-custodian#2863]
I am having an issue when running an app-elb policy in Lambda. I am trying to invoke in Lambda on a 'CreateLoadBalancer' event and check that the LB is created in the right regions (valid regions in text file and eu-west-3 is not included in the file).
The policy works okay if run interactively, and deletes the LB, but does not seem to filter and action when run in Lambda. Could it be because the LB is still provisioning when the event is processed?
```
policies:
  - name: app-elb-started-non-eu-region
    resource: app-elb
    description: |
        Detect any app-elb instance launched outside expected regions
    mode:
        type: cloudtrail
        role: arn:aws:iam::{account_id}:role/CloudCustodian
        function-prefix: dev-lbd-cc-
        events:
          - source: "elasticloadbalancing.amazonaws.com"
            event: CreateLoadBalancer
            ids: "requestParameters.name"
        tags:
          AWS-Policy: "Region Check"
          Application: Custodian
#
    filters:
       - type: event
         key: "awsRegion"
         op: not-in
         value_from:
              url: s3://bucket/regions.txt
    actions:
       - delete
```

(Filter event type is changed to value when run interactively).

In Lambda the policy finds the resource okay, but does not seem to perform any other action.
```
09:16:17 START RequestId: 80c9773b-b66c-11e8-8dc3-cbce66a9cd4a Version: $LATEST
09:16:18 [INFO]	2018-09-12T09:16:18.281Z	80c9773b-b66c-11e8-8dc3-cbce66a9cd4a	Processing event { "account": "xxxxxxxxxxxx", "region": "eu-west-3", "detail": { "eventVersion": "1.04", "eventID": "f4aa7c8e-cad8-4b3f-956a-ff324e6a962b", "eventTime": "2018-09-12T09:15:35Z", "requestParameters": { "ipAddressType": "ipv4", "name": "dev-app-elb-paris-12", "subnetMap
09:16:18 [DEBUG]	2018-09-12T09:16:18.295Z	80c9773b-b66c-11e8-8dc3-cbce66a9cd4a	Disabling cache
09:16:18 [INFO]	2018-09-12T09:16:18.295Z	80c9773b-b66c-11e8-8dc3-cbce66a9cd4a	Found resource ids: [u'dev-app-elb-paris-12']
09:16:18 [INFO]	2018-09-12T09:16:18.647Z	80c9773b-b66c-11e8-8dc3-cbce66a9cd4a	Resources []
09:16:18 END RequestId: 80c9773b-b66c-11e8-8dc3-cbce66a9cd4a
09:16:18 REPORT RequestId: 80c9773b-b66c-11e8-8dc3-cbce66a9cd4a	Duration: 818.14 ms	Billed Duration: 900 ms Memory Size: 512 MB	Max Memory Used: 52 M
```

**Comment by kapilt** [comment]
your event filter for the region key isn't matching, it looks like it should be s/awsRegion/region per the log message

**Comment by timbo256** [comment]
Sorry - Don't understand the s/awsRegion/region

**Comment by timbo256** [comment]
Do you mean the filter should be using the name 'Region' rather than awsRegion?

**Comment by kapilt** [comment]
`region` the key has to match the key in the event. ie from the output you posted that would be
` "region": "eu-west-3"`

there's probably additional keys with the region in the `detail` dictionary but that output was ellided in the issue report.

**Comment by timbo256** [comment]
both region and awsRegion appear in the cloudwatch event

```
{
    "account": "xxxxxxxxxxxx",
    "region": "eu-west-3",
    "detail": {
        "eventVersion": "1.04",
        "eventID": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
        "eventTime": "2018-09-12T11:58:05Z",
        "requestParameters": {
            "ipAddressType": "ipv4",
            "name": "dev-app-elb-paris-17",
						
		.......
			
        "awsRegion": "eu-west-3",
        "eventName": "CreateLoadBalancer",
        "userIdentity": {
		
		........
		"resources": []
}
```

**Comment by kapilt** [comment]
right but to get to `awsRegion` you have to specify the full path to the key which is `detail.awsRegion`

**Comment by timbo256** [comment]
Tried that

**Comment by kapilt** [comment]
ah.. ic, its finding the resource ids but not able to find the resources. there's some oddness there on app elb vs elb. let me find an example for app elb

**Comment by timbo256** [comment]
Yeah - similar policy for elb works fine!
