### ISSUE TITLE
custom action not being deployed to AWS

### ISSUE THREAD

**Issue by eamonnfaherty** [capitalone/cloud-custodian#2872]
Hi,

I have created a custom action as a python module which is installed into my virtualenv via python setup.py install. 

I am referencing it within a policy and all seems to work: 
- custodian schema shows the action available 
- custodian validate shows my policy is correct.

When I deploy my policy to AWS the module for the action is not deployed with the lambda and when the lambda executes custodian says the action is not available. 

Do you have any ideas how I can bundle my library?  I have checked the docs and looked the azure and gcp examples but cannot see anything that I may be missing.

**Comment by eamonnfaherty** [comment]
Found the solution! 

Here it is for others:

policies:
- name: tag-compliance-3
  resource: ec2
  description: |
    Schedule a resource that does not meet tag compliance policies
    to be stopped
  mode:
    type: cloudtrail
    events:
    - RunInstances
    packages:
    - my_package
  filters:
    - "tag:compliant": absent
  actions:
    - type: my-action

**Comment by srikanthcs** [comment]
Hey @eamonnfaherty , can you give me some info on how you setup custom-action into custodian runtime ?
