### ISSUE TITLE
initial install issue & policy run issue

### ISSUE THREAD

**Issue by rvandy** [capitalone/cloud-custodian#29]
Thank you for this wonderful tool.  

Perhaps there may be some ideas here for additional developer install instructions - I would be happy to contribute if helpful. 

The below steps show my efforts at installing Cloud Custodian.   Eventually, I successfully installed Cloud Custodian and ran tests/coverage.  However - I ran into a traceback issue in running a custom policy.    Any insight on where my environment is invalid would be greatly appreciated.  

Using a blank Amazon linux distro,  referencing the following install doc: 
http://www.capitalone.io/cloud-custodian/quickstart/developer.html

I configured this new EC2 to run cloud custodian via CLI as follows:

Spin up Amazon linux distro EC2 nano instance:  i-xxxxxxxx
ssh into this new instance
% yum update
% yum install gcc
% yum install git
% yum install install python python-dev python-pip python-virtualdev
% yum install emacs
% git clone https://github.com/capitalone/cloud-custodian.git
% make install 

(have make output if needed)

% make test
./bin/nosetests -s -v --with-timer tests
make: ./bin/nosetests: Command not found
make: *** [test] Error 127

Looking @ the makefile -  ran this additional command

% make develop

then - tried the following:

% make test

Progressed further - but my tests failed.

Performed another:

% make install

and looking at the output, noticed:

You are using pip version 6.0.8, however version 8.1.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command

so - performed the following:

% pip install --upgrade pip
% pip install -r requirements.txt
% pip install -r requirements-dev.txt 
% make test -> failed.

Looking at the output, noticed that is was looking for a default AWS region.

Hence - ran:

% aws configure  // inserted Access Keys and default region

% make test -> Successful!
% make coverage  -> Successful!

Happy with my progress so far - copied the following default policy from the documentation:

- name: ec2-old-instances
  resource: ec2
  comment: |
    Report running instances older than 60 days
  query:
    - instance-state-name: running
  filters:
    - type: instance-age
      days: 60

name: policy.yml

Ran the following command:

% ./bin/custodian run --dryrun -c policy.yml  -s out

which produced quite a bit of verbose output.   Of the relevant pieces, I believe, are the following:

Traceback (most recent call last):
  File "./bin/custodian", line 9, in <module>
    load_entry_point('c7n==0.8.3', 'console_scripts', 'custodian')()
  File "/home/ec2-user/cloud-custodian/c7n/cli.py", line 105, in main
    config = policy.load(options, options.config)
  File "/home/ec2-user/cloud-custodian/c7n/policy.py", line 45, in load
    raise errors[0]
jsonschema.exceptions.ValidationError: [{'comment': 'Report running instances older than 60 days\n', 'query': [{'instance-state-name': 'running'}], 'resource': 'ec2', 'name': 'ec2-old-instances', 'filters': [{'type': 'instance-age', 'days': 60}]}] is not of type 'object'

Failed validating 'type' in schema:
    {'$schema': 'http://json-schema.org/schema#',
     'additionalProperties': False,

Now - stuck on diagnosing this "object" error.    

Any suggestions?

[make output attached]
[cloud_custodian_output.txt](https://github.com/capitalone/cloud-custodian/files/241418/cloud_custodian_output.txt)

**Comment by kapilt** [comment]
Thanks for trying things out, there's some rough spots in the docs that need addressing. wrt to the error the formatting on the policy looks off, which is likely triggering the schema validation error,  but its hard to see in this issue without using a prefix block,  yaml is white space sensitive.

here's an example of a working policy 

```
policies:
  - name: ec2-old-instances
    resource: ec2
    comment: |
      Report running instances older than 60 days                                                                                                                                 
    query:
      - instance-state-name: running
    filters:
      - type: instance-age
        days: 60
```
and running it on an account

```
$ custodian run -c config.yml -v  -s out --dryrun
custodian run -c config.yml -v  -s out
2016-04-29 06:51:18,670: custodian.output:INFO Storing output with <DirectoryOutput to dir:out/ec2-old-instances>
2016-04-29 06:51:18,670: custodian.policy:INFO Running policy ec2-old-instances
2016-04-29 06:51:18,670: custodian.resources.ec2:INFO Querying ec2 instances with [{'Values': ['running'], 'Name': 'instance-state-name'}]
2016-04-29 06:51:19,915: custodian.resources.ec2:DEBUG Found 46 instances on 46 reservations
2016-04-29 06:51:19,925: custodian.resources.ec2:INFO Filtered from 46 to 5 ec2
2016-04-29 06:51:19,927: custodian.policy:INFO policy: ec2-old-instances resource:ec2 has count:5 time:1.26
2016-04-29 06:51:19,927: custodian.output:DEBUG metric:ResourceCount Count:5 policy:ec2-old-instances restype:ec2 scope:policy
2016-04-29 06:52:16,282: custodian.policy:DEBUG dryrun: skipping actions
```

Re other items reported here.

 - [ ] reference make develop in developer docs
 - [ ] unit tests or make tests should set their default region it not already set

**Comment by kapilt** [comment]
i think we tackled the doc issue and the unit tests defaulting to region (when executed via make) in #32 and #33, and also the policy example here in the issues.

Re the initial install we can furnish additional instructions there for other distros (contrib welcome), but i think maybe the other option is just shipping a docker image to the public registry, which we use internally for our ci (via drone).
