### ISSUE TITLE
ASG propagate-tags filter typo - only works as proGagate-tags

### ISSUE THREAD

**Issue by vszopa** [capitalone/cloud-custodian#2925]
custodian version - 0.8.30.0

Typo: proGagated-tags vs proPagated-tags

It looks like the ASG propagated-tags filter actually requires the spelling "progagated-tags." (p => g)
This is shown in the output of "custodian schema asg", but not the documentation or examples.
The incorrect spelling does, happily, seem to work.

Thank you!

### POLICY
======
<pre>
policies:
  - name: asg-delete-if-nonpropagating-tags
    resource: asg
    description: |
       if required tags not set to propagate, delete ASG and notify
    filters:
      - type: propagated-tags
        keys: ["my-special-pony-key", "application-group"]
        match: false
        propagate: true
    actions:
      - *slack
      - type: delete
</pre>

### ERROR
=====
<pre>
Traceback (most recent call last):
  File "/usr/local/bin/custodian", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/site-packages/c7n/cli.py", line 357, in main
    command(config)
  File "/usr/local/lib/python3.7/site-packages/c7n/commands.py", line 66, in _load_policies
    collection = policy_load(options, fp, validate=validate, vars=vars)
  File "/usr/local/lib/python3.7/site-packages/c7n/policy.py", line 75, in load
    errors[1], errors[0]))
Exception: Failed to validate on policy asg-delete-if-nonpropagating-tags 
 'sandbox-nonpropagating-tag-filters' is not valid under any of the given schemas

Failed validating 'anyOf' in schema[17]['allOf'][1]['properties']['filters']['items']:
    {'anyOf': [{'$ref': '#/definitions/resources/aws.asg/filters/capacity-delta'},
               {'$ref': '#/definitions/resources/aws.asg/filters/config-compliance'},
               {'$ref': '#/definitions/resources/aws.asg/filters/event'},
               {'$ref': '#/definitions/resources/aws.asg/filters/image'},
               {'$ref': '#/definitions/resources/aws.asg/filters/image-age'},
               {'$ref': '#/definitions/resources/aws.asg/filters/invalid'},
               {'$ref': '#/definitions/resources/aws.asg/filters/launch-config'},
               {'$ref': '#/definitions/resources/aws.asg/filters/marked-for-op'},
               {'$ref': '#/definitions/resources/aws.asg/filters/metrics'},
               {'$ref': '#/definitions/resources/aws.asg/filters/network-location'},
               {'$ref': '#/definitions/resources/aws.asg/filters/not-encrypted'},
               {'$ref': '#/definitions/resources/aws.asg/filters/offhour'},
               {'$ref': '#/definitions/resources/aws.asg/filters/onhour'},
               {'$ref': '#/definitions/resources/aws.asg/filters/progagated-tags'},
               {'$ref': '#/definitions/resources/aws.asg/filters/security-group'},
               {'$ref': '#/definitions/resources/aws.asg/filters/subnet'},
               {'$ref': '#/definitions/resources/aws.asg/filters/tag-count'},
               {'$ref': '#/definitions/resources/aws.asg/filters/valid'},
               {'$ref': '#/definitions/resources/aws.asg/filters/value'},
               {'$ref': '#/definitions/resources/aws.asg/filters/vpc-id'},
               {'$ref': '#/definitions/filters/valuekv'},
               {'enum': ['value',
                         'or',
                         'and',
                         'not',
                         'event',
                         'offhour',
                         'onhour',
                         'tag-count',
                         'marked-for-op',
                         'metrics',
                         'config-compliance',
                         'security-group',
                         'subnet',
                         'network-location',
                         'launch-config',
                         'valid',
                         'invalid',
                         'not-encrypted',
                         'image-age',
                         'image',
                         'vpc-id',
                         'progagated-tags',
                         'capacity-delta']}]}

On instance['filters'][1]:
    'sandbox-nonpropagating-tag-filters'
</pre>

Note "progagated":
<pre>
               {'$ref': '#/definitions/resources/aws.asg/filters/progagated-tags'},
</pre>

### CHANGE AND TEST
===============
Update this:
    filters:
      - type: propagated-tags

To this:
    filters:
      - type: progagated-tags

### TEST RESULTS
============
<pre>
RUNNING IN us-west-2...
2018-09-25 15:09:11,435: custodian.policy:INFO policy: asg-delete-if-nonpropagating-tags resource:asg region:us-west-2 count:13 time:0.88

RUNNING IN us-east-1...
2018-09-25 15:09:13,147: custodian.policy:INFO policy: asg-delete-if-nonpropagating-tags resource:asg region:us-east-1 count:2 time:0.95
</pre>

### MATCHES IN cloud-custodian SOURCE
==============================
<pre>
$ git grep -i proGagated-tags
c7n/resources/asg.py:@filters.register('progagated-tags')
c7n/resources/asg.py:        'progagated-tags',
docs/source/policy/resources/asg.rst:``progagated-tags``
tests/test_asg.py:                    {"type": "progagated-tags", "keys": ["Tag01", "Tag02", "Tag03"]}
tests/test_asg.py:                        "type": "progagated-tags",
tests/test_asg.py:                        "type": "progagated-tags",
tests/test_asg.py:                        "type": "progagated-tags",
"P"
$ git grep -i proPagated-tags
c7n/resources/asg.py:@filters.register('propagated-tags')
c7n/resources/asg.py:              - name: asg-non-propagated-tags
c7n/resources/asg.py:                  - type: propagated-tags
c7n/resources/asg.py:        aliases=('propagated-tags',),
tests/test_asg.py:                    {"type": "propagated-tags", "keys": ["Tag01", "Tag02", "Tag03"]}
$ 
</pre>
==============================

**Comment by kapilt** [comment]
Thanks for the awesome bug report

**Comment by kapilt** [comment]
we'll need to keep the misspelled name for compatibility but we should add in the correct spelling as well.

**Comment by thisisshi** [comment]
fixed via https://github.com/capitalone/cloud-custodian/pull/2784 can you pull the latest version of custodian? I'm seeing it show up correctly in the schema

**Comment by vszopa** [comment]
Looks fixed for me - both correct and misspelled filter names work in 0.8.31.2. Thanks a lot!
