### ISSUE TITLE
EC2 Filter - IAMInstanceProfile: absent, throwing error

### ISSUE THREAD

**Issue by mukavik** [capitalone/cloud-custodian#2937]
EC2 Filter **IAMInstanceProfile: absent** is throwing following error:
_ClientError: An error occurred (InvalidParameterValue) when calling the DescribeIamInstanceProfileAssociations operation: Invalid value 'null/empty' for 'filter'. Invalid filter - one of more name/value pair was incomplete._ 

I am using version 0.8.31.0 and checked on version 8.28.0 also.
Below is the sample policy i am using:
'policies:
  - name: ec2-role-check
    resource: ec2
    description: |
        Set default Instance profile role
    mode:
      type: periodic
      role: arn:aws:iam::{account_id}:role/CloudCustodianExecutionRole
      schedule: "rate(5 minutes)"
      execution-options:
        metrics_enabled: false
      memory: 128
    filters:
          - IamInstanceProfile: absent
    actions:
      - type: set-instance-profile
        name: default_iaminstancerole'

**Comment by mukavik** [comment]
@kapilt I would appreciate if you can take a look at this. We are dependent on this to enable some security functionality. Appreciate your help.

**Comment by thisisshi** [comment]
@mukavik thanks for the bug report, I've been able to reproduce this on my side, looks like the error is occurring when trying to set the instance profile on an instance.

full trace:
```
Traceback (most recent call last):
  File "/cloud-custodian/c7n/commands.py", line 232, in run
    policy()
  File "/cloud-custodian/c7n/policy.py", line 872, in __call__
    resources = mode.run()
  File "/cloud-custodian/c7n/policy.py", line 273, in run
    results = a.process(resources)
  File "/cloud-custodian/c7n/resources/ec2.py", line 1382, in process
    {'Name': 'state', 'Values': ['associating', 'associated']}]
  File "/cloud-custodian/lib/python3.6/site-packages/botocore/client.py", line 314, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/cloud-custodian/lib/python3.6/site-packages/botocore/client.py", line 612, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (InvalidParameterValue) when calling the DescribeIamInstanceProfileAssociations operation: Invalid value 'null/empty' for 'filter'. Invalid filter - one of more name/value pair was incomplete
```

**Comment by mukavik** [comment]
@thisisshi @kapilt appreciate the help. I just did a pip install and also tried cloning ad running setup.py but still see the error. Do i need to do anything else?

**Comment by thisisshi** [comment]
@mukavik follow the steps here: http://capitalone.github.io/cloud-custodian/docs/developer/installing.html

**Comment by mukavik** [comment]
@thisisshi Oh i see. Any idea when this will be GA? i mean available via pip install because our deployment pipeline uses that.

**Comment by mukavik** [comment]
@thisisshi any update on the bug fix availability through pip install?

**Comment by mukavik** [comment]
@thisisshi appreciate that.
