### ISSUE TITLE
C7N mu.py doesent honor function-prefix on describe_rule

### ISSUE THREAD

**Issue by jacob-kinzer** [capitalone/cloud-custodian#2949]
Currently it looks like _mu.CloudWatchEventSource.get()_ doesent end up honoring the _function-prefix_ parameter when CloudWatchEventSource is instantiated. 

Currently mu.PolicyLambda.get_events() does not pass in a prefix variable and therefore the default of _custodian-_ is used in the describe_rule calls, even if you specify your own prefix in your policy files.

![image](https://user-images.githubusercontent.com/40577885/46300140-92810600-c568-11e8-9561-7a7f5acb117e.png)

Passing in the prefix should allow the call to work as intended:
![image](https://user-images.githubusercontent.com/40577885/46300191-b04e6b00-c568-11e8-8819-a7171df2de2a.png)

Sidenote: the put_rule call uses the function's name, which already has the correct prefix applied, so that works as intended. Its just the describe before hand that is failing.

**Comment by kapilt** [comment]
yeah, i noticed that, it results a bad diff check when updating, which means updates on every execution which is suboptimal and a bug, but from a functional perspective its okay (policy lambda deploys and executes).
