### ISSUE TITLE
Cloud-Custodian resource:ec2 send mail region and account-name variable problem

### ISSUE THREAD

**Issue by umitseremet** [capitalone/cloud-custodian#2975]
I have prepared a Cloud-CustodianPolicy which detects new created EC2s and send emails. The structure works but I could not write account-name and region information into nor subject or body of mail. While yaml can understand in role part as {account_id}, it can not understand inside of mail related part. Is there a way to use these parametric variables inside policy?

yaml file;

     ...
      role: arn:aws:iam::{account_id}:role/administrator", 
     ...
    
      actions:
          - type: notify
            template: default
            priority_header: '2'
            subject: "Huge Sized Type EC2 has been PoweredON accountID:{account_id} {account_name}-{region}"

mail subject in the mail sent;
 
> subject: Huge Sized Type EC2 has been PoweredON accountID:{account_id} {account_name}-{region}

**Comment by umitseremet** [comment]
The format below has worked in my config

subject: "Huge Sized Type EC2 has been PoweredON in {{account}} on {{region}}"

**Comment by davegonzales2004** [comment]
Hi @umitseremet ,

I'm having this same problem and I went ahead and added your above recommendation, but I'm still not getting the account to show up in the subject of the email. Did you have to make any changes to the email template "default.html.j2"?
`actions:
      - type: notify
        template: default.html
        priority_header: 1
        subject: "Root User Login Detected! - {{ account }} - {{ region }}"
        violation_desc: "A user has logged into the AWS Console with the Root user:"
        action_desc: |
            Please investigate and notify your team that root login is not allowed.
        to:
           - admin@domain.com`

**Comment by davegonzales2004** [comment]
@umitseremet ,

Nevermind, I got it to work using {{ account_id }}:

```subject: "Root User Login Detected! - AWS Account: {{ account_id }} - Region: {{ region }}"```

**Comment by umitseremet** [comment]
Please remove "-" and do not use special character and try again

**Comment by davegonzales2004** [comment]
I was able to get this to work using "-". 
The key for me was using {{ account_id }} instead of {{ account }}

**Comment by ndesai15** [comment]
@umitseremet & @davegonzales2004 do we have a list of such variables that we can use in custodian policy? I don't see in main documentation of cloud custodian.

**Comment by ahmadzaikk** [comment]
@davegonzales2004  were are able to add the account name or ID into email body?
