### ISSUE TITLE
Custodian in container cannot find policies

### ISSUE THREAD

**Issue by jdogg89** [capitalone/cloud-custodian#2989]
When running in a container, custodian can't seem to read policy files:

custodian.commands:WARNING Empty policy file(s).  Nothing to do.

**Comment by thisisshi** [comment]
@jdogg89 are you mounting your policies in the container correctly?

**Comment by jdogg89** [comment]
@thisisshi I worked through the issue. I've been building my own container image with azure integration, thanks for the reply, I will close the issue.
