### ISSUE TITLE
mugc.py does not have the ability to act on all regions

### ISSUE THREAD

**Issue by thomasbiddle** [capitalone/cloud-custodian#2994]
Cloud-Custodian has the ability to use `-r all` and act on all regions.

mugc.py can only act on a specific region, eg: `-r us-west-1` - And also does not have the ability to take in multiple regions, eg: `-r us-west-1 -r us-east-1` as Cloud Custodian does.

**Comment by kapilt** [comment]
mugc now supports specifying region multiple times, or specifying `all` for targeting all regions.

**Comment by leongwq** [comment]
Getting `botocore.exceptions.NoRegionError: You must specify a region.` when using this command `python3 mugc.py --region all -c emptypolicy.yml --dryrun`
