### ISSUE TITLE
Azure - Configurable Azure Function Service Principal Context

### ISSUE THREAD

**Issue by aluong** [capitalone/cloud-custodian#2996]
Currently, the service principal that is running Custodian gets its information copied into the Function that gets deployed. 

We would like to propose adding a parameter to Custodian that allowed us to specify an auth file with the configuration of another service principal when we are running an Azure Function mode policy. In turn, when the function gets deployed it will use this other sp as its running context. This way we can assign a different set of roles and access control. 

Consequently, users can two different set of roles:

-  **"deployment and infrastructure"** service principal used for `custodian run`
- **"functions"** service principal running in Azure Functions

**Comment by kapilt** [comment]
would that just be an option on the execution mode to specify a service principal auth file?

**Comment by aluong** [comment]
If we put specific auth information in the execution mode, a potential problem would be the need for duplicate policy files in order to specify different authentication parameters.

Do you think it would be better for c7n-org to handle this and we can specify information in it's configuration file?

Also, currently the assumption is that wherever the Function resides is the subscription it affects. This option opens the door for having a single subscription that holds Custodian functions that manage other subscriptions.
