### ISSUE TITLE
ParameterValidation error - IAM

### ISSUE THREAD

**Issue by mukavik** [capitalone/cloud-custodian#2999]
Getting errors - ParamValidationError: Parameter validation failed:
Invalid length for parameter PolicyArn, value: 8, valid range: 20-inf. 
I am trying to trigger a C7N policy on CloudTrail Event CreatePolicy. I see there is no shortcut for the event and thus doing this:
events:
    - source: iam.amazonaws.com
      event: CreatePolicy
      ids: "requestParameters.policyName"

Am i missing something or is it C7N error?

**Comment by kapilt** [comment]
there's not enough context here to understand what the issue is, whats the policy and what's the full traceback.

**Comment by kapilt** [comment]
it looks like the api is expecting an arn, and your sending it the policy name.

**Comment by mukavik** [comment]
**Here is the policy:**
policies:
  - name: IAM-Policy-Allow-All-Check
    description: |
      Check if IAM policy resource(s) have allow-all IAM policy statement block
    resource: iam-policy
    mode:
      role: arn:aws:iam::{account_id}:role/CloudCustodianExecutionRole
      type: cloudtrail
      events:
        - source: iam.amazonaws.com
          event: CreatePolicy
          ids: "requestParameters.policyName"
    filters:
      - type: value
        key: PolicyName
        value: AdministratorAccess
        op: ne
      - type: has-allow-all
    actions:
      - type: delete
**Traceback:**
Parameter validation failed:
Invalid length for parameter PolicyArn, value: 15, valid range: 20-inf: ParamValidationError
Traceback (most recent call last):
File "/var/task/custodian_policy.py", line 4, in run
return handler.dispatch_event(event, context)
File "/var/task/c7n/handler.py", line 91, in dispatch_event
p.push(event, context)
File "/var/task/c7n/policy.py", line 834, in push
return mode.run(event, lambda_ctx)
File "/var/task/c7n/policy.py", line 442, in run
resources = self.resolve_resources(event)
File "/var/task/c7n/policy.py", line 419, in resolve_resources
resources = self.policy.resource_manager.get_resources(resource_ids)
File "/var/task/c7n/query.py", line 474, in get_resources
resources = self.source.get_resources(ids)
File "/var/task/c7n/resources/iam.py", line 164, in get_resources
results.append(client.get_policy(PolicyArn=r)['Policy'])
File "/var/runtime/botocore/client.py", line 314, in _api_call
return self._make_api_call(operation_name, kwargs)
File "/var/runtime/botocore/client.py", line 586, in _make_api_call
api_params, operation_model, context=request_context)
File "/var/runtime/botocore/client.py", line 621, in _convert_to_request_dict
api_params, operation_model)
File "/var/runtime/botocore/validate.py", line 291, in serialize_to_request
raise ParamValidationError(report=report.generate_report())
ParamValidationError: Parameter validation failed:
Invalid length for parameter PolicyArn, value: 15, valid range: 20-inf

I tried using _ids: "requestParameters.arn_ instead but then the trigger does not work. 
**Traceback:**
[INFO]	2018-10-17T19:39:01.743Z	4bb0d8c6-d244-11e8-9b88-a96c7c9d049c	Found resource ids: []
[WARNING]	2018-10-17T19:39:01.743Z	4bb0d8c6-d244-11e8-9b88-a96c7c9d049c	Could not find resource ids

**Comment by kapilt** [comment]
arn is in the responseElements not the requestParameters.

**Comment by kapilt** [comment]
you have to look at the event in the log and specify the correct path to the arn for the ids expression. the one you've done here is not correct, the arn is contained within a policy mapping in the response.

**Comment by mukavik** [comment]
It is working now. Thanks for the help
