### ISSUE TITLE
Use Event Bus as target in CloudWatch event Rule

### ISSUE THREAD

**Issue by nagarajatantry** [capitalone/cloud-custodian#3002]
I would like to know if Cloud Custodian supports setting up of Event Bus as target instead of using lambda. 
Use case: I want some specific cloud-watch event  from 1000s of accounts to be routed to few central account which then triggers a chain of different process.

**Comment by kapilt** [comment]
custodian has some support for it, but it assumes you've setup the event bus out of band. you also need to specify a `member-role` with appropriate trust relationship for the assumption back into the target accounts.

**Comment by nagarajatantry** [comment]
Cool thanks..@kapilt 
I will check it out..
