### ISSUE TITLE
c7n_mailer DataDog and Slack Integration for Azure

### ISSUE THREAD

**Issue by jdogg89** [capitalone/cloud-custodian#3005]
Currently the c7n_mailer documentation only lists notifications being able to be sent via email and a sendgrid account. It would be great to have the ability to notify our platform team via slack or have metrics sent to DataDog for additional alerting and monitoring. Functionality currently exists for AWS and it would be great to utilize this for Azure.

**Comment by stefangordon** [comment]
Slack integration tracked in #2633
