### ISSUE TITLE
email templates unrecognized

### ISSUE THREAD

**Issue by jdogg89** [capitalone/cloud-custodian#3010]
Email templates cannot be recognized, even after clean installs going off of default examples in mailer setup. I am setting up with sendgrid and Azure, and have re-validated my mailer.yml file and testemailnotify.yml that should return the resource groups in my subscription.

Output:
2018-10-19 14:48:51,308 - custodian-mailer - ERROR - Invalid template reference default.j2
default.j2
Request body:
{"errors":[{"message":"The content value must be a string at least one character in length.","field":"content.0.value","help":"http://sendgrid.com/docs/API_Reference/Web_API_v3/Mail/errors.html#message.content.value"}]}

Request headers:
Server: nginx
Date: Fri, 19 Oct 2018 19:48:51 GMT
Content-Type: application/json
Content-Length: 219
Connection: close
Access-Control-Allow-Origin: https://sendgrid.api-docs.io
Access-Control-Allow-Methods: POST
Access-Control-Allow-Headers: Authorization, Content-Type, On-behalf-of, x-sg-elas-acl
Access-Control-Max-Age: 600
X-No-CORS-Reason: https://sendgrid.com/docs/Classroom/Basics/API/cors.html

**Comment by kapilt** [comment]
whats the policy look like that was triggering the notification here? (sanitized on subscription id/private details pls)

**Comment by kapilt** [comment]
@capitalone/c7n-azure-write-team any ideas ^

**Comment by jdogg89** [comment]
It appears that when running the pip packages c7n_azure and c7n_mailer, this works fine. When 'c7n' is installed in addition to this, the template issues appear.

**Comment by stefangordon** [comment]
While #2955 was suspicious it does not seem to have touched the actual template deployment (just removed similarly named ARM template utilities).

You are possibly the only person actually running this so far beyond some of the testing we did while coding the first pass implementation in mailer for Azure, so likely lots of issues to work through.  I'm working on prioritizing them and reproducing them now.

**Comment by logachev** [comment]
@jdogg89 just to unblock you. The issue is that when you install c7n-mailer via pip, it doesn't include msg-templates folder (default.j2 not found).
You can manually copy-paste this folder next to the c7n_mailer folder (with the current behavior it should reside in `python3.6/site-packages/msg-templates`

**Comment by logachev** [comment]
Unfortunately, I don't know. 
@kapilt please let me know when you want to publish new pip package for mailer. I sent a PR with slack integration for Azure, would be great to include it in new package.
