### ISSUE TITLE
azure - check tests aren't writing files into working tree

### ISSUE THREAD

**Issue by kapilt** [capitalone/cloud-custodian#3074]
There's been a few drone failures on merges when going to publish docs due to what appears to be a new test file introduced during tests execution. specifically

```
error: The following untracked working tree files would be overwritten by checkout:
	tools/c7n_azure/tests/cassettes/VMTest.test_validate_vm_schemas.yaml
```

**Comment by kapilt** [comment]
link to one of the ci failures on master https://ci.cloudcustodian.io/capitalone/cloud-custodian/7624

**Comment by kapilt** [comment]
master commits that failed ci due to this issue.

https://ci.cloudcustodian.io/capitalone/cloud-custodian/7650
https://ci.cloudcustodian.io/capitalone/cloud-custodian/7628
https://ci.cloudcustodian.io/capitalone/cloud-custodian/7624
https://ci.cloudcustodian.io/capitalone/cloud-custodian/7612

**Comment by stefangordon** [comment]
Note on gh-pages branch
https://github.com/capitalone/cloud-custodian/tree/gh-pages/tools/c7n_azure/tests/cassettes

**Comment by stefangordon** [comment]
I think the root cause may be the SDK doing some sort of background polling for long running compute operations.  That needs to be resolved as well as some general updates to how VCRPY works (which by itself wouldn't stop the build break, but would prevent new files being created)

**Comment by stefangordon** [comment]
Looks like this is the standard polling config in all SDK methods

```
        if polling is True: polling_method = ARMPolling(lro_delay, **operation_config)
        elif polling is False: polling_method = NoPolling()
```

Patching ARMPolling() to return NoPolling() might be a nice solution, testing it now.

**Comment by stefangordon** [comment]
I think this has worked....
