### ISSUE TITLE
Azure - Policy Feature Request - Scaling App Service Plans for Off-hours

### ISSUE THREAD

**Issue by jdogg89** [capitalone/cloud-custodian#3115]
### Requested Feature: 
The ability to scale an app service plan down to free tier during off hours, and back to the desired tier during on hours. Since App Service Plans cannot be turned off like a traditional virtual machine during off hours, the ability to scale them down to free tier in lower environments would result in large cost savings for any organization.

### Outcome
- Reduced cost as service plan pricing would be changed for duration of off time window
- Ability to more tightly control resource consumption for organizations who choose to go with managed services in Azure

**Comment by stefangordon** [comment]
So I think this would be a new action on the App Service Plan resource for setting the SKU.  

If setting the SKU on that resource is generic to other resource types we should look at making the action available wherever feasible.

Agreed this is useful, will see if we can get it on the schedule soon.

**Comment by stefangordon** [comment]
@jdogg89 https://github.com/capitalone/cloud-custodian/pull/3130  Should get this in today or tomorrow.
