### ISSUE TITLE
'AzureFunctionMode' is not defined

### ISSUE THREAD

**Issue by spacekitty76** [capitalone/cloud-custodian#3158]
Hello, I'm trying to go through the README to run c7n_mailer on Azure and I am having some issues getting it to recognize that the c7n_azure package is installed.  Perhaps I'm doing something wrong, if anyone could take a minute to help me out it would be much appreciated!

What I'm doing:
$ virtualenv c7n_mailer
$ source c7n_mailer/bin/activate
$ cd tools/c7n_mailer
$ pip install -r requirements.txt
$ python setup.py develop

Then to install azure:
$ cd ..
$ pip install c7n_azure

Then I run it:
$ c7n-mailer --config mailer.yml --update-lambda

I keep getting this error:
```
Traceback (most recent call last):
  File "/Users/xxx/cloud-custodian/c7n_mailer/bin/c7n-mailer", line 11, in <module>
    load_entry_point('c7n-mailer', 'console_scripts', 'c7n-mailer')()
  File "/Users/xxx/cloud-custodian/tools/c7n_mailer/c7n_mailer/cli.py", line 209, in main
    azure_deploy.provision(mailer_config)
  File "/Users/xxx/cloud-custodian/tools/c7n_mailer/c7n_mailer/azure/deploy.py", line 79, in provision
    service_plan = AzureFunctionMode.extract_properties(function_properties,
NameError: global name 'AzureFunctionMode' is not defined
```

Is there a particular directory I'm supposed to run it from?  I've tried the cloud_custodian and the tools directory with the same issue.  Any ideas?

Thanks!

**Comment by kapilt** [comment]
@stefangordon @aluong @erwelch @logachev any ideas ^

**Comment by kapilt** [comment]
@logachev it looks like he's running into the importerror exception catch in c7n_mailer/azure/deploy  and then hitting the runtime error later on.

https://github.com/capitalone/cloud-custodian/blob/master/tools/c7n_mailer/c7n_mailer/azure/deploy.py#L29

@spacekitty76 it does look like an install error on the azure libraries

**Comment by jdogg89** [comment]
Are you installing from source? the pypi packaged never worked for me so I download from source every time I build an image or test locally. Also do you get the same results running a python3 virtual environment? I was having issues a while ago and those two pieces did the trick for me to run mailer.

**Comment by spacekitty76** [comment]
Hey guys, thanks for getting back to me. I ended up getting it to work with @jdogg89's tip.  Installing from source and specifying python3 in virtualenv.

Thanks much!
