### ISSUE TITLE
account: enable cloudtrail action

### ISSUE THREAD

**Issue by kapilt** [capitalone/cloud-custodian#339]

**Comment by skurfer** [comment]
Enable = start logging?

**Comment by skurfer** [comment]
Comment from @kapilt on a dead pull request:

> yeah, my bad, it was intended to put the trail and recorder in place if it had been deleted, or to enable if it had been disabled.

I’m revisiting this. If we need to put one in place, we need to name it. We also need to create (and name) an S3 bucket for it. Any preferences for those names?

**Comment by kapilt** [comment]
I'd defer to policy for any resource details, most folks set this up during account creation, we're effectively doing this so we can have realtime remediation if folks disable or delete an extant trail somehow.
