### ISSUE TITLE
count of resources as a value_type option on value filter

### ISSUE THREAD

**Issue by kapilt** [capitalone/cloud-custodian#342]

**Comment by nyetsche** [comment]
What's the proposal here? I'm possible interested, in the sense of a rule like "if tag==FOO && instances > 10, bring down to 10", but I'm having trouble thinking of what a great action would be.

**Comment by kapilt** [comment]
for alot of our policies it would be like if condition and collection size < x then notify a human. our use cases are mostly around substrates like network and identity to ensure ha. but yes the intent is that a filter on collection size would be combined with 'or' and 'and' with other filters. note we do already have a size value_type.. so you could do if asg has more than 100 instances, resize and notify today.

**Comment by scotwk** [comment]
@kapilt 

I was going to pick this one up but didn't fully understand how to implement it.  If someone specified the following:

```
            'type': 'value',
            'value_type': 'count',
            'key': '?',
            'value': '...'
            'op': '...'
```

I assume that `value` will just be a comparison (using `op`, if supplied) against the count of resources.

But what is the `key`?  Normally that pulls info from the instance (i.e. naming a tag, key value, or jmespath).  In the case of resources, what info is it pulling from an instance?  Or is it just returning the count of resources (in which case `key` would be ignored)?
