### ISSUE TITLE
detect unused iam instance profile

### ISSUE THREAD

**Issue by kapilt** [capitalone/cloud-custodian#359]
bonus to remove it.

**Comment by andrewalexander** [comment]
Looks like the Access Advisor is what we would want here, but from what I can gather, they haven't added that to any of their exposed APIs yet. You can look at the console and inspect the web traffic to see that it is hitting `GetServiceLastAccessed` and other related calls, but Amazon has said on some [forums](https://blogs.aws.amazon.com/security/post/Tx280RX2WH6WUD7/Remove-Unnecessary-Permissions-in-Your-IAM-Policies-by-Using-Service-Last-Access) that they were investigating adding the APIs. 

Depending on what we are trying to accomplish with this, I don't think that's actually a problem. We could search through the CloudTrail/API logs for each instance profile and see when they were last used. Unsure if that's what we really what the goal was here, but if that check is put in a daily policy, it probably wouldn't be too terrible in terms of number of API calls.

**Comment by kapilt** [comment]
closed in #467
