### ISSUE TITLE
S3 CW Metrics Filtering is not working as expected

### ISSUE THREAD

**Issue by jimmyraywv** [capitalone/cloud-custodian#363]
With known empty buckets in the target account, I used the two following filters that did not catch any known buckets.  There are many buckets that are empty, so both CW filters should have triggered.

  - name: s3-empty-report
    resource: s3
    filters:
      - type: metrics
        name: NumberOfObjects
        value: 0
        op: eq

  - name: s3-empty-report
    resource: s3
    filters:
      - type: metrics
        name: NumberOfObjects
        value: 1000
        op: less-than

**Comment by kapilt** [comment]
so the model attribute and the dimension name diverge for s3, its Name on one side and BucketName on the other.

**Comment by kapilt** [comment]
fixed in #368 and released in 0.8.18.1
