### ISSUE TITLE
filter for ebs ami snapshots

### ISSUE THREAD

**Issue by ocampocj** [capitalone/cloud-custodian#366]
Hi @kapilt, 

In testing some new functionality around ebs-snapshots, I found a possible issue with logging.  AMI snapshots are successfully skipped, as expected, but the logging appears to still note that x number of snapshots have been deleted even if they haven't.  This is obviously not a huge issue, but it could cause confusion if troubleshooting an issue.

Thanks!

**Comment by kapilt** [comment]
yeah.. in general filters should get to the actionable set, as thats what gets recorded, actions doing filtering can skew those numbers, ie, in this context we would need an is-ami-snapshot filter to out those to get accurate stats.

**Comment by kapilt** [comment]
Merged in #466
