### ISSUE TITLE
S3 Tag Action is Trying to Store AWS Tags

### ISSUE THREAD

**Issue by jimmyraywv** [capitalone/cloud-custodian#370]
When using a action clause like:

    actions:
      - type: tag
        key: <tag_name>
        value: <tag_value>

We are seeing an error like:

"An error occurred (InvalidTag) when calling the PutBucketTagging operation: Your TagKey cannot be prefixed with aws:"

So,it looks like the action is trying to add aws tags along with custom tags.

**Comment by kapilt** [comment]
yeah. its a little odd to modify tags on buckets you have to put the full set of tags, we can just omit the aws ones and see what happens, but based on extant behavior it would mean erasing the aws prefixed ones.

**Comment by kapilt** [comment]
i assume the aws tags on the bucket were cloudformation initiated.

**Comment by kapilt** [comment]
note that this will indeed erase the aws prefix tags, that's just an aws api limitation around s3.
