### ISSUE TITLE
Issue running the policy

### ISSUE THREAD

**Issue by vinodtiwari** [capitalone/cloud-custodian#377]
Hi Team,

I created a policy - attached with .txt extension as .yml extension is not supported. Here I trying to stop the server at 07:00 PM and then starting them again at 10:00 AM. I'm getting following error while executing it.

```
[ec2-user@ip-192-168-0-174 cloud-custodian]$ ./bin/custodian run -c policy.yml -s out
Traceback (most recent call last):
  File "./bin/custodian", line 9, in <module>
    load_entry_point('c7n==0.8.17.3', 'console_scripts', 'custodian')()
  File "/home/ec2-user/cloud-custodian/c7n/cli.py", line 125, in main
    options.command(options)
  File "/home/ec2-user/cloud-custodian/c7n/commands.py", line 36, in _load_policies
    collection = policy.load(options, options.config)
  File "/home/ec2-user/cloud-custodian/c7n/policy.py", line 48, in load
    raise errors[0]
jsonschema.exceptions.ValidationError: 'offhour-stop-19' does not match '^[A-z][A-z0-9]*(-[A-z0-9]*[A-z][A-z0-9]*)*$'

Failed validating 'pattern' in schema[7]['allOf'][0]['properties']['name']:
    {'pattern': '^[A-z][A-z0-9]*(-[A-z0-9]*[A-z][A-z0-9]*)*$',
     'type': 'string'}

On instance['name']:
    'offhour-stop-19'
[ec2-user@ip-192-168-0-174 cloud-custodian]$ [ec2-user@ip-192-168-0-174 cloud-custodian]$ ./bin/custodian run -c policy.yml -s out
-bash: [ec2-user@ip-192-168-0-174: command not found
[ec2-user@ip-192-168-0-174 cloud-custodian]$
```

Could anyone please help in debugging the issue? Also is there any way that we define the policy to stop the EC2 instance on Weekends - Saturday and Sunday - and during off hours.

Does Cloud Custodian create a backend job on AWS (using API calls - CloudWatch?) which keeps on stopping and starting the EC2 instance based on policy or do we need to run daily.

Thanks for the help in advance.

[policy.txt](https://github.com/capitalone/cloud-custodian/files/434121/policy.txt)

**Comment by kapilt** [comment]
the error is trying to tell you that it doesn't like the policy name.

**Comment by vinodtiwari** [comment]
Hey Kapil, I figured it out and ran the policy successfully. Unfortunately
forgot to close the issue.

-Vinod

**Comment by vinodtiwari** [comment]
Kapil - I have few queries:

```
[ec2-user@ip-192-168-0-174 cloud-custodian]$ ./bin/custodian run -c policy.yml -s out
2016-08-24 09:12:17,759: custodian.policy:INFO Running policy Test_Server-offhour resource: ec2 region:us-east-1
2016-08-24 09:12:17,760: custodian.resources.ec2:INFO Filtered from 22 to 0 ec2
2016-08-24 09:12:17,761: custodian.policy:INFO policy: Test_Server-offhour resource:ec2 has count:0 time:0.00
2016-08-24 09:12:17,761: custodian.policy:INFO Running policy Test_Server-onhour resource: ec2 region:us-east-1
2016-08-24 09:12:17,763: custodian.resources.ec2:INFO Filtered from 22 to 0 ec2
2016-08-24 09:12:17,763: custodian.policy:INFO policy: Test_Server-onhour resource:ec2 has count:0 time:0.00
```

I noticed today that the EC2 instance was running however as per my policy it should have stopped at 22:00 hrs and started at 10:00 AM next morning. Am I missing something in my policy?

1) I want to stop the server at 10:00 PM and start it again at 10:00 AM next day. Do I need to give create IAM user and give some privileges?
2) Also how can how can we write the policy to keep the instances shut on weekend? Do we have some syntax to specify the day (week ...) like we do whilst setting CRON job?

Sorry for troubling you again.

-Vinod

**Comment by kapilt** [comment]
its no trouble, we've been iterating features faster than docs, so the burden is on us to explain.

first can you send a gist link to your policy.

1. just StartInstances, DescribeTags, StopInstances, DescribeInstances as a baseline, good to also have CreateTags/RemoveTags
2. weekends-only will have the offhours trigger on friday (default 19), and onhours trigger on monday morning (default 7)
3. execution mode is separate then the policy semantics. The default execution mode is basically poll with the user responsible for setting up the execution (ie running a server with cron or the like), this mode is useful when you have lots of policies in a large account as they share a cache between policies and can greatly reduce the number of api calls made into an account. *Or* you can use periodic execution mode which will provision the policies directly into lambda.  see the example at the bottom of http://www.capitalone.io/cloud-custodian/policy/lambda.html  note you can use any of the time expressions here http://goo.gl/x3oMQ4

there's one other subtle aspect to offhours, namely that if you want to avoid starting resources that custodian didn't stop, you'll also need to tag them with a 'marker' filter when stopping, and use that as a filter when starting.
