### ISSUE TITLE
cli utility in tools for renaming a policy outputs

### ISSUE THREAD

**Issue by kapilt** [capitalone/cloud-custodian#397]
in response to a policy rename, as we're currently tracking outputs in s3 with the policy name :(

don't see a great way to otherwise resolve this, outside of having folks do uuids in policy.. so at the least let's give folks a way to handle it a bit better.

**Comment by calvinhp** [comment]
Do you envision a policy itself that handles the rename, or is this a CLI command like:

    $ custodian rename old-name new-name

**Comment by kapilt** [comment]
for this one i was thinking just a standalone script in tools/ops/policyrename.py

**Comment by kapilt** [comment]
in tools/ops/policyrename.py
