### ISSUE TITLE
cli logs should handle non lambda policies

### ISSUE THREAD

**Issue by kapilt** [capitalone/cloud-custodian#409]
push out to policy exec mode for implementation, for non lambda policies trawl s3 (same logic as report). also cleanup cli options.

**Comment by dayna-c** [comment]
Per email from Kapil: 

This is about the cli logs command supporting either lambda or cli poll executed based policies transparently, the logs for the later are stored in the output directory passed in on the cli (-s). The trawling logic here for s3 on logs is similar to what we do for reports.

**Comment by kapilt** [comment]
ideally doing policy.get_logs that can defer to execution mode, and have the cli update to just invoke the policy method. we should also accept a cw log group and pull from there instead of s3, as it will be more timely.

**Comment by calvinhp** [comment]
What in the policy would trigger something to run in Lambda vs the CLI Poll?

**Comment by kapilt** [comment]
execution mode per the docs.

**Comment by kapilt** [comment]
http://www.capitalone.io/cloud-custodian/docs/policy/lambda.html

**Comment by skurfer** [comment]
> also cleanup cli options

What do you have in mind for this? It looks like the `logs` subcommand is using the default options. Did you mean create some option specific to that command (like `_report_options`), or clean up the defaults in some way?

**Comment by skurfer** [comment]
Pay no attention to commit messages mentioning this issue. 🙈

Everything seems to be working, but I need to add more tests.
