### ISSUE TITLE
cli validate should take multiple config files

### ISSUE THREAD

**Issue by kapilt** [capitalone/cloud-custodian#410]
also ensure uniqueness of policy names.

**Comment by skurfer** [comment]
It looks like there’s already a check for duplicates in `schema.validate`, but it was there before your comment above. Should it be checking for dupes across all files?

**Comment by kapilt** [comment]
yup duplicates across files, we typically segment files by periodicity of execution, so would like validate to take multiple files to check for duplicates across all the files we execute for account.

**Comment by skurfer** [comment]
This should have been closed with the merge of #593
