### ISSUE TITLE
Ability to tie 'unmark' actions to specifc 'op'

### ISSUE THREAD

**Issue by ocampocj** [capitalone/cloud-custodian#419]
Hi @kapilt.  We've run into some scenarios in which marking/unmarking resources can become contradictory.  In some cases, resources marked for one violation may be inadvertently unmarked simply because it meets another policy's requirement.  The simplest resolution I can think of is to add the ability to tie the 'unmark' actions to a specific 'op', similarly to the 'mark' action.  

The cases of resources violating multiple policies seem to be rarer, but as policy files become longer and more complex, this could be a bigger issue.  Any ideas?

Thanks

**Comment by kapilt** [comment]
Use different tags for different policies, we have a tag limit of 50 now on many resources.

**Comment by kapilt** [comment]
trying to hot box multiple policies on to different tags, means a non compliant resource gets labeled with which, just seems like more complexity vs using a separate tag.

**Comment by kapilt** [comment]
that said i'm not opposed if its a contrib.

**Comment by kapilt** [comment]
given that just using different tags for different policies is the right answer for this, going to close this out, hot boxing is just going to lead to additional complications.

**Comment by ocampocj** [comment]
sorry for the delay.  agreed, this makes sense.  thanks kapilt!
