### ISSUE TITLE
mark-for-op & unmark tagging actions for S3 buckets

### ISSUE THREAD

**Issue by stevenmjo** [capitalone/cloud-custodian#422]
Most ec2 resources inherit baseline filters & actions from query.py. s3 interactions and boto requests react differently for s3 buckets vs ec2 resources. Therefore the ec2 baseline filters & actions are not completely portable to other aws resources. May need to write specific mark & unmark functions for s3 actions & filters for this issue. 

e.g. getting list of tags (requests and responses) differs between s3 and ec2

**Comment by kapilt** [comment]
why? what action would you do on a bucket?

**Comment by kapilt** [comment]
its not really clear what the ask here is or why, mostly this seems to be explaining that s3 and ec2 are different.. yes, they are.

**Comment by stevenmjo** [comment]
We want to start marking untagged s3 buckets.

**Comment by kapilt** [comment]
you can tag and untag

**Comment by stevenmjo** [comment]
https://github.com/capitalone/cloud-custodian/blob/master/c7n/resources/s3.py#L1043

Does this support untagging?

**Comment by kapilt** [comment]
it doesn't, although it could pretty easily, since its putting the set of tags, but given the desire for orthogonality, an untag would be nicer. per discussion in slack it does sound like the goal here beyond tag/untag, is support for mark/unmark style on buckets.
