### ISSUE TITLE
Output Custodian Version Number in Logs

### ISSUE THREAD

**Issue by ocampocj** [capitalone/cloud-custodian#449]
@kapilt, it would be useful to have the version of Custodian that is running in a given environment readily available in order to schedule policy changes around release dependencies.

**Comment by kapilt** [comment]
logging version on policy run in #450

**Comment by jeffastorey** [comment]
@kapilt would it be worth having a separate issue to display the version that is currently deployed rather than just in the run log? It's useful to know what's running before pushing a policy.
