### ISSUE TITLE
Can't install via pip

### ISSUE THREAD

**Issue by nikolay** [capitalone/cloud-custodian#45]
This fails:
```Bash
$ pip install git+https://github.com/capitalone/cloud-custodian.git
```
Although your package is not on PyPI, we should be able to install it via pip.

**Comment by kapilt** [comment]
there was already an unrelated custodian package on so we're using a different package name, per our install instructions, 

```
$ pip install c7n
```

If you want to install it straight from git, this should do it.

```
$ pip install  git+https://github.com/capitalone/cloud-custodian.git#egg=c7n
```

**Comment by nikolay** [comment]
@kapilt Thank you!

**Comment by kapilt** [comment]
also updated readme with pip install instructions, cheers.
