### ISSUE TITLE
Temp File Issue

### ISSUE THREAD

**Issue by mandeepbal** [capitalone/cloud-custodian#469]
I'm getting a ton binaries showing up in the `/tmp` space. please help! k thx bye

**Comment by kapilt** [comment]
sigh windows support, time to yank. we used to do ops on files which windows didn't like, got merged in #118 to be reverted.

**Comment by skurfer** [comment]
> sigh windows support, time to yank. we used to do ops on files which windows didn't like

Does this mean we’re no longer opening the file a second time and those changes should just be reversed, or is there more to it than that?
