### ISSUE TITLE
SNS transport

### ISSUE THREAD

**Issue by jeffastorey** [capitalone/cloud-custodian#47]
Notifications capability should have an SNS transport option for real-time notifications.

**Comment by kapilt** [comment]
two things, i've got support in a branch for sns transport, but its not going to be very useful as its going to be a raw json message. second, the latency around the sqs should be under a minute, we're basically on a 5m timer with lambda, and the lambda delivery loops on the queue for 4 minutes.

**Comment by jeffastorey** [comment]
Under a minute is probably sufficient for most use cases - good to know it's that fast now.

In addition, SNS has other applications other than real time. It would be nice to be able to list an SNS topic and have people subscribe as they see fit so we can get new subscribers to notifications without updating custodian config files.

The json issue is a little more difficult. Have to think about this one some more...

**Comment by kapilt** [comment]
This is dependent on #163
