### ISSUE TITLE
No query filtering support for EMR

### ISSUE THREAD

**Issue by aiell0** [capitalone/cloud-custodian#485]
Hello,

There is currently no support for adding query filter options on EMR. We are finding that on AWS accounts with many EMR clusters, we are going over our rate limits because there is no way to filter out all of the clusters we don't need in the query.

I have coded a solution and am writing the tests now. I will link my pull request to this issue once I am finished.

**Comment by kapilt** [comment]
sounds good, i just reviewed our emr support and it seems a bit lacking. i'd like to support the query options you mention (days as relative date specification, and created-before, created-after), and additionally inspecting the configuration of the cluster, and the ability to delete. This is mostly fyi on future roadmap items on emr.

**Comment by aiell0** [comment]
Currently, we only have a need for the "ClusterStates" filter, so that is the one I am applying at the moment. I will also be implementing the delete function in another pull request/issue.

**Comment by aiell0** [comment]
Pull Request for this improvement is at https://github.com/capitalone/cloud-custodian/pull/487
