### ISSUE TITLE
No delete operation for EMR Cluster

### ISSUE THREAD

**Issue by aiell0** [capitalone/cloud-custodian#488]
There is currently no support for deleting EMR clusters in Cloud Custodian. We have a need for this feature, so I am just creating this for Capital One's recordkeeping. I will code up the implementation and unit tests and paste the pull request here when I am finished.

**Comment by kapilt** [comment]
dupe fwiw on #407, but happy to role with this one.

**Comment by aiell0** [comment]
Pull Request is at https://github.com/capitalone/cloud-custodian/pull/490

I will add more tests soon so coveralls passes.
