### ISSUE TITLE
--resource filter doesn't seem to work

### ISSUE THREAD

**Issue by rowanu** [capitalone/cloud-custodian#515]
When I run Custodian with a resource filter (e.g. `custodian run --resource ec2 ...`) it doesn't seem to have any impact - I get all policies regardless of resource type.

I'm still getting familiar with the codebase, but I think [this generator](https://github.com/capitalone/cloud-custodian/blob/master/c7n/policy.py#L64) is adding _all_ policies _all_ the time (because of the `or 1` at the end). Is that intentional?

**Comment by kapilt** [comment]
fixed in #539
