### ISSUE TITLE
Monitoring endpoint does not exist

### ISSUE THREAD

**Issue by gingersnapz** [capitalone/cloud-custodian#525]
When running the s3stats in custodian tools, it attempts to grab the bucket region: 

`bucket_region = s3.get_bucket_location(
                Bucket=b['Name'])['LocationConstraint']` 

However, if the bucket is in Ireland, the value returned is "EU". So it would fail when it attempted to reach monitoring.EU.amazonaws.com since that domain doesn't exist.
I added a quick fix within s3stat.py but should be possible to just map the monitoring endpoint with the existing boto data file or another work around.

**Comment by kapilt** [comment]
hmm.. looks like an s3 inconsistency that needs client handling, for all other values of LocationConstraint this maps 1 to 1 to region per 
http://docs.aws.amazon.com/AmazonS3/latest/API/RESTBucketGETlocation.html

**Comment by kapilt** [comment]
we'll need to add this to resources/s3.py as well which uses the same location constraint to region logic.
