### ISSUE TITLE
fix drone config to not err on no sphinx changes

### ISSUE THREAD

**Issue by kapilt** [capitalone/cloud-custodian#528]
If we have non code changes make ghpages will exit 1 which fails our drone ci setup, even though we have a perfectly valid build.

**Comment by kapilt** [comment]
i'll need to get you access to our drone server i think

**Comment by skurfer** [comment]
I was going to ask, but really, if I can get `make ghpages` exit cleanly locally, that will probably take care of it. I might still need access for #529 though.

**Comment by kapilt** [comment]
sounds good re exit clean
