### ISSUE TITLE
s3 bucket remediation should only notify on buckets that had unencrypted objects

### ISSUE THREAD

**Issue by jeffastorey** [capitalone/cloud-custodian#53]
The encrypt all keys policy sends notifications that include all s3 buckets that were scanned. It should only include those that were remediated, or at least some indication of how many objects in each bucket were scanned and how many were not previously encrypted.

**Comment by kapilt** [comment]
from a model perspective this is a little odd, basically notify action would need its own filters. we'll need to annotate the s3 object as well the stats picked up.

**Comment by jeffastorey** [comment]
understood it may not fit into the current model of things, just something to think about for making this notification more useful

**Comment by kapilt** [comment]
well something that might be more useful is maybe attaching the remediation stats to the bucket object, so that when it goes out via the notify action, the template has enough context to report total scanned, total remediated per bucket, and filter as needed there.

**Comment by jeffastorey** [comment]
that works as well

**Comment by kapilt** [comment]
Fwiw, this was implemented with KeyScanCount KeyRemediated annotations on buckets.
