### ISSUE TITLE
improve errors from custodian command

### ISSUE THREAD

**Issue by skurfer** [capitalone/cloud-custodian#540]
Two things I would propose:
- Move all `sys.exit()` calls out of `commands.py` and into `cli.py`
- Raise exceptions or use return values from `commands.py`, but make sure `cli.py` catches all of them and shows a concise, useful error

**Comment by ewbankkit** [comment]
Relates to https://github.com/capitalone/cloud-custodian/issues/191.

**Comment by kapilt** [comment]
its always good to start with the why, whats the benefit?

**Comment by skurfer** [comment]
This was with the assumption that `commands.py` would be a part of the eventual Python API. From comments elsewhere, it sounds like `commands.py` isn’t meant to be used with anything other than `cli.py`, so if the two can’t be cleanly separated, it probably doesn’t matter in practice.
