### ISSUE TITLE
s3 - encryption policy filter

### ISSUE THREAD

**Issue by kapilt** [capitalone/cloud-custodian#550]
Currently the encryption policy filter uses missing-policy-statement which filters a policy by statement id, which means its not tamper resistant. The s3 action encryption-policy is tamper proof (reserved statement id, verify contents). But to be end to end we need the filter to also have that capability, likely we just need a new filter, as we're checking policy statement contents.

**Comment by ocampocj** [comment]
@kapilt - Since this came up last week, I think this would be a good candidate for the Blue Team board.  We can discuss later if you think otherwise.
