### ISSUE TITLE
Add ability to encrypt S3 objects using customer provided CMK

### ISSUE THREAD

**Issue by kskvarci** [capitalone/cloud-custodian#562]
Add the ability to encrypt S3 objects using a customer provided CMK in addition to (AES256) or the default KMS key (aws:kms).

**Comment by kapilt** [comment]
do you mean a non default kms key, or a customer provided key, effectively both are customer managed, but with different degrees of trust to aws. 

http://docs.aws.amazon.com/AmazonS3/latest/dev/serv-side-encryption.html

**Comment by kskvarci** [comment]
Should have been more specific. I mean (SSE-KMS) with a non-default kms key, not (SSE-C). Probably would be good to have support for the latter eventually but not a current priority.

**Comment by calvinhp** [comment]
Do we want the ability for the `encrypt-keys` action to re-encrypt to a new `key-id` if the one in the policy differs from the current encryption key?
