### ISSUE TITLE
sphinx extension for docs from json schema

### ISSUE THREAD

**Issue by kapilt** [capitalone/cloud-custodian#566]
given our utilization of json schema, it would be nice to have documentation auto extract a filter/actions parameters into the docs directly from their respective schema.

**Comment by scotwk** [comment]
@kapilt - I attached a screenshot of an example for EC2's docs.  Is this what you mean?  I extracted the schema attribute from the filter classes and display it inline with the filter name.

![screen shot 2016-11-18 at 12 24 52 am](https://cloud.githubusercontent.com/assets/2279506/20419583/8084b9e0-ad25-11e6-8f22-a7f9578089b6.png)

**Comment by whit537** [comment]
Can this be closed with https://github.com/capitalone/cloud-custodian/pull/714?

**Comment by kapilt** [comment]
yup
