### ISSUE TITLE
[Question] Best way to clean up cloudwatch?

### ISSUE THREAD

**Issue by jason-riddle** [capitalone/cloud-custodian#572]
Cloudwatch logs, alarms, and custom metrics tend to accumulate which can add up pretty quickly with 0.05 per GB ingested, 0.10 per alarm per month, and 0.50 per metric per month respectively. Is there a way to identify stale / super old logs, constantly failing alarms that have never passed, etc.? This isn't a feature request, but more of a general question since this may be out of scope for something like cloud-custodian.

**Comment by kapilt** [comment]
logs yeah.. we have something to identify stale logs groups  via`last-write` filter that haven't been written to in a while and then garbage collect them, ditto for setting retention policies on log groups via `retention` action. 

for cw alarms we don't have anything at the moment beyond the basic resource support (iterating and filtering alarms with builtin filters & actions), but easy enough to add an alarm specific filter on alarm history.

**Comment by jason-riddle** [comment]
Metrics are now stored for 15 months: https://aws.amazon.com/blogs/aws/amazon-cloudwatch-update-extended-metrics-retention-user-interface-update/

**Comment by jason-riddle** [comment]
Or when you say auto-gc'd were you referring to cloud custodian?

**Comment by kapilt** [comment]
thanks for sharing i guess thats pretty fresh off printing press.

**Comment by kapilt** [comment]
anyways, cw costs are a pretty minuscule portion of any aws customer's bills that i've seen. the log group stuff we have mitigates the primary source of archive costs and limits.  the only anti-pattern i've seen is people using cw logs on cloudtrail, instead of using cw events.
