### ISSUE TITLE
c7n mailer docs

### ISSUE THREAD

**Issue by kapilt** [capitalone/cloud-custodian#598]
https://github.com/capitalone/cloud-custodian/tree/master/tools/c7n_mailer

kick the tires, put installer docs

**Comment by whit537** [comment]
Could you specify this more, @kapilt? Looks like there is a README for the mailer. What do you mean by "put installer docs"?

**Comment by whit537** [comment]
First pass in #784. Proceeding to kick tires ...

**Comment by kapilt** [comment]
i think what's missing are docs on how to actually deploy/operate, note there is a separate `epic` around various mailer improvements in #706

**Comment by whit537** [comment]
Do you want the docs in the [README](https://github.com/capitalone/cloud-custodian/blob/db864e403a8c7c798a378b2e5cf6ad10c1b4c4d0/tools/c7n_mailer/README.md) or on http://www.capitalone.io/cloud-custodian/docs/?

**Comment by whit537** [comment]
Off and running ...

```
(cloud-custodian) $ c7n-mailer 
usage: c7n-mailer [-h] -c CONFIG
c7n-mailer: error: argument -c/--config is required
(cloud-custodian) $
```

**Comment by whit537** [comment]
### Todo (will be revised)

- [ ] write a quickstart
- [ ] is the "Email Message Relay" a second mode of operation?
- [ ] document cli configuration

**Comment by kapilt** [comment]
message relay is a primary mode for multi-account setups, its just making the sqs queue accessible to additional accounts.

re lambda bits... some misgivings, next round of work on mailer will likely drop it out of lambda entirely as a default. for large accounts on non-lambda policies there's too much variance on a given sqs message, for how many api calls we need to make as we segment things by user. ie 250 resources might turn into 5 emails, or 250 emails depending on who is designated the `resource-owner` and assuming a notification to the resource owner.

**Comment by whit537** [comment]
Capturing from https://github.com/capitalone/cloud-custodian/pull/792#issuecomment-270115127:

> re required keys, subnets/security groups are required for the ldap lookup at the moment assuming ldap dir server isn't setup for public access, long term i'd prefer address lookup is pluggable per the laundry list on #706

**Comment by whit537** [comment]
I'm working up a quickstart, but am hitting a permissions error trying to create a role:

> User: arn:aws:iam::644160558196:user/chad@sixfeetup.com is not authorized to perform: iam:CreateRole on resource: arn:aws:iam::644160558196:role/whit537-testing-mailer

I will try to workaround by reusing an existing role ...

![screen shot 2017-01-04 at 5 46 07 am](https://cloud.githubusercontent.com/assets/134455/21639997/1eb8b6e4-d241-11e6-9dad-8a8c36998822.png)

**Comment by whit537** [comment]
Success? I manually removed the `subnets` and `security_groups` [parameters](https://github.com/capitalone/cloud-custodian/blob/82073b06062ef2097080316f38ab1a039e5baeeb/tools/c7n_mailer/c7n_mailer/deploy.py#L85-L86) rather than trying to figure out values for them. I also used the `custodian-mu` role.

```
(cloud-custodian) $ c7n-mailer -c testing.yml 
DEBUG:custodian.lambda:Created custodian lambda archive size: 1.09mb
INFO:custodian.lambda:Publishing custodian policy lambda function cloud-custodian-mailer
DEBUG:custodian.lambda:Creating cwe rule for <CWEvent Type:periodic Events:>
DEBUG:custodian.lambda:Added lambda invoke cwe rule permission
DEBUG:custodian.lambda:Creating cwe rule target for <CWEvent Type:periodic Events:> on func:arn:aws:lambda:us-west-2:644160558196:function:cloud-custodian-mailer
DEBUG:custodian.lambda:Added event source: <CWEvent Type:periodic Events:> to function: arn:aws:lambda:us-west-2:644160558196:function:cloud-custodian-mailer
(cloud-custodian) $
```

**Comment by whit537** [comment]
I do find a `cloud-custodian-mailer` Lambda. Now I'm working on sending mail through it.

![image](https://cloud.githubusercontent.com/assets/134455/21641176/29a14916-d248-11e6-8190-62cb37b6100a.png)

**Comment by whit537** [comment]
Success?

```
(cloud-custodian) $ custodian run -c test-policy.yml -s .
2017-01-04 06:42:17,692: custodian.policy:INFO Running policy mailer-test resource: sqs region:None c7n:0.8.21.2
2017-01-04 06:42:19,181: custodian.resources.sqs:INFO Filtered from 1 to 1 sqs
2017-01-04 06:42:19,181: custodian.policy:INFO policy: mailer-test resource:sqs has count:1 time:1.49
2017-01-04 06:42:20,591: custodian.actions:INFO sent message:da433b8a-ff10-4f99-bcb4-3910eb142e97 policy:mailer-test template:default count:1
2017-01-04 06:42:20,591: custodian.policy:INFO policy: mailer-test action: notify resources: 1 execution_time: 1.41
(cloud-custodian) $
```

```yaml
policies:
  - name: mailer-test
    resource: sqs
    filters:
     - "tag:MailerTest": absent
    actions:
      - type: notify
        template: default
        subject: fix your tags
        to:
          - resource-owner
        transport:
          type: sqs
          queue: https://sqs.us-west-2.amazonaws.com/644160558196/whit537-testing-mailer
```

**Comment by whit537** [comment]
Looking for an email ... not finding one ... :thinking:

**Comment by whit537** [comment]
In the CloudWatch logs for the `cloud-custodian-mailer` Lambda I find an error: `module initialization error: Incorrect padding`.

**Comment by whit537** [comment]
Ah, I bet that's for the bogus `ldap_bind_password` I provided. 😊

**Comment by whit537** [comment]
Progress! I manually made `ldap_bind_{user,password}` optional in `cli.py`.

![screen shot 2017-01-04 at 7 03 09 am](https://cloud.githubusercontent.com/assets/134455/21641759/e81c88c6-d24b-11e6-8269-a3eedc9dde57.png)

**Comment by whit537** [comment]
Actually the relevant error is:

```
[ERROR]	2017-01-04T12:01:03.754Z	76ff05c4-d275-11e6-b436-45355856ff23	import failed No module named ldap3
Traceback (most recent call last):
File "/var/task/c7n_mailer/handle.py", line 57, in run
from .worker import Worker
File "/var/task/c7n_mailer/worker.py", line 21, in <module>
from processor import Processor
File "/var/task/c7n_mailer/processor.py", line 26, in <module>
from address import get_user
File "/var/task/c7n_mailer/address.py", line 16, in <module>
from ldap3 import (
ImportError: No module named ldap3
```

**Comment by whit537** [comment]
I find that `ldap` is [specified](https://github.com/capitalone/cloud-custodian/blob/82073b06062ef2097080316f38ab1a039e5baeeb/tools/c7n_mailer/c7n_mailer/deploy.py#L38) but not `ldap3`. Hmm ...

**Comment by whit537** [comment]
Looks like I need to understand Mu's PythonPackageArchive.

**Comment by kapilt** [comment]
we do a whitelist includes in custodian_package function in mu

**Comment by kapilt** [comment]
using the existing lambda role should be fine, re iam permissions it needs sqs receive, sns publish, ses send, sts assume role, + basic lambda exec

**Comment by kapilt** [comment]
the ldap to ldap3 switch was when rob switched out from pyldap to a pure python impl, the deploy script was not updated, causing this discrepancy and breaking ootb deploys.

**Comment by whit537** [comment]
@kapilt Cool, will pick up with that next time.

**Comment by kapilt** [comment]
actually in this case the mailer's deploy.py is all you really need to modify s/ldap/ldap3 and its done.

**Comment by whit537** [comment]
I tried that and it didn't immediately work. Left off debugging until tomorrow ...

**Comment by whit537** [comment]
...

**Comment by whit537** [comment]
This morning I see way more invocations than I'd expect—something is running this Lambda besides me at the command line with `custodian -c test-mailer.yml -s .`?

![screen shot 2017-01-05 at 5 15 55 am](https://cloud.githubusercontent.com/assets/134455/21676979/1a45fbce-d306-11e6-9e5f-98ddf0466913.png)

**Comment by whit537** [comment]
And I see that `s/ldap/ldap3` _did_ work(?!). On to the next `ImportError` ...

```
[ERROR]	2017-01-05T10:11:04.199Z	43becc03-d32f-11e6-8458-77ff01da7dcc	import failed No module named pyasn1.type.univ
Traceback (most recent call last):
File "/var/task/c7n_mailer/handle.py", line 57, in run
from .worker import Worker
File "/var/task/c7n_mailer/worker.py", line 21, in <module>
from processor import Processor
File "/var/task/c7n_mailer/processor.py", line 26, in <module>
from address import get_user
File "/var/task/c7n_mailer/address.py", line 16, in <module>
from ldap3 import (
File "/var/task/ldap3/__init__.py", line 150, in <module>
from .core.server import Server
File "/var/task/ldap3/core/server.py", line 33, in <module>
from ..protocol.rfc4511 import LDAP_MAX_INT
File "/var/task/ldap3/protocol/rfc4511.py", line 41, in <module>
from pyasn1.type.univ import OctetString, Integer, Sequence, Choice, SequenceOf, Boolean, Null, Enumerated, SetOf
ImportError: No module named pyasn1.type.univ
```

**Comment by whit537** [comment]
My goal is to avoid setting up an LDAP server and just get to the [fallback](https://github.com/capitalone/cloud-custodian/blob/828b24187071fdc8fa2d28f86a39902b69e5854b/tools/c7n_mailer/c7n_mailer/address.py#L57) instead.

**Comment by whit537** [comment]
A Java exception?!

```
module initialization error: An error occurred (ValidationException) when calling the Decrypt operation: 1 validation error detected: Value 'java.nio.HeapByteBuffer[pos=0 lim=0 cap=0]' at 'ciphertextBlob' failed to satisfy constraint: Member must have length greater than or equal to 1
```

**Comment by whit537** [comment]
Surely something under https://github.com/capitalone/cloud-custodian/blob/828b24187071fdc8fa2d28f86a39902b69e5854b/tools/c7n_mailer/c7n_mailer/handle.py#L40-L42, as with https://github.com/capitalone/cloud-custodian/issues/598#issuecomment-270354248.

**Comment by whit537** [comment]
http://docs.aws.amazon.com/cli/latest/reference/kms/encrypt.html

**Comment by kapilt** [comment]
its saying you have to give it an actual value to decrypt for the ldap password, not a blank string.

**Comment by whit537** [comment]
Alright, let's see about a key here ...

```
(cloud-custodian) $ aws kms encrypt --key-id=foo --plaintext=Zm9v

An error occurred (NotFoundException) when calling the Encrypt operation: Invalid keyId
(cloud-custodian) $
```

**Comment by whit537** [comment]
http://docs.aws.amazon.com/kms/latest/developerguide/create-keys.html

**Comment by whit537** [comment]
👍

```
(cloud-custodian) $ aws kms encrypt --key-id=alias/whit537-testing-mailer --plaintext=Zm9v
{
    "KeyId": "arn:aws:kms:us-west-2:644160558196:key/02dba5d2-1185-409f-9e49-0a0eb8742866", 
    "CiphertextBlob": "AQECAHj5iqus8Cq0ZiCeAvIAk/tTGg55EAwjAOO4Z0kAuOQ2dAAAAGIwYAYJKoZIhvcNAQcGoFMwUQIBADBMBg"
}
(cloud-custodian) $
```

**Comment by whit537** [comment]
> Not sure what was happening yesterday.

I think I'm just seeing log lag? I think I noticed there's a five-minute window or something?

**Comment by whit537** [comment]
http://boto3.readthedocs.io/en/latest/reference/services/kms.html#KMS.Client.decrypt

**Comment by whit537** [comment]
https://docs.aws.amazon.com/kms/latest/APIReference/API_Decrypt.html

**Comment by whit537** [comment]
More unexpected invocations. Who is calling the Lambda I created while I'm sleeping?

--------------------

![screen shot 2017-01-06 at 5 16 32 am](https://cloud.githubusercontent.com/assets/134455/21714895/5912626a-d3cf-11e6-9d2d-693e31fcc6d3.png)

--------------------

![screen shot 2017-01-06 at 5 17 35 am](https://cloud.githubusercontent.com/assets/134455/21714914/7af9c80a-d3cf-11e6-82e5-96411c3c8812.png)

**Comment by whit537** [comment]
Whoever it is, they're using the same password, and getting the same `InvalidCiphertextException`.

![screen shot 2017-01-06 at 5 18 43 am](https://cloud.githubusercontent.com/assets/134455/21714966/b8355888-d3cf-11e6-9cc2-a4317bd1f662.png)

**Comment by whit537** [comment]
https://github.com/awslabs/aws-lambda-redshift-loader/issues/16 perhaps suggests that a region misconfiguration is the problem?

**Comment by whit537** [comment]
The lambda and key are in us-west-2. Is that what the `aws kms encrypt` call is using?

**Comment by whit537** [comment]
If it weren't, why would it succeed?

**Comment by whit537** [comment]
I do have region specified in my `~/.aws/config`.

**Comment by whit537** [comment]
Gosh. Now it looks like I was truncating the CiphertextBlob somehow? 😥 

```
(cloud-custodian) $ aws kms encrypt --key-id=alias/whit537-testing-mailer --plaintext=foo
{
    "KeyId": "arn:aws:kms:us-west-2:644160558196:key/02dba5d2-1185-409f-9e49-0a0eb8742866", 
    "CiphertextBlob": "AQECAHj5iqus8Cq0ZiCeAvIAk/tTGg55EAwjAOO4Z0kAuOQ2dAAAAGEwXwYJKoZIhvcNAQcGoFIwUAIBADBLBgkqhkiG9w0BBwEwHgYJYIZIAWUDBAEuMBEEDEyEG/GKMiONtwKqEQIBEIAe8+pRh8gNApz7sSa9NUSIlnTMawQZLMfJ66HX2QcF"
}
(cloud-custodian) $
```

**Comment by whit537** [comment]
I also discovered a nicer [bullet](https://github.com/aws/aws-cli/issues/1043#issuecomment-65878875):

```
(cloud-custodian) $ aws kms encrypt --key-id=alias/whit537-testing-mailer --plaintext=foo --query=CiphertextBlob --output text | base64
QVFFQ0FIajVpcXVzOENxMFppQ2VBdklBay90VEdnNTVFQXdqQU9PNFowa0F1T1EyZEFBQUFHRXdYd1lKS29aSWh2Y05BUWNHb0ZJd1VBSUJBREJMQmdrcWhraUc5dzBCQndFd0hnWUpZSVpJQVdVREJBRXVNQkVFREkrK04wZHdwalJrOExvTFhBSUJFSUFlL0VGTXIvdjZwRjVQUk5PK2JmczJVRDVJWUxybHdKTENNeHh6eU1DWQo=
(cloud-custodian) $
```

**Comment by whit537** [comment]
Son of a gun. Same thing? That encoded ciphertext may not match, though?

![screen shot 2017-01-06 at 5 52 13 am](https://cloud.githubusercontent.com/assets/134455/21715763/57b59a04-d3d4-11e6-80e0-eb3257b49ab3.png)

**Comment by whit537** [comment]
Looks like they're salting or timestamping or something?

```
(cloud-custodian) $ aws kms encrypt --key-id=alias/whit537-testing-mailer --plaintext=foo --query=CiphertextBlob --output text | base64
QVFFQ0FIajVpcXVzOENxMFppQ2VBdklBay90VEdnNTVFQXdqQU9PNFowa0F1T1EyZEFBQUFHRXdYd1lKS29aSWh2Y05BUWNHb0ZJd1VBSUJBREJMQmdrcWhraUc5dzBCQndFd0hnWUpZSVpJQVdVREJBRXVNQkVFRFBsdmdZWWdYc0pmSDhzK1dRSUJFSUFlb1VsSnNSL3dFUDlOOVVOaDBYN2NVbk5iUitENHdqdndldDYzdjlOZQo=
(cloud-custodian) $ aws kms encrypt --key-id=alias/whit537-testing-mailer --plaintext=foo --query=CiphertextBlob --output text | base64
QVFFQ0FIajVpcXVzOENxMFppQ2VBdklBay90VEdnNTVFQXdqQU9PNFowa0F1T1EyZEFBQUFHRXdYd1lKS29aSWh2Y05BUWNHb0ZJd1VBSUJBREJMQmdrcWhraUc5dzBCQndFd0hnWUpZSVpJQVdVREJBRXVNQkVFREF2M0piTmpzY0tEbnZnR0hRSUJFSUFlNExpaWwvQThmSXJITmJNYmk1eloyWWpQcnVBekZzL0NLYTlHR1ptYQo=
(cloud-custodian) $ aws kms encrypt --key-id=alias/whit537-testing-mailer --plaintext=foo --query=CiphertextBlob --output text | base64
QVFFQ0FIajVpcXVzOENxMFppQ2VBdklBay90VEdnNTVFQXdqQU9PNFowa0F1T1EyZEFBQUFHRXdYd1lKS29aSWh2Y05BUWNHb0ZJd1VBSUJBREJMQmdrcWhraUc5dzBCQndFd0hnWUpZSVpJQVdVREJBRXVNQkVFREdpdndwMXFPSGR6ZDk4MkR3SUJFSUFlV252Z3A3UUZlcjZ0SVpTZzQ1OUJQUUhFbWh3em0xcWFxTEJxemtVego=
(cloud-custodian) $ aws kms encrypt --key-id=alias/whit537-testing-mailer --plaintext=foo --query=CiphertextBlob --output text | base64
QVFFQ0FIajVpcXVzOENxMFppQ2VBdklBay90VEdnNTVFQXdqQU9PNFowa0F1T1EyZEFBQUFHRXdYd1lKS29aSWh2Y05BUWNHb0ZJd1VBSUJBREJMQmdrcWhraUc5dzBCQndFd0hnWUpZSVpJQVdVREJBRXVNQkVFREJKcEdUV25qaTFCZXVaRjRRSUJFSUFlQUpHd3RvMXZ2dU4rT2Z1N1N4NEdCL2VEUjJZZ0toZ3l5U2xVUWU0cAo=
(cloud-custodian) $ aws kms encrypt --key-id=alias/whit537-testing-mailer --plaintext=foo --query=CiphertextBlob --output text | base64
(cloud-custodian) $ aws kms encrypt --key-id=alias/whit537-testing-mailer --plaintext=foo --query=CiphertextBlob --output text
AQECAHj5iqus8Cq0ZiCeAvIAk/tTGg55EAwjAOO4Z0kAuOQ2dAAAAGEwXwYJKoZIhvcNAQcGoFIwUAIBADBLBgkqhkiG9w0BBwEwHgYJYIZIAWUDBAEuMBEEDEiGYNwuH6ojYl/lJwIBEIAe9e3g+H1cbwRBDPzFPy+m4XO9TlgQz4vHFl/yYtzt
(cloud-custodian) $ aws kms encrypt --key-id=alias/whit537-testing-mailer --plaintext=foo --query=CiphertextBlob --output text
AQECAHj5iqus8Cq0ZiCeAvIAk/tTGg55EAwjAOO4Z0kAuOQ2dAAAAGEwXwYJKoZIhvcNAQcGoFIwUAIBADBLBgkqhkiG9w0BBwEwHgYJYIZIAWUDBAEuMBEEDBk79bhjRumWrAx8OAIBEIAesSZAuKIg2ANxH/XoEA3vi1Hh2yBZZ9to10mBCyIf
(cloud-custodian) $ aws kms encrypt --key-id=alias/whit537-testing-mailer --plaintext=foo --query=CiphertextBlob --output text
AQECAHj5iqus8Cq0ZiCeAvIAk/tTGg55EAwjAOO4Z0kAuOQ2dAAAAGEwXwYJKoZIhvcNAQcGoFIwUAIBADBLBgkqhkiG9w0BBwEwHgYJYIZIAWUDBAEuMBEEDI52QL/qsyIAjxLQmgIBEIAebgosCOOcOkbK1Ci8gAvq+njeUi17qNKmdhiCAA7+
(cloud-custodian) $ aws kms encrypt --key-id=alias/whit537-testing-mailer --plaintext=foo --query=CiphertextBlob --output text
AQECAHj5iqus8Cq0ZiCeAvIAk/tTGg55EAwjAOO4Z0kAuOQ2dAAAAGEwXwYJKoZIhvcNAQcGoFIwUAIBADBLBgkqhkiG9w0BBwEwHgYJYIZIAWUDBAEuMBEEDNnkYTJ0bNsjhR33QgIBEIAeX7eOcpOwpIBsbtHmYa8ldQqhiFL/IhIe390ANcdy
(cloud-custodian) $
```

**Comment by whit537** [comment]
Yeah, I'm skunked. Still hitting `InvalidCiphertextException`.

![screen shot 2017-01-06 at 6 15 30 am](https://cloud.githubusercontent.com/assets/134455/21716278/9bd5297c-d3d7-11e6-8597-b79be54efb3f.png)

**Comment by kapilt** [comment]
The mailer lambda is setup for 5m periodic execution

**Comment by whit537** [comment]
@kapilt @skurfer Any idea what I'm doing wrong here? I applied loose permissions to the queue I'm testing with, but I didn't see how to do the same with the lambda.

### Steps

<ol>
<li>Go to the root of your Custodian working copy and activate yer virtualenv.</li>
<li>Sync up code:
<pre>
git checkout 82073b06062ef2097080316f38ab1a039e5baeeb
curl https://gist.githubusercontent.com/whit537/8b181f00f1fb01b458f6e8ab6c8afd90/raw/4249a8b6ecf1cb71cfcb0b404c05dccaed075be2/82073b0.diff | git apply -</pre></li>
<li>Install the mailer:<pre>
cd tools/c7n_mailer
pip install -r requirements.txt
pip install -e .</pre></li>
<li>Grab my config files:<pre>
curl -O https://gist.githubusercontent.com/whit537/8b181f00f1fb01b458f6e8ab6c8afd90/raw/4249a8b6ecf1cb71cfcb0b404c05dccaed075be2/mailer.yml
curl -O https://gist.githubusercontent.com/whit537/8b181f00f1fb01b458f6e8ab6c8afd90/raw/4249a8b6ecf1cb71cfcb0b404c05dccaed075be2/test-policy.yml</pre></li>
<li>Run it!<pre>
c7n-mailer -c mailer.yml && custodian run -c test-policy.yml -s .
</pre></li>
<li>Check console output:<pre>
DEBUG:custodian.lambda:Created custodian lambda archive size: 3.02mb
DEBUG:custodian.lambda:Updating function cloud-custodian-mailer code
2017-01-06 06:49:56,248: custodian.policy:INFO Running policy mailer-test resource: sqs region:None c7n:0.8.21.2
2017-01-06 06:49:59,593: custodian.resources.sqs:INFO Filtered from 1 to 1 sqs
2017-01-06 06:49:59,593: custodian.policy:INFO policy: mailer-test resource:sqs has count:1 time:3.34
2017-01-06 06:50:00,878: custodian.actions:INFO sent message:3353f52b-7010-4afa-8e29-1cd25fe93f11 policy:mailer-test template:default count:1
2017-01-06 06:50:00,878: custodian.policy:INFO policy: mailer-test action: notify resources: 1 execution_time: 1.29
</pre></li>
<li>Wait five minutes.</li>
<li>Check the latest <a href="https://us-west-2.console.aws.amazon.com/cloudwatch/home?region=us-west-2#logStream:group=/aws/lambda/cloud-custodian-mailer;streamFilter=typeLogStreamPrefix">log</a> (can you see that?).</li>
</ol>

### Expected

Some error about LDAP not connecting properly.

### Actual

`InvalidCiphertextException`, per above.

**Comment by whit537** [comment]
> The blob includes metadata.

http://boto3.readthedocs.io/en/latest/reference/services/kms.html#KMS.Client.decrypt

Hmm ... :thinking:

**Comment by whit537** [comment]
https://d0.awsstatic.com/whitepapers/KMS-Cryptographic-Details.pdf

**Comment by whit537** [comment]
Gosh, what a 🐰 hole.

**Comment by whit537** [comment]
> Ciphertext contains encrypted data with additional information that identifies the CMK to use in the
decryption process.

https://d0.awsstatic.com/whitepapers/KMS-Cryptographic-Details.pdf

**Comment by whit537** [comment]
> After a customer has established a CMK, it can be used to perform cryptographic operations. Whenever an element is encrypted under a CMK the resulting object is a customer ciphertext. The ciphertext will contain two sections: an unencrypted header (or cleartext) portion, protected by the authenticated encryption scheme as the additional authenticated data, and an encrypted portion. The cleartext portion will include the HSA backing key identifier (HBKID). These two immutable fields of the ciphertext value help ensure that AWS KMS will be able to decrypt the object in the future.

**Comment by whit537** [comment]
> The ciphertext and the EKT are sent, along with the encryption context, over an authenticated session to an HSA for decryption.
>
> The HSA will execute the following:
> 1. Decrypt the EKT to obtain the HBK = Decrypt(DKi , EKT).
> 2. Determine a 256-bit encryption key K from HBK.
> 3. Decrypt the ciphertext to obtain plaintext = Decrypt(K, context,
ciphertext).

**Comment by whit537** [comment]
> Upon reception, AWS KMS will request the creation of an initial HSA backing key (HBK) to be placed into the CMK container. We denote all such HSA-resident-only keys in red. The HBK will be generated on an HSA in the domain and is designed to never be exported from the HSA in plaintext. Instead, the HBK is exported encrypted under HSA-managed domain keys. We refer to these exported HBKs as exported key tokens (EKT).

**Comment by whit537** [comment]
Leaving off with this for now, with this [local diff](https://gist.github.com/whit537/7e0e826dc97b9a0e824023413e4dc0b9).

**Comment by whit537** [comment]
Just noticed @kapilt in Gitter:

> i'd suggest disabling it, one of the goals for dev on mailer is pluggable resolvers

**Comment by whit537** [comment]
> the ldap to ldap3 switch was when rob switched out from pyldap to a pure python impl, the deploy script was not updated, causing this discrepancy and breaking ootb deploys.

Ftr this is what sent me after integration testing (#455 &rarr; #836).

**Comment by whit537** [comment]
Unwound and trying again w/ no `ldap_*`

```
queue_url: https://sqs.us-west-2.amazonaws.com/644160558196/whit537-testing-mailer
role: "arn:aws:iam::644160558196:role/custodian-mu"

region: us-west-2

contact_tags: []
```

**Comment by whit537** [comment]
On to the next!

![screen shot 2017-01-11 at 7 34 29 am](https://cloud.githubusercontent.com/assets/134455/21848748/755b68ea-d7d0-11e6-9049-09fece16c359.png)

**Comment by whit537** [comment]
[Looks](https://github.com/capitalone/cloud-custodian/blob/master/tools/c7n_mailer/c7n_mailer/processor.py#L268-L269) like an email address directly in the policy should work.

**Comment by whit537** [comment]
Chippin' away ...

![screen shot 2017-01-11 at 7 47 51 am](https://cloud.githubusercontent.com/assets/134455/21849140/4710cf00-d7d2-11e6-8caa-c2b9c79556f1.png)

**Comment by whit537** [comment]
I've verified my address and run:

```
(cloud-custodian) $ custodian run -c test-policy.yml -s .
2017-01-12 05:27:58,517: custodian.policy:INFO Running policy mailer-test resource: sqs region:default c7n:0.8.22.0
2017-01-12 05:28:00,043: custodian.policy:INFO policy: mailer-test resource:sqs has count:1 time:1.53
2017-01-12 05:28:01,373: custodian.actions:INFO sent message:951f7397-19d5-4781-b28a-b762b5a3e112 policy:mailer-test template:default count:1
2017-01-12 05:28:01,373: custodian.policy:INFO policy: mailer-test action: notify resources: 1 execution_time: 1.33
```

Waiting for message to appear in inbox or logs ...

**Comment by whit537** [comment]
Not seeing anything sent ...

![screen shot 2017-01-12 at 5 29 30 am](https://cloud.githubusercontent.com/assets/134455/21886042/21d8509e-d888-11e6-97d3-1c4cb3e7e147.png)

**Comment by whit537** [comment]
Now it looks like chad@sixfeetup.com is probably okay but custodan@example.com is not?

![image](https://cloud.githubusercontent.com/assets/134455/21887111/978a00cc-d88c-11e6-9cec-e052473ed6f2.png)

**Comment by whit537** [comment]
Ah! That's the from address.

**Comment by whit537** [comment]
💃 

![screen shot 2017-01-12 at 6 16 21 am](https://cloud.githubusercontent.com/assets/134455/21887630/af7c3cc0-d88e-11e6-8b68-cf2b0dfb99a7.png)

**Comment by whit537** [comment]
Alright! So it's gonna take some code changes before we can write a workable quickstart.

**Comment by whit537** [comment]
PR in #843. Next is a quickstart in the README ...

**Comment by whit537** [comment]
Tutorial in #844.

**Comment by whit537** [comment]
Good to close, @kapilt? #834/#844 are in.

**Comment by kapilt** [comment]
yup, thanks!
