### ISSUE TITLE
library paths for Lambda packaging is hardcoded

### ISSUE THREAD

**Issue by quiver** [capitalone/cloud-custodian#627]
Due to hard coded library paths, Lambda cannot be executed.

```
No module named yaml: ImportError Traceback (most recent call last): File "/var/task/custodian_policy.py", line 4, in run return handler.dispatch_event(event, context) File
...
File "/var/task/skew/config.py", line 18, in <module>
import yaml
ImportError: No module named yaml
```
via CloudWatch Logs.

When creating Lambda packages, `c7n/mu.py` only packages libraries under `BASEPATH/lib/python2.7/site-packages/` . 
https://github.com/capitalone/cloud-custodian/blob/master/c7n/mu.py#L114

But packages can be installed under different paths.
For example, on Amazon Linux, after creating virtualenv and using that pip, run `$ pip install XXX` will  install packages under `VENVPATH/lib64/python2.7/site-packages/`(Note `lib` and `lib64` difference.). That's why yaml libraries are not packaged. 

There should be more clever way to search for Python lib paths.

**Comment by kapilt** [comment]
applicable is sys.path os os.environ['PYTHONPATH'].split(":") in a loop around the same line.

**Comment by kapilt** [comment]
fwiw this has worked on both rhel7.2 and ubuntu14.04 and 16.04, curious what the delta is on this environment besides amz linux, needs some a bit more investigation, there's some .pth files here that we may have to parse.
