### ISSUE TITLE
Docs on deploying as lambda function

### ISSUE THREAD

**Issue by petehayes** [capitalone/cloud-custodian#63]
I attempted to deploy as a lambda function the following policy:

```
policies:
  - name: tag-compliance
    resource: ec2
    mode:
      type: cloudtrail
      events:
        - RunInstances
    comment: |
       Stop instances that do not follow tagging policy
    filters:
      - State.Name: running
      - "tag:CustomerID": absent
    actions:
      - stop
```

This failed with the error:

```
2016-05-04 13:57:14,954: custodian.output:ERROR Error while executing policy
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/c7n/policy.py", line 162, in provision
    PolicyLambda(self), 'current', role=self.options.assume_role)
  File "/usr/local/lib/python2.7/dist-packages/c7n/mu.py", line 208, in publish
    result, changed = self._create_or_update(func, role, s3_uri, qualifier=alias)
  File "/usr/local/lib/python2.7/dist-packages/c7n/mu.py", line 270, in _create_or_update
    assert role, "Lambda function role must be specified"
AssertionError: Lambda function role must be specified
```

Is there a definition of a role that is required for this lambda function to work documentationed anywhere?  I also couldn't find documentation on how to specify the role.  The [example](http://www.capitalone.io/cloud-custodian/policy/lambda.html) didn't include or mention it.

**Comment by mandeepbal** [comment]
Hi Pete, When custodian deploys code, it use the role you are assuming or using to assign to the Lambda function. Lambda functions heed a role with the correct trust relationship setup. The commands below are what I use to deploy custodian. Try creating a role for your lambda function that you can also assume to deploy the policy.

```
/usr/local/custodian/bin/custodian run --cache-period=15 -v \
  -m -l /cloud-custodian/myaccount/us-east-1 -s s3://mylogs/us-east-1/ \
 --assume="arn:aws:iam::123123123123:role/mylambdarole" \
  -c /etc/custodian/policies/hourly.yml &>> /var/log/custodian/run.log
```

**Comment by kapilt** [comment]
you can also specify the role inline within the policy as part of the mode section

```
    mode:
      type: cloudtrail
      role: lambda_role_arn
      events:
        - RunInstances
```

**Comment by petehayes** [comment]
Thanks - is there a definition of the role that can be shared?

**Comment by kapilt** [comment]
which iam permissions you need is dependent on which policies your running and what they do, we can probably do some automation for iam policy generation, analogous to how we generate our jsonschema.

**Comment by petehayes** [comment]
Both approaches worked for me.  Thanks.
