### ISSUE TITLE
Suggestion: switch c7n_mailer from Python-LDAP to ldap3

### ISSUE THREAD

**Issue by skurfer** [capitalone/cloud-custodian#637]
http://ldap3.readthedocs.io

For the sorts of read-only operations it’s doing, this would be a really simple change.

Advantages:

  * pure Python, so shipping it to Lambda (or even installing locally) would be greatly simplified
  * supports Python 3
  * a much better API (in my opinion)

**Comment by kapilt** [comment]
interesting, thanks, that's definitely worth exploring even just on the basis of simplifying the install (strong preference to avoid checking in binaries into the repo).
