### ISSUE TITLE
related resource filter can depend on a side-effect

### ISSUE THREAD

**Issue by skurfer** [capitalone/cloud-custodian#644]
Given this policy based largely on the examples from #541 (and the code that fixed it), an exception will be triggered.

```
policies:
  - name: related-rds-test
    description: |
      If databse is using default security group, adjust the retention.
    resource: rds
    filters:
      - type: security-group
        match-resource: true
        key: "GroupName"
        value: "default"
    actions:
      - type: retention
        days: 14
```

Specifically, this will happen *any* time `match-resource` is `True` and `key` doesn't start with “tag:”.

```
Traceback (most recent call last):
  File "cloud-custodian/c7n/policy.py", line 167, in run
    resources = self.policy.resource_manager.resources()
  File "cloud-custodian/c7n/query.py", line 152, in resources
    return self.filter_resources(resources)
  File "cloud-custodian/c7n/manager.py", line 63, in filter_resources
    resources = f.process(resources, event)
  File "cloud-custodian/c7n/filters/related.py", line 96, in process
    return [r for r in resources if self.process_resource(r, related)]
  File "cloud-custodian/c7n/filters/related.py", line 70, in process_resource
    self.data['value'] = self.get_resource_value(
  File "cloud-custodian/c7n/filters/core.py", line 274, in get_resource_value
    self.expr = jmespath.compile(self.k)
AttributeError: 'SecurityGroupFilter' object has no attribute 'k'
```

The policy passes validation.

The problem is

https://github.com/capitalone/cloud-custodian/blob/master/c7n/filters/related.py#L69

`self.get_resource_value()` can depend on `self.k` in some cases, but that’s only set up as a side-effect of calling `self.match()`.

Just calling `self.match(None)` first will set up the properties then bail, which seems to work, but also seems like a hack.

Moving lines 68-70 down below the `for` loop also seems to work, but I'm unsure of the impact. (The calls to `self.match()` could be influenced by the change to `self.data['value']`.)

**Comment by kapilt** [comment]
i think the issue is that it should be using the passed in key/k instead of self.k
