### ISSUE TITLE
Do you have a definition of all your labels?

### ISSUE THREAD

**Issue by richnsoos** [capitalone/cloud-custodian#677]
And if so, where do you keep your definitions? For example, do you advertise somewhere what is considered a bite-sized piece of work? We are an innersource project within Capital One and we are looking to adopt / apply the labeling strategy that cloud-custodian is using. We also want to provide a short definition of what each of our labels means. Wondering where the best place to keep that info would be. Thanks for any thoughts!

**Comment by kapilt** [comment]
not really, you'll see some other projects using similiar style of hierarchy (docker, terraform, etc), i debated doing a script for the labels, but ended up just setting it up by hand. you could probably do a json file with additional metadata and a script to generate the labels on gh issues and a markdown page for additional docs.
