### ISSUE TITLE
lambda dlq support

### ISSUE THREAD

**Issue by kapilt** [capitalone/cloud-custodian#680]

**Comment by whit537** [comment]
Per call, the idea here is to expose this config in the `LambdaFunction` class(es) in mu.py.

**Comment by whit537** [comment]
I'm reading this as extend [`LambdaManager._create_or_update`](https://github.com/capitalone/cloud-custodian/blob/8d1d593e7839452c955699f04eed04842988f50b/c7n/mu.py#L319-L357).

**Comment by kapilt** [comment]
that sounds right, also while your there... we also want lambda tag support.

**Comment by kapilt** [comment]
effectively execution-mode is going to grow some more lambda config pass through
