### ISSUE TITLE
S3 'attach-encrypt' lambda unable to import module 's3crypt'

### ISSUE THREAD

**Issue by aiell0** [capitalone/cloud-custodian#689]
I am attempting to use the `attach-encrypt` action to encrypt objects in our S3 buckets. The lambda creates without a problem, but am noticing the following invocation error in the cloudwatch logs:

`Unable to import module 's3crypt': No module named ipaddress`

**Comment by kapilt** [comment]
we picked up an ipaddress module dependency

**Comment by kapilt** [comment]
if you install ipaddress module, before deploying the lambda it should be fine.
