### ISSUE TITLE
ELB set-ssl-listener-policy fails after first run when same policy name used

### ISSUE THREAD

**Issue by wallscode** [capitalone/cloud-custodian#691]
The ELB set-ssl-listener-policy command runs successfully the first time it's run against an ELB with a given SSL policy name, but after that it fails when the same policy name is used.  

The use case for needing multiple runs with the same policy name is that if someone updates the ELB policy to something out of compliance after Custodian cleaned it up, the subsequent daily/hourly run will fail to revert those changes unless a unique policy name is provided with every call.

/opinion
If you want to keep it simple with a single set-ssl-listener-policy command instead of create/delete/set commands, if a duplicate policy name is passed either ignore the attributes and issue a set command or do a deletion of the old policy and create and set the new one with the new attributes.

**Comment by kapilt** [comment]
afaicr, the same policy updates was handled a few months ago, are you seeing traceback, errors or just failure to effect the goal.

**Comment by wallscode** [comment]
Thank you for the response Kapil.  I deleted Custodian and Python and did a full reinstall of both to make sure I wasn't using any old code or utilities, and I'm still getting the error "Policy Name [SSLPolicyTest] already exists.

When I look at elb.py in c7n/resources/ I see the following code which makes me think that this is the section that's blowing up.

`try:
            client.create_load_balancer_policy(
                LoadBalancerName=lb_name,
                PolicyName=policy_name,
                PolicyTypeName='SSLNegotiationPolicyType',
                PolicyAttributes=policy_attributes)
        except ClientError as e:
            if e.response['Error']['Code'] in (
                    'DuplicatePolicyName', 'DuplicationPolicyNameException'):
                raise`

**Comment by kapilt** [comment]
yup, definitely a bug, i was looking for the traceback, but i got a copy.
