### ISSUE TITLE
Action Delete isn't working for ESS based on cloud trail

### ISSUE THREAD

**Issue by sri321** [capitalone/cloud-custodian#702]
Cloud Trail policy based on "CreateElasticsearchDomain" doesnt work.

**Comment by kapilt** [comment]
why doesn't it?

**Comment by sri321** [comment]
i dont know why exactly. the delete action works individually. it just doesnt work for cloud trail policy.

  name : elasticsearch-delete
   resource: elasticsearch
   mode:
      type: cloudtrail
      events:
        - CreateElasticsearchDomain
   actions:
     - delete

**Comment by kapilt** [comment]
some resources don't support deletion while their being created, thats an aws limitation, there's not much we can do about it. its best not to do those policies in lambda on resources that don't support deletion while their pending creation. aws has also silently changed behavior on some resources in this regard, we used to be able to delete redshift in pending state, but no longer. i've experimented with adding delay syntax for sleeping in lambda, but removed it as its not really the right answer, the right answer is just not doing those in an on create cwe lambda imo.
