### ISSUE TITLE
Custodian doesn't read aws cli default region in config

### ISSUE THREAD

**Issue by atif1996** [capitalone/cloud-custodian#711]
My cli is configured as follows: 
[default]
output = json
region = us-east-2

When I try to run the policy below, it custodian created the lambda in us-east-1 instead of us-east-2.  I would have expected the framework would create a policy in the right region.

policies:
- name: ec2-auto-tag-owner
  resource: ec2
  mode:
    type: cloudtrail
    role: arn:aws:iam:::role/TagMyEc2
    events:
        - RunInstances
    filters:
     - tag:Owner: absent
    actions:
     - type: auto-tag-creator
       tag: OwnerContact

**Comment by kapilt** [comment]
custodian defaults to us-east-1 unless another region is specified via cli or environment variable or passing explicit profile.

**Comment by atif1996** [comment]
Sounds good, I can set the AWS_DEFAULT_REGION variable, but I expect most people will expect it to follow the behavior of other aws tools that honor the settings in ~/.aws/config 

Thanks for the clarification

**Comment by kapilt** [comment]
no other language sdk parses ~/.aws/config only aws cli and some of the tools that use boto/py sdk.

**Comment by atif1996** [comment]
I can't say that I've tested this in every language, but that seems to contradict the aws documentation (link below) and my experience.  It appears to work for the AWS sdk in Python, Java, and C++ based on my testing.  Perhaps the feature was broken at the time your team looked at it?

Link: https://aws.amazon.com/blogs/security/a-new-and-standardized-way-to-manage-credentials-in-the-aws-sdks/

Relevant section of the documentation: 
**Specifying Credentials Using a Profile Name**
If you don’t pass any credential information during initialization, and if the credentials are not found in the known environment variables, the SDKs look for credentials in the central credentials file. In that file, the SDKs look for a profile named [default] and use those credentials. This profile must exist in the file. As an alternative to having a [default] profile, you can point to a specific profile in these ways: ...

**Comment by kapilt** [comment]
yes ~/.aws/credential is common, ~/.aws/config is not.

**Comment by atif1996** [comment]
Fair point.  The SDK's usually require setting the region and the command line tool looks at ~/.aws/config

For custodian, do you think it best for the region to be specified in the shell environment, ~/.aws/config, or the Yaml file? 

I'm still a custodian newbie, so I don't have a strong opinion myself.

**Comment by mrpudn** [comment]
@kapilt Under the covers, `boto3` will honor the default region defined in your `~/.aws/config` file ([`relevant docs`](http://boto3.readthedocs.io/en/latest/guide/quickstart.html#configuration)) - should custodian intervene here and impose its own defaults (`us-east-1`)?

**Comment by kapilt** [comment]
i'm aware, the issue is thats an implementation detail of a particular sdk not a standard across.

**Comment by kapilt** [comment]
so i think the right thing, given we have compatibilty concerns on that default us-east-1, is to read the config ini file, and use that as a default if present.

**Comment by scotwk** [comment]
@kapilt - When reading the config file, if a user specifies `--profile` on the command line should I read that section of the config file?  I wasn't sure if that was referring to the same profile.

**Comment by whit537** [comment]
@scotwk That cli [option](https://github.com/capitalone/cloud-custodian/blob/24bdc7ab00f634629ef1a38170cc35a84a78feca/c7n/cli.py#L41-L43) is [passed](https://github.com/capitalone/cloud-custodian/blob/24bdc7ab00f634629ef1a38170cc35a84a78feca/c7n/credentials.py#L40) to a boto3 [session](http://boto3.readthedocs.io/en/latest/reference/core/session.html), so ... yes. :-)

**Comment by kapilt** [comment]
okay, after some experimentation its become clear, that doing anything outside of letting the sdk handle this just increases complexity significantly, going to punt on having a default in c7n.

**Comment by kapilt** [comment]
removed default region in custodian, everything defers to sdk now, there's too much logic in there for us to intercept and set an additional default without more complexity then is warranted.
