### ISSUE TITLE
filter name instance-state-name does not exist for ec2

### ISSUE THREAD

**Issue by awolde** [capitalone/cloud-custodian#722]
Seems like the doc is outdated, it took me a while to realize that all the filters listed here are not supported - http://www.capitalone.io/cloud-custodian/docs/policy/resources/ec2.html

**Comment by tim-elliott** [comment]
The documentation showing instance-state-name is for "query" not "filters".  This is a valid filter for an AWS CLI query, which is what the "- query" type represents.  See http://www.capitalone.io/cloud-custodian/docs/quickstart/tagCompliance.html for an example of its use.

**Comment by kapilt** [comment]
query parameters of which instance-state-name is represent server side query filtering, only a few resources support them (ec2, emr), their useful, but require extra api calls/cache key entries for each server side query. its generally better to just use the filters on the equivalent when possible. ie 
```
filters:
  - State.Name: running
```

is equivalent in terms of the instances it will match for an ec2 policy as the query on instance-state-name.

we're in progress on some doc improvements.
