### ISSUE TITLE
IAM Policy Requirements For Running Custodian in Ec2

### ISSUE THREAD

**Issue by elangoganesan** [capitalone/cloud-custodian#727]
Hi ,

We are Planning to Run Custodian in a ec2 instance . What we are struggling with is the iam role with policies that we need to assign to the box on which custodian is running .Do you guys have recommended iam polciy document that we can leverage . Appreciate  your help.

thanks,
Elango

**Comment by kapilt** [comment]
Depends on what your using it for. Ie a set of policies with no actions could run with a read only role, the full set of permissions depends on the actions, filters in use and the policy resource type. we have a backlogged story to generate iam policies from config files.
