### ISSUE TITLE
Implement tab completion

### ISSUE THREAD

**Issue by whit537** [capitalone/cloud-custodian#740]
Under https://github.com/capitalone/cloud-custodian/pull/736#pullrequestreview-13549396, I find myself hitting `custodian schema e<tab>`. Would be swell to have that do the thing we all know it should do. ;-)

**Comment by kapilt** [comment]
that would be awesome

**Comment by kapilt** [comment]
there's some extant argparse tab completion, but might need something more custom for schema

**Comment by whit537** [comment]
When I've seen this before, it's been a bash thing (django has it, iirc).

**Comment by kapilt** [comment]
sure its typically something like this https://argcomplete.readthedocs.io/en/latest/ or explicitly done, and it requires some integration into the user env, for dynamic completion the app has to do some specific integrations

**Comment by scotwk** [comment]
Agreed - this is something I was thinking about while implementing the schema subcommand.
