### ISSUE TITLE
Download of the Cloud Custodian Current Policies?

### ISSUE THREAD

**Issue by Kolafunmiloye** [capitalone/cloud-custodian#750]
Hello Team, 
I am very new to Cloud Custodian, can someone please point me to where one can download the current cloud custodian policies? Need to review the rules for a new project that I am a part of.

Thanks, have a great day,

Kay.

**Comment by kapilt** [comment]
custodian is a rules engine, outside of docs examples and some presentations, we don't distribute any particular set of rules (aka policies) at the moment. there are quite literally millions of possible policies that can be constructed with custodian. 

i think there is some interest in having some more in-depth and ready to use rule policies out there as more complete examples. i think one targeting the cis benchmark will probably be our initial example.

in the mean time have a look at the extant examples and docs, and the `custodian schema` cli. The later is our complete guide to available resources, filters, and actions.
