### ISSUE TITLE
How to execute a policy ( yaml ) file as a lambda function

### ISSUE THREAD

**Issue by vijayrcse** [capitalone/cloud-custodian#772]
Hi,

I have created a policy document as .yaml file and it works very well when i execute from command line

custodian run -c my_first_polict.yaml -s /home/ec2-user/custodian/output -r us-west-2

Howvever i want to run this as a lambda function with below addition

	mode:
	  type: periodic
	  schedule: "rate(1 hour)"
	  role: lambda_start_stop_role

When i try to execute it lambda log say as below
{
  "errorMessage": "Syntax error in module 'lambda_function'"
}
Could you please advice how could i execute this as a lambda func? ( it supports only python, node.js and java )

**Comment by kapilt** [comment]
syntax error sounds quite strange.

what os are you using?, what version of python, what version of custodian? what's the output of running custodian?

**Comment by kapilt** [comment]
oh are you trying to copy and paste the the yaml file as a lambda policy? that won't work, you use custodian to deploy the yaml file, after adding the mode information to the policy.

**Comment by vijayrcse** [comment]
yes i am copied the yaml file content and pasted into "Code"  block of AWS Lambda

Do i have to create a python script and call the below command in that ?
custodian run -c my_first_polict.yaml -s /home/ec2-user/custodian/output -r us-west-2
 and make that python script as lambda function ?

**Comment by vijayrcse** [comment]
can you please tell me what command should i use to achieve the below ?

_"you use custodian to deploy the policy as a lambda function, after adding the mode information to the policy"_

**Comment by kapilt** [comment]
if your policy yaml specifies a mode and events to subscribe to running the custodian command line will provision the lambda for you and hook up the event sources. ie. the output of a `custodian run -c config.yml` is a provisioned lambda and its event source.

**Comment by kapilt** [comment]
complete but contrived example
```
policies:
   - name: ec2-tag-compliance
     resource: ec2
     mode:
      - type: config-rule
         role: insert_your_lambda_role_arn
     filters:
      - "tag:appname": absent
```

now run the policy
```custodian  run -c policy.yml```

and the lambda is deployed, as a custom config rule to validate that ec2 instances have the required tag else they are marked non compliant by config

**Comment by vijayrcse** [comment]
thanks Kapil

**Comment by kiranbapat** [comment]
Hi kapil,

Is it possible to invoke custodian run command from lambda function?
or is there any way to get output of custodian run command into lambda function ?

**Comment by kiranbapat** [comment]
@kapilt 
Hi kapil,

Is it possible to invoke custodian run command from lambda function?
or is there any way to get output of custodian run command into lambda function ?
