### ISSUE TITLE
Prune dead pages on doc deploy

### ISSUE THREAD

**Issue by whit537** [capitalone/cloud-custodian#782]
At https://github.com/capitalone/cloud-custodian/pull/730#issuecomment-269743086 I asked about deploying docs. Now I see that they're deployed, but I have no idea how! Was the pipeline broken and needed to be fixed? Is doc deployment manual?

**Comment by kapilt** [comment]
its being done by .drone.yml on pushes to master

https://github.com/capitalone/cloud-custodian/blob/master/.drone.yml#L34

**Comment by whit537** [comment]
Okay. I think what's confusing me here is that when I click "Developer Install" [from the](https://github.com/capitalone/cloud-custodian/blob/30fe43c22289ba8b0492fb01b1731d8faa80756b/README.rst#links) README, I get a page the looks out of date, like a page I changed in some PR or other. What I notice now is that the page is `developer.html`, and that's a page I don't have in my local `docs/build/quickstart`. It's also not linked consistently in the navigation on prod docs (screenshots). Is that an old page that never got cleaned up? Perhaps our docs build needs an `rm -rf docs/build`?

---------------------------

![screen shot 2017-01-02 at 5 22 53 am](https://cloud.githubusercontent.com/assets/134455/21587533/8ebc0fc8-d0ab-11e6-9603-4a91e17a3b1e.png)

---------------------------

![screen shot 2017-01-02 at 5 22 29 am](https://cloud.githubusercontent.com/assets/134455/21587532/8ebbac90-d0ab-11e6-9722-d312a29ae52c.png)

**Comment by whit537** [comment]
> some PR or other

#730 ... my first one. :)

**Comment by whit537** [comment]
Sorry, the file is still there: [`docs/source/developer.rst`](https://github.com/whit537/cloud-custodian/commits/820577f9711248638d3dd4a72178e10b63706f7d/docs/source/developer.rst).

**Comment by whit537** [comment]
Here we go! Seems the file moved from `./quickstart/developer.html` to `./developer.html` at some point, but the README links to the old.

**Comment by whit537** [comment]
> some point

#642

**Comment by whit537** [comment]
So two bugs:

- http://www.capitalone.io/cloud-custodian/docs/quickstart/developer.html still exists
- link from README is bad

**Comment by whit537** [comment]
Yeah, here we go. When we [`make ghpages`](https://github.com/capitalone/cloud-custodian/blob/30fe43c22289ba8b0492fb01b1731d8faa80756b/.drone.yml#L44) we [copy over new files](https://github.com/capitalone/cloud-custodian/blob/30fe43c22289ba8b0492fb01b1731d8faa80756b/Makefile#L41), but we don't prune old files.

**Comment by whit537** [comment]
https://github.com/capitalone/cloud-custodian/tree/8808ba813c85bde19acff3fefc0f704b299c9a04/docs/quickstart

Also still has http://www.capitalone.io/cloud-custodian/docs/quickstart/deployment.html.

**Comment by whit537** [comment]
PR in #789.

**Comment by whit537** [comment]
Blech, #789 is insufficient.

**Comment by whit537** [comment]
https://github.com/capitalone/cloud-custodian/tree/29a2d22b6c25dac789c4a7d3f9c18e733936c3e8/docs/quickstart still has developer.html.

**Comment by whit537** [comment]
But https://github.com/capitalone/cloud-custodian/tree/gh-pages/docs/quickstart doesn't. ;-)

Okay! False alarm. We're good. 👍
