### ISSUE TITLE
Add ability to filter resources when no metrics are returned

### ISSUE THREAD

**Issue by wallscode** [capitalone/cloud-custodian#800]
When writing policies that search for specific metrics, those filters don't work as expected when no metrics are returned for the specific metric used.  Basically since no value is returned at all, custodian fails to match since there is insufficient data to evaluate.  

The specific use-case in which I was able to reproduce this issue is for ELBs that had not been used in over 2 weeks.  When I write a policy looking for a specific named ELB that I know hasn't been used in over two weeks, it works just fine until I add a filter on a metric such as RequestCount, HealthyHostCount, or UnhealthyHostCount.  Even when I put a condition such as not-equal for an obscure value such as 0.12345 it fails to return any results.

I'm thinking you'd either want a lack of a result to return a 0 value or have a unique value that can be matched in the filter such as null.

**Comment by kapilt** [comment]
what about value: insufficient-data  to trigger a match in those cases?

**Comment by wallscode** [comment]
I tried using "value: insufficient-data" but the validation failed since it's looking for a number.

`Exception: Failed to validate on policy elb-unused-report`
` 'insufficient-data' is not of type 'number'`

`Failed validating 'type' in schema[6]['properties']['value']:`
`    {'type': 'number'}`

`On instance['value']:`
`    'insufficient-data'`

**Comment by jhnlsn** [comment]
Looks like using a NOT filter should suffice.
