### ISSUE TITLE
onboard @whit537

### ISSUE THREAD

**Issue by whit537** [capitalone/cloud-custodian#802]
At our standup yesterday @dayna-c was suggesting that I should have perms to assign myself to, e.g., https://github.com/capitalone/cloud-custodian/issues/598, and change state on https://github.com/capitalone/cloud-custodian/projects/3. Is that true? :]

**Comment by whit537** [comment]
Secondly, I am hitting a permissions error trying to create a role:

> User: arn:aws:iam::644160558196:user/chad@sixfeetup.com is not authorized to perform: iam:CreateRole on resource: arn:aws:iam::644160558196:role/whit537-testing-mailer

I hit something similar under https://github.com/capitalone/cloud-custodian/pull/742, but the details are buried in private Slack, sorry.

@mandeepbal Can you get me the perms I need here?

**Comment by kapilt** [comment]
we're not setup to give out iam admin on the custodian sandbox account, we're still awaiting organizations access to setup each dev in their own sandbox with admin.

for now using the extant lambda iam role suffices, i've commented on the specific issue re exact iam permissions for doc purpose.

**Comment by whit537** [comment]
Roger that. Re: GitHub access I just responded to an invite from @jaredsmith so we should be good there. Thanks! 👍
