### ISSUE TITLE
Remove Permissions - Security Group Issue

### ISSUE THREAD

**Issue by dykemasarah** [capitalone/cloud-custodian#807]
I am having issues matching for specific security group rules when the there are multiple rules that have the same FromPort.

For Example if the Security Group ruleset looks like this:
Type | Protocol | Port Range | Source
 SSH |     TCP    |       22         | 10.1.23.2/32
 SSH |     TCP    |       22         | 0.0.0.0/0
HTTP|    TCP     |       80        | 10.1.23.2/32

Here is my CC configuration:
    resource: security-group
    filters:
      - type: ingress
        Cidr:
          value: 0.0.0.0/0
          op: eq
          value_type: cidr
    actions:
      - type: remove-permissions

However, when running this configuration, it matches on the 0.0.0.0/0 rule but ALSO any other rules that have the same port.  I only want it to match on 0.0.0.0/0 rule.

DELETES --> SSH |     TCP    |       22         | 10.1.23.2/32
DELETES --> SSH |     TCP    |       22         | 0.0.0.0/0
KEEPS  --> HTTP|    TCP     |       80        | 10.1.23.2/32

Resources File:
    "MatchedIpPermissions": [
      {
        "PrefixListIds": [],
        "FromPort": 22,
        "IpRanges": [
          {
            "CidrIp": "0.0.0.0/0"
          },
          {
            "CidrIp": "10.1.23.2/32"
          }
        ],
        "ToPort": 22,
        "IpProtocol": "tcp",
        "UserIdGroupPairs": [],
        "Ipv6Ranges": []
      }
    ],

**Comment by kapilt** [comment]
thanks for the bug report!  that leads to an interesting find, i did some testing on this, it looks like aws will combine separate rules by port using multiple ip ranges when doing a describe on the rules. i'll need to check around if this rule folding holds for other rule attribute matches. if its just ip range grouping we'll need to ungroup/multiplex by iprange before filter matching or permission removal. afaics this shouldn't affect our diff/patch implementation for security-groups.

![image](https://cloud.githubusercontent.com/assets/21650/21665326/f9379e20-d2b9-11e6-81bf-b3d4426c923c.png)

`aws ec2 describe-security-groups`

![image](https://cloud.githubusercontent.com/assets/21650/21665384/34ea20be-d2ba-11e6-8ee2-6bca8eb063b1.png)

revoking works on an individual iprange/cidr level

`aws ec2 revoke-security-group-ingress --group-id  sg-xxyyzz --cidr 0.0.0.0/0 --port 22 --protocol tcp`

`aws ec2 describe-security-groups`

![image](https://cloud.githubusercontent.com/assets/21650/21665512/e6bab498-d2ba-11e6-8030-a2e8786bf619.png)

**Comment by kapilt** [comment]
looks like we'll need to ungroup/expand on port/protocol by prefixlists, useridgroup pairs, and ipranges.

**Comment by dykemasarah** [comment]
@kapilt - WOW!  I'm super impressed at the quick response time to fix this issue.  I did some testing on it and it appears for the _most_ part it is working correctly.  Thank you so much for taking time to look at this.

I still only see one issue left when doing my testing on the security group.
**If the IpProtocol == -1 (or All Traffic) it is still doing grouping :( ** 

For example:
    "MatchedIpPermissions": [
      {
        "IpProtocol": "-1",
        "PrefixListIds": [],
        "IpRanges": [
          {
            "CidrIp": "0.0.0.0/0"
          },
          **{
            "CidrIp": "10.1.1.1/32"
          }**
        ],
        "UserIdGroupPairs": [],
        "Ipv6Ranges": []
      },
      {
        "PrefixListIds": [],
        "FromPort": 22,
        "IpRanges": [
          {
            "CidrIp": "0.0.0.0/0"
          }
        ],
        "ToPort": 22,
        "IpProtocol": "tcp",
        "UserIdGroupPairs": [],
        "Ipv6Ranges": []
      }
    ],
