### ISSUE TITLE
support system python package installation

### ISSUE THREAD

**Issue by kapilt** [capitalone/cloud-custodian#816]
Currently we have an implicit requirement for virtualenv based installations, since we're not picking up packages from dist locations. we should walk sys.path for explicit dependencies and pull them into the lambda deployment package.

**Comment by whit537** [comment]
Done in https://github.com/capitalone/cloud-custodian/pull/997, ya?

**Comment by whit537** [comment]
I'm calling this done in #997, @kapilt. Reopen if I've misunderstood.
