### ISSUE TITLE
support lambda provisioning within lambda

### ISSUE THREAD

**Issue by kapilt** [capitalone/cloud-custodian#831]
currently when provisioning we assemble the lambda archive assuming virtualenv paths (#816 for system paths), when we're in lambda exec env the layouts for sources are different, we should be aware of that to be able to generate a lambda archive from within lambda.

**Comment by kapilt** [comment]
good example might be a lambda subscribed to cwe on CreateBucket and then attaching an object encrypt lambda.

**Comment by whit537** [comment]
I think https://github.com/capitalone/cloud-custodian/pull/997 sets us up for this.

**Comment by whit537** [comment]
@kapilt What's the end product here? Do you want some helper API in mu for this? If the scope is just "support this scenario" then I believe #997 ticks that box.

**Comment by whit537** [comment]
Calling this done w/ #997. Please reopen if necessary, @kapilt.
