### ISSUE TITLE
Policy runs locally but not in lambda 

### ISSUE THREAD

**Issue by barundel** [capitalone/cloud-custodian#848]
Hello, Making real progress but hit another issue I can't seem to get past.

I have a simple policy to update a tag if one is absent, this works when I run it locally but does not via lambda. 

**Policy**:
`policies:
 - name: auto-tag-notice-mk3
   resource: ec2
   mode:
     type: cloudtrail
     events:
      - RunInstances
      - StartInstances
      - RebootInstances
      - DeleteTags
      - CreateTags
     role: arn:notshowingthatagain
   filters:
   - "tag:Owner": absent
   actions:
   - type: tag
     key: Notice
     value: Missing-Required-Tag
    actions:
      type: tag
      key: Notice
      value: Missing-Required-Tag
`

**Local Run:**
`ubuntu@ip-10-0-0-23:/usr/local/cloud-custodian$ sudo custodian run --region=eu-west-1 --output-dir=. --config=ec2-tag-not-lambda.yml
2017-01-13 16:05:43,116: custodian.policy:INFO Running policy auto-tag-not-lambda resource: ec2 region:eu-west-1 c7n:0.8.22.0
2017-01-13 16:05:43,737: custodian.policy:INFO policy: auto-tag-not-lambda resource:ec2 has count:22 time:0.62
2017-01-13 16:05:44,459: custodian.policy:INFO policy: auto-tag-not-lambda action: tag resources: 22 execution_time: 0.72`

**Lambda Run:**
```
[DEBUG]	2017-01-13T16:40:09.181Z	f2118543-d9ae-11e6-8713-d7cad9c785e9	Disabling cache
[INFO]	2017-01-13T16:40:09.183Z	f2118543-d9ae-11e6-8713-d7cad9c785e9	Found resource ids: ()
[WARNING]	2017-01-13T16:40:09.183Z	f2118543-d9ae-11e6-8713-d7cad9c785e9	Could not find resource ids
```

I have checked the lambda role permission, tried it with mine and the administrator role but it still produces the error. 

Any help would be great, so close to getting this working :)

**Comment by kapilt** [comment]
you have to spec sources ands ids, full example for point in time recovery on security groups which does the same on cwe. custodian has shortcuts for some events via specifying event name, lack of a shortcut should be a validation error and message. additional shortcuts welcome (cwe.py)

https://gist.github.com/kapilt/d5a53ae4239cecbc4e027d192423117c

**Comment by barundel** [comment]
thanks, got past that issue with that info.
