### ISSUE TITLE
If -t is supplied and all policies are filtered out we should have a warning

### ISSUE THREAD

**Issue by scotwk** [capitalone/cloud-custodian#860]
@kapilt 

Two issues here:

1) We recently added a warning when passing `-p` and that causes all the policies to be filtered out.  I think we should do this also if `-t` is supplied and all policies are filtered out.

2) The way that PolicyCollection works differs between a policy name filter and a resource type filter.  It seems like these should work the same way.

`PolicyCollection.policies()` (and `PolicyCollection.filter()` which is just another name for the `.policy()`) accept a `resource_type` argument but don't use it.

I've been playing with a fix for this, so I assigned myself the issue already.  But I wanted to get your input in case you had strong feelings on how PolicyCollection should work.

**Comment by kapilt** [comment]
1 & 2 sound good. no strong feelings on policycollection impl, different filtering behavior sounds good, but wrt to warnings a cli result helper taking collection and filter params and doing the warning would be ideal, as its a user interface construct and should be closer to the entry point. for library usage an empty set on filtering is not a warning.
