### ISSUE TITLE
[Feature Request] DynamoDB Tagging Support

### ISSUE THREAD

**Issue by wallscode** [capitalone/cloud-custodian#864]
Now that DynamoDB supports tagging of tables, I'd like to request support for querying and updating tags via Custodian.

https://aws.amazon.com/blogs/database/announcing-tagging-for-amazon-dynamodb/

**Comment by kapilt** [comment]
sounds good, it looks they used a per resource api call to fetch tags

**Comment by kumarsiyer** [comment]
@kapilt any idea when this will be implemented?

**Comment by ocampocj** [comment]
This should be taken care of with this last PR:  https://github.com/capitalone/cloud-custodian/pull/880
