### ISSUE TITLE
Please add SPDX lines in license headers.

### ISSUE THREAD

**Issue by SanthiSridharan** [capitalone/cloud-custodian#867]
Include the following lines in the license headers within the scripts. This is to ensure that the automated license scanning tools can identify the license.

SPDX-Copyright: Copyright (c) Capital One Services, LLC
SPDX-License-Identifier: Apache-2.0

**Comment by kapilt** [comment]
helpful to actually link to what sdpx is https://spdx.org/learn

**Comment by kapilt** [comment]
you'll have to explain the benefit or the use case, afaics usage in the wild is non existent,  so the value of trying to have every single project adopt a single tool's notion of metadata headers seems marginal and wishful thinking. digging into the team behind it (blackduck, hp) and the tools (java/rdf/semantic web) their offering does not inspire confidence. Can you point to some other projects that are using this format?

**Comment by kapilt** [comment]
it looks like spdx got npm registry to signup so license is selected for the package json on npm init, but that's still a far cry from per file headers.

**Comment by kapilt** [comment]
of course the irony is that none of the spdx tools seems to have this per file metadata.
