### ISSUE TITLE
iam-policy no longer works with mode: cloudtrail

### ISSUE THREAD

**Issue by zachzeid** [capitalone/cloud-custodian#873]
Unable to get mode: cloudtrail to trigger action with iam-policy.  From my understanding, iam-policy utilizes list_polices (https://docs.aws.amazon.com/IAM/latest/APIReference/API_ListPolicies.html, https://github.com/capitalone/cloud-custodian/blob/master/c7n/resources/iam.py#L84)
Attempted to use the example within the code itself and run from command line (https://github.com/capitalone/cloud-custodian/blob/master/c7n/resources/iam.py#L295-L299) which results in the following error:
https://gist.github.com/zachzeid/8a9d7b0345415a8329f91551495dfbe8

With using `mode: cloudtrail`, Custodian function does trigger, but does not invoke action:
policy: https://gist.github.com/zachzeid/44560d1cd66b0b0ceab25dd5c0d31c9c

The custodian function logs this to Cloudwatch Logs (https://gist.github.com/zachzeid/ca6a007a1f8cbd49f28743d5cb084219).  I suspect because the `responseElements` is null, it won't return any resource id to trigger the function.  I'm not understanding what filters need to be in place to trigger an action in this case.

**Comment by kapilt** [comment]
That first trace back, implies the custodian version in the lambda doesn't have the action, which is odd since it had to validate to deploy

**Comment by kapilt** [comment]
the issue i'm seeing is translating the event's policy arn back to a path for the resource id resolution when fetching the iam policies for c7n policy evaluation.
