### ISSUE TITLE
Request for delete action for resource Cloud Watch Alarms

### ISSUE THREAD

**Issue by sri321** [capitalone/cloud-custodian#874]
Hi,

Can you guys put in a "Delete" action for the resource "alarm"

Thank you

**Comment by kapilt** [comment]
Just to understand the use case more, What criteria would you be using to filter alarms to delete

**Comment by sri321** [comment]
StateValue and Age for now, was able to filter successfully using these two

**Comment by sri321** [comment]
Alarms have a hard limit of 5000/account as of now. We hit that and had to manually delete over 4000 alarms which were not being used at all.

**Comment by kapilt** [comment]
how do you determine not used?

**Comment by sri321** [comment]
@kapilt :Once an instance gets deleted, its cloud watch alarm stays behind(doesn't get deleted). We rehydrate our instances every 100 days, after the instance gets deleted it goes into  "StateValue: INSUFFICIENT_DATA" and we can filter the age based on the updated timestamp of the "AlarmConfigurationUpdatedTimestamp"

**Comment by siddartha1992** [comment]
+1, we are also in need for this action. 

Thanks.
