### ISSUE TITLE
Allow multiple policy files to be specified.

### ISSUE THREAD

**Issue by AMeng** [capitalone/cloud-custodian#882]
When you have quite a few policies, it becomes unwieldy to have them all in a single YAML file. Its better to split out the policies into separate files. Instead of specifying a single policy file, it would be nice to either specify a directory, or some sort of glob.
Something like:

```
custodian run -c policies
```

or:

```
custodian run -c policies/*.yml
```

**Comment by kapilt** [comment]
sounds good

**Comment by kapilt** [comment]
released in 0.8.23.0 ... not sure if it supports wildcards directly, but shell expansion should handle that.
