### ISSUE TITLE
Question around caching

### ISSUE THREAD

**Issue by vijayrcse** [capitalone/cloud-custodian#886]
Hi 

I have my yaml where i have defined two policies for the same resource type( ec2) one after the other

**1st Policy :** 
It identifies certain ec2 instance based on a criteria and tags with some values( action )

**2nd Policy :** 
Based on the tagging done by first policy it takes some other action

What we notice is even though 1st policy performs the action correctly, the 2nd policy is not able to detect that in filter criteria. Returning no resources even though the tagging is done and available

is there a cache exist ? is there a way to disable the cache on certain yaml files only ?

Please advise

**Comment by kapilt** [comment]
there is a default cache which is region aware, but is not account aware, see `custodian run --help` for options, but we should be caching pre filtering so multiple policies against the same resource should run fine, you can pass in a different cache file with -f or set the cache period.

**Comment by vijayrcse** [comment]
thanks kapil will take a look at the options available

**Comment by kapilt** [comment]
could you give an example / use case where you want to have consecutive modifications in different policies using the previous policy actions as filters for the second in the same custodian execution. typically we stage those across multiple executions of custodian (ie. effectively a time based workflow) or combine the policies if they want to be atomic in the same exec.  effectively each policy is independently reading from the cache.

**Comment by vijayrcse** [comment]
hi kapil
the use case is tag compliance policy. Previously

1st Policy :
Find ec2 instances that are missing with certain tags and mark for stop

2nd Policy :
Find ec2 instances that are missing with certain tags and it is also m,arked for stop 
if so take an action to 'Stop' the instance


Previously I had both the tags in same policy document with different trigger ( time based ) one after the other, 5 mins interval.
But since both using same cache file , the second policy is not executing stop action as it did not have correct filter results.

I separated the policy into separate files , with separate cache files executing one after the other within 5 min interval..

**Comment by kapilt** [comment]
i guess my point with that example is there isn't any real value in separating the policies afaics if you want to stop the instances during that same execution. just stop and tag them in the first policy. executing on that short of a frequency 5m also seems strange, seems like this policy would be better suited as a config rule lambda policy.  many times its easier to start a discussion/question with what your actually trying to do, aka the goal.
