### ISSUE TITLE
Question: is there a way to parameterize the queue for an action notification of a policy?

### ISSUE THREAD

**Issue by caversa** [capitalone/cloud-custodian#894]
I have been experimenting with email notifications with policies, and the process is working well.  However, I'd like to not have to explicitly imbed the queue name in every policy definition, as we'll be deploying the same set of policies in several accounts, and each has its own queue.  The queue is the same as what is associated with the Custodian Mailer Lambda function that is running in each account.

We'd ideally like to keep the accounts completely separate (not share a queue across accounts).  Is there a way to parameterize this, use an environment variable, etc. so that I don't hard code it into each policy?  Or - if it can be fetched from the value set for the Custodian Mailer function, that would be ideal as well.  Any advice would be greatly appreciated.

**Comment by kapilt** [comment]
while i've been resistant to variable interpolation in config files, this is probably an appropriate use case to enable better policy reuse. env vars are a little implicit and have implications on the various runtime modes we support. i think we can probably extend run cli with --vars and take a vars file with some simple value interpolation, no loops or conditionals though, probably doing interpolation pre yaml load. when we bake policy for lambda execution we'll bake in a post interpolated version.

alternatively generating your config with the interpolation out of band. also while not the same worth looking into advanced yaml syntax for avoiding repetition of common blocks (anchors and aliases).

**Comment by caversa** [comment]
Ultimately what I'm doing is providing templates for account owners to run if they'd like to - and my plan will be to give them scripts to create a role and queue ahead of time.  So in the end, for every account there is a cloud-custodian-role and a cloud-custodian-queue but since the full arn is required each time (which includes the account number) that is where I need the parameterization.  Since I can pass in the arn for the role, I'm OK, but I can't do that for the queue.  If there was a way for the arn to be generated based upon the account, that would also fully solve it for me.  By the way, I think this is a really terrific, powerful tool.  I'm really enjoying working with it thus far!

**Comment by kapilt** [comment]
filed as separate issue (#938) for variable interpolation.

**Comment by kapilt** [comment]
fwiw account queue arn does now support account id variable interpolation.

**Comment by caversa** [comment]
Kapil, 

Can you please direct me to the doc for this, or provide a sample?  I'd love to use this. 

Thanks,
Carrie
