### ISSUE TITLE
Add data pipeline resource

### ISSUE THREAD

**Issue by tim-elliott** [capitalone/cloud-custodian#909]
We need the ability to limit who can launch a Data Pipeline but no datapipeline resource is available.  At a minimum we would want to have tag, untag, mark-for-op, notify, and delete actions, and the and, marked-for-op, or, and value filters should be available.

**Comment by kapilt** [comment]
@whit537 thanks

**Comment by whit537** [comment]
PR w/ verbose logging in https://github.com/whit537/cloud-custodian/pull/3.

**Comment by whit537** [comment]
Abbreviate to `dp` (or other?) or use `datapipeline`?
