### ISSUE TITLE
Can Cloud Custodian be used to check servers with open ports?

### ISSUE THREAD

**Issue by victorh3** [capitalone/cloud-custodian#915]
For example, can I use Cloud Custodian to check if any server has port 80 open?

**Comment by kapilt** [comment]
we don't have any filters that assume tcp connectivity to a server at the moment, extant all operates against the aws api endpoints, happy to accept pull-requests for a filter that does a check.

we do have filter can check security groups of any network attached resource (ec2 instance, etc)  by attribute and separately atm to filter security groups on allowed ingress/egress rules (ports, protocols, cidrs, etc).

**Comment by victorh3** [comment]
Could you provide a link to the documentation for that? Or a sample policy to see what the implementation looks like?

**Comment by kapilt** [comment]
docs are builtin to the cli via `custodian schema security-group.filters.ingress` `custodian schema security-group.filters.egress`  and `custodian schema ec2.filters.security-group`

**Comment by kapilt** [comment]
for some reason the best docs on this topic didn't make it to custodian schema command or our public docs. here's a link re ingress/egress filtering on a security group
https://github.com/capitalone/cloud-custodian/blob/master/c7n/resources/vpc.py#L478
