### ISSUE TITLE
Add CloudTrail logging and Redshift logging accounts to S3CrossAccountFilter

### ISSUE THREAD

**Issue by tim-elliott** [capitalone/cloud-custodian#916]
It would be useful to have the CloudTrail logging and Redshift logging region accounts as part of S3CrossAccountFilter.  These can be found at http://docs.aws.amazon.com/awscloudtrail/latest/userguide/cloudtrail-supported-regions.html and http://docs.aws.amazon.com/redshift/latest/mgmt/db-auditing.html, respectively.

**Comment by kapilt** [comment]
thanks, probably should parameterize (services: [cloudtrail, elb]) on the filter with a default of all.
