### ISSUE TITLE
S3 bucket deletion to use as_completed

### ISSUE THREAD

**Issue by ocampocj** [capitalone/cloud-custodian#927]
Currently, S3 bucket deletions are not using 'as_completed' and as a result, any deletes that fail blow up and cause the rest of the buckets in the list to get ignored.  We should move to as_completed, in order to reduce the possibility of missing buckets for deletion.

**Comment by whit537** [comment]
Instead of doing concurrent_futures.map, use `.submit`, collect all futures, if one dies, log it and continue on to the next one. Goal is to avoid failing hard on all if a single future fails.

**Comment by ocampocj** [comment]
@whit357 - sounds good, and yes that's the intent.

**Comment by whit537** [comment]
@ocampocj For context, I was channeling @kapilt from this morning's call. Can't take credit myself! :-)
