### ISSUE TITLE
Is there a way get the attach time of an ebs volume?

### ISSUE THREAD

**Issue by victorh3** [capitalone/cloud-custodian#928]
I'm looking to get a list of EBS volumes that have been unattached for longer than 30 days. The example for garbage collection doesn't check for attach time and I can't find much information on the documentation nor schema.

**Comment by kapilt** [comment]
attach time is not a direct attribute if a volume isn't attached. 

we typically manage this two ways, one is a multi-policy workflow around garbage collecting unattached volumes as follows.

 - step1. tag ebs volumes that aren't attached with a mark-for-op action 30 days out to delete
 - step2 untag ebs volumes that are attached
 - step3  delete volumes that have been marked for 30 days.

and then run those policies daily.

The other is too record attachment time and copy instance tags to their attached volumes using `$ custodian schema ebs.actions.copy-instance-tags` doc output below.

```
$ custodian schema ebs.actions.copy-instance-tags

Help
----

Copy instance tags to its attached volume.

Useful for cost allocation to ebs volumes and tracking usage
info for volumes.

Mostly useful for volumes not set to delete on termination, which
are otherwise candidates for garbage collection, copying the
instance tags gives us more semantic information to determine if
their useful, as well letting us know the last time the volume
was actually used.

:example:

    .. code-block: yaml

        policies:
          - name: ebs-copy-instance-tags
            resource: ebs
            filters:
              - type: value
                key: "Attachments[0].Device"
                value: not-null
            actions:
              - type: copy-instance-tags
                tags:
                  - Name

Schema
------

{   'additionalProperties': False,
    'properties': {   'tags': {   'items': {   'type': 'string'}, 'type': 'array'},
                      'type': {   'enum': ['copy-instance-tags']}},
    'required': ['type'],
    'type': 'object'}
```
