### ISSUE TITLE
s3 action - enable/suspend versioning

### ISSUE THREAD

**Issue by kapilt** [capitalone/cloud-custodian#933]
ideally with optional lifecycle policy for archiving.

**Comment by ocampocj** [comment]
Hey @kapilt - any updates on this?

**Comment by scotwk** [comment]
@ocampocj @kapilt - I was going to pick this one up but I dug in and it appears to be (partially?) done.  There is already a `toggle-versioning` action in S3.  The docstring was wrong, so I am about to submit a PR that fixes it.  Problems with the docstring:

 - syntax error - `filter` needed to be `filters`
 - the key was wrong.  `Versioning` should have been `Versioning.Status`
 - when a bucket never had versioning enabled, it just returns an empty dictionary for the Versioning key (`Versioning: {}`).  So if the goal is to enable versioning for any buckets that have it turned off, you would need to add a second conditional where the `Status` is missing.

Chris - does this do what you are hoping to do?  (It doesn't look to do any lifecycle stuff, is that important?)
