### ISSUE TITLE
Offhours limited timezone support

### ISSUE THREAD

**Issue by aiell0** [capitalone/cloud-custodian#942]
The offhours filter has very limited timezone support. I'm referring to the following structure:

```
    TZ_ALIASES = {
        'pdt': 'America/Los_Angeles',
        'pt': 'America/Los_Angeles',
        'pst': 'America/Los_Angeles',
        'est': 'America/New_York',
        'edt': 'America/New_York',
        'et': 'America/New_York',
        'cst': 'America/Chicago',
        'cdt': 'America/Chicago',
        'ct': 'America/Chicago',
        'mt': 'America/Denver',
        'gmt': 'Europe/London',
        'gt': 'Europe/London'}
```

These only support regions `us-east-1, us-east-2, us-west-1, us-west-2, ca-central-1, eu-central-1, eu-west-1, and eu-west-2`. Can additional timezones be added to support other AWS regions?

**Comment by kapilt** [comment]
note this is just a set of shortcuts, long form names can be passed for other locations.

**Comment by aiell0** [comment]
While this may be true for using default offhours schedules, this breaks down when the custom `maid_offhours` tag is used to define the timezone. For example, the following custom tag will incur a parsing error:

`off=[(M-F,21),(U,18)];on=[(M-F,6),(U,10)];tz=ist` (For Indian Standard Time, which Mumbai runs in)
or:
`off=[(M-F,21),(U,18)];on=[(M-F,6),(U,10)];tz=America/New_York`
also:
`off=[(M-F,21),(U,18)];on=[(M-F,6),(U,10)];tz="America/New_York"`

**Comment by aiell0** [comment]
Created a [pull request](https://github.com/capitalone/cloud-custodian/pull/948) to resolve this issue.

**Comment by kapilt** [comment]
good point, and thanks for the PR!
