### ISSUE TITLE
s3 encryption

### ISSUE THREAD

**Issue by willjgillen** [capitalone/cloud-custodian#946]
Policy below isn't obeying the "key-id" and taking the default key instead. Also once this works will it switch the key to the one provided in the policy should it mis-match?

policies:
  - name: s3-key-encryption
    resource: s3
    actions:
      - type: encrypt-keys
        crypto: aws:kms
        key-id: 486820a6-bafc-4cf9-aa0f-f837879075ba

**Comment by kapilt** [comment]
looks like a bad comparison resulted in omission of SSEKmsKeyId in the copy request, plus the test around this wasn't extensive enough to verify the key id. i've fixed that in #959 and added support for re-keying if your specifying key-id. also note that for any significant volume of keys, i'd recommend looking at tools/c7n_salactus as it provides scale out s3 semantics.

**Comment by willjgillen** [comment]
@kapilt unless I'm missing something the re-key feature isn't working.  If there is an object not encrypted then it copied fine with my defined key however objects using the default key are not copied with the updated key.
thanks
