### ISSUE TITLE
Empty policy files exit with error code of 1

### ISSUE THREAD

**Issue by mandeepbal** [capitalone/cloud-custodian#949]
I'm experiencing an issue with custodian returning an error if you try to run a yml file with zero policies. This behavior in `0.8.23.0` is a depature from previous version where it would return an exit code of `0`.

```
2017-02-17 14:05:03,027: custodian.commands:DEBUG Loaded file /custodian/policy.yml. Contains 0 policies (after filtering)
Error: empty policy file(s).  Nothing to do.
```

Where in the code the error is coming from:
https://github.com/capitalone/cloud-custodian/blob/6304ba2167ff2dbbaf2a9724ca8aa803667f4918/c7n/commands.py#L86-L101

**Comment by kapilt** [comment]
so i think if the policy file is empty we can exit 0, if we get to an empty list as a result of filtering  (name, or type) i think we should continue to exit 1

**Comment by scotwk** [comment]
@kapilt - I am happy to fix this if you aren't on it already - I wrote that code.

**Comment by scotwk** [comment]
@mandeepbal @kapilt 

The behavior I fixed when I touched this code last was that specifying an empty config file resulted in a huge schema dump, not a sensible error message.  This was an issue I filed - #859.  But I did not change the exit code as far as I can tell.

I just checked out releases dating back six months, but they all have exit code 1 if the policy file is empty (both if the file is totally empty, and also if it has a `policies:` line, but no policies specified).

What is your input that is causing this @mandeepbal, and what version was it zero?

**Comment by kapilt** [comment]
i believe the input was

```
policies: []
```

**Comment by scotwk** [comment]
@kapilt : Yeah - using that policy I am able to replicate what @mandeepbal is saying wrt the `run` subcommand.  But historically, the `report` and `logs` subcommands would both exit 1 if there were no policies supplied.

Those work a little different than `run` because they want one - and only one - policy while `run` accepts any number.  But which behavior do we want?  Should they match how `run` works and exit 0?  Or should they behave differently on that edge case?

**Comment by cjsandeep** [comment]
Hey Everyone. I've been getting the same error for literally every code I've been trying implement.

**Comment by cjsandeep** [comment]
Is this an spacing issue?

**Comment by scotwk** [comment]
@cjsandeep - the issue from this was fixed a long time ago.  Can you show the policy you are trying along with the error it is returning?

**Comment by manitmalik** [comment]
policies:
  - name: tag-compliance
    resource: ec2
    description: |
        Identify resources that does not meet tag compliance policies to be notified via email
    filters: 
      - tag:Contact : absent
      - tag:Service : absent
      - tag:Environment : absent
    actions: 
      - type: notify
        template: default
        priority_header: '2'
        subject : Test8 with default
        to:
            - <email address>
        transport:
            type: sqs
            queue: <queue url>

Getting the same error on this policy
