### ISSUE TITLE
Bug with Health Filter Schema

### ISSUE THREAD

**Issue by mchen804** [capitalone/cloud-custodian#951]
I believe the enum in the new Health-event filter schema has a bug. The line in question is here https://github.com/capitalone/cloud-custodian/blob/master/c7n/filters/health.py#L32

Currently the schema only allows the open health-event status, but there are two more statuses (upcoming and closed) which are not allowed by the schema

**Comment by kapilt** [comment]
upcoming support merged by your pull request. open to supporting closed but don't have a use case at the moment. closing this out for now, prs welcome if anyone finds it of use.
