### ISSUE TITLE
html email template - default.html.j2 not working

### ISSUE THREAD

**Issue by arunbagadi** [capitalone/cloud-custodian#974]
I am using c7n mailer tool to send notification. Lambda function is working fine if I use default template (default.j2)  but getting below error when  I use html template (default.html.j2). 

Error 
    [ERROR] 2017-02-22T23:24:55.830Z	1e4af0ac-f956-11e6-b810-11db18d264a0	Invalid template reference default.html.j2

Policy 

    policies:
  - name: ec2-underutilized
    resource: ec2
    filters:
      - type: metrics
        name: CPUUtilization
        days: 4
        period: 86400
        value: 10
        op: less-than
    actions:
      - type: notify
        template: default.html
        subject: Ec2 underutilized report
        to:
          - xxxxx@gmail.com
        transport:
          type: sqs
          queue: https://sqs.us-east-1.amazonaws.com/10838310/mailer-test

**Comment by kapilt** [comment]
that implies your mailer lambda hasn't been updated with a version that has the default.html.j2 template.

**Comment by arunbagadi** [comment]
Thanks Kapil.  Its working after mailer lambda update.

**Comment by arunbagadi** [comment]
Gmail blocking CSS in emails.

**Comment by abhilash14j** [comment]
@arunbagadi can you describe how to update the mailer lambda, please ? Thanks
