### ISSUE TITLE
ec2 image filters don't support public AMIs

### ISSUE THREAD

**Issue by Sutto** [capitalone/cloud-custodian#979]
Based on the implementation of the ami resource, which is restricted to images owned by self, you can't actually fetch AMI's for instances that are using non-self owned images.

it'd be useful to be able to filter on details of all images, e.g. to be able to find instances running AMIs not owned by yourself and actually act on them as a catch all.

I'm working on a PR to do this, but wanted to raise it here first so there is some context.

**Comment by kapilt** [comment]
merged
