### ISSUE TITLE
Modify value_from filter to read data as Key-Value pairs

### ISSUE THREAD

**Issue by salwandhruvdev** [capitalone/cloud-custodian#993]
Currently we have the ability to read csv files using value_from filter. Custodian reads data from the csv file into a list. 'expr' used for searching that list data is a bit complicated.

It would be useful if we can parse csv data as a dictionary, with Keys as headers and corresponding column values.

**Comment by scotwk** [comment]
@salwandhruvdev - What would you do if there are duplicate headers?  Keys in a python dictionary must be unique.

**Comment by scotwk** [comment]
@salwandhruvdev - merged in #1069 

Use the alternate format `csv2dict` when you want this behavior.  If there is any documentation you see that needs updating, let me know and I will take care of it.
