### ISSUE TITLE
Multiple tag filters don't work as described? 

### ISSUE THREAD

**Issue by ohuk1** [capitalone/cloud-custodian#995]
From the documentation it seems to me that this filter should be triggered when *either* of the filter rules is triggered. Not sure if it's me misunderstanding the documentation?

policies:

- name: ec2-validate-tag-policy
  resource: ec2
  filters:
      - "tag:Data Classification": absent
      - "tag:Environment": absent

I have three instances with the following tags:

$ aws ec2 describe-tags
{
    "Tags": [
...
        {
            "ResourceType": "instance", 
            "ResourceId": "i-07da68dec66ad98b1", 
            "Value": "Public", 
            "Key": "Data Classification"
        }, 
        {
            "ResourceType": "instance", 
            "ResourceId": "i-07da68dec66ad98b1", 
            "Value": "Prod", 
            "Key": "Environment"
        }, 
        {
            "ResourceType": "instance", 
            "ResourceId": "i-07da68dec66ad98b1", 
            "Value": "Web", 
            "Key": "Name"
        }, 
        {
            "ResourceType": "instance", 
            "ResourceId": "i-0925b1d1fd7cd8143", 
            "Value": "Public", 
            "Key": "Data Classification"
        }, 
        {
            "ResourceType": "instance", 
            "ResourceId": "i-0f94cf52d7d1c7127", 
            "Value": "database", 
            "Key": "Name"
        }, 

So, the rule should trigger twice, correct, on i-0925b1d1fd7cd8143 and i-0f94cf52d7d1c7127? However it only triggers once:

2017-03-01 16:12:38,309: custodian.policy:INFO Running policy ec2-validate-tag-policy resource: ec2 region:us-west-1 c7n:0.8.23.0
2017-03-01 16:12:40,141: custodian.policy:INFO policy: ec2-validate-tag-policy resource:ec2 has count:1 time:1.83

If I add an action:

  actions:
       - type: tag
         tag: Tag test
         value: Triggered for this instance

I see that only i-0f94cf52d7d1c7127 received the test tag, even through i-0925b1d1fd7cd8143 also should have received it? 

$ aws ec2 describe-tags
{
    "Tags": [
…. 
        {
            "ResourceType": "instance", 
            "ResourceId": "i-07da68dec66ad98b1", 
            "Value": "Public", 
            "Key": "Data Classification"
        }, 
        {
            "ResourceType": "instance", 
            "ResourceId": "i-07da68dec66ad98b1", 
            "Value": "Prod", 
            "Key": "Environment"
        }, 
        {
            "ResourceType": "instance", 
            "ResourceId": "i-07da68dec66ad98b1", 
            "Value": "Web", 
            "Key": "Name"
        }, 
        {
            "ResourceType": "instance", 
            "ResourceId": "i-0925b1d1fd7cd8143", 
            "Value": "Public", 
            "Key": "Data Classification"
        }, 
        {
            "ResourceType": "instance", 
            "ResourceId": "i-0f94cf52d7d1c7127", 
            "Value": "database", 
            "Key": "Name"
        }, 
        {
            "ResourceType": "instance", 
            "ResourceId": "i-0f94cf52d7d1c7127", 
            "Value": "Triggered for this instance", 
            "Key": "Tag test"
        }
    ]
}

Thanks in advance :-) !

**Comment by tim-elliott** [comment]
filters are "and'-ed by default, so your filter will only trigger if both tags are absent, which is what it is doing.  If you want the filter to trigger if either condition is met you need to use an "or" filter:
```
  - name: ec2-validate-tag-policy
    resource: ec2
    filters:
      - or:
        - "tag:Data Classification": absent
        - "tag:Environment": absent
````

**Comment by kapilt** [comment]
Default semantics between filter clauses are Anded you can do explicit or block to change the semantic

**Comment by kapilt** [comment]
What Tim said :)

**Comment by ohuk1** [comment]
Great - thanks guys :-) !
